AssemblerEmulator - Nikola Bebic: Code/Assembler/Include/z85.h File Reference
z85.h File Reference
#include <stddef.h>
Functions
size_t Z85_encode_with_padding (const char *source, char *dest, size_t inputSize)
Encodes 'inputSize' bytes from 'source' into 'dest'. If 'inputSize' is not divisible by 4 with no remainder, 'source' is padded. Destination buffer must be already allocated. Use Z85_encode_with_padding_bound() to evaluate size of the destination buffer.
size_t Z85_decode_with_padding (const char *source, char *dest, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source' into 'dest', encoded with Z85_encode_with_padding(). Destination buffer must be already allocated. Use Z85_decode_with_padding_bound() to evaluate size of the destination buffer.
size_t Z85_encode_with_padding_bound (size_t size)
Evaluates a size of output buffer needed to encode 'size' bytes into string of printable symbols using Z85_encode_with_padding().
size_t Z85_decode_with_padding_bound (const char *source, size_t size)
Evaluates a size of output buffer needed to decode 'size' symbols into binary string using Z85_decode_with_padding().
size_t Z85_encode (const char *source, char *dest, size_t inputSize)
Encodes 'inputSize' bytes from 'source' into 'dest'. If 'inputSize' is not divisible by 4 with no remainder, 0 is retured. Destination buffer must be already allocated. Use Z85_encode_bound() to evaluate size of the destination buffer.
size_t Z85_decode (const char *source, char *dest, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source' into 'dest'. If 'inputSize' is not divisible by 5 with no remainder, 0 is returned. Destination buffer must be already allocated. Use Z85_decode_bound() to evaluate size of the destination buffer.
size_t Z85_encode_bound (size_t size)
Evaluates a size of output buffer needed to encode 'size' bytes into string of printable symbols using Z85_encode().
size_t Z85_decode_bound (size_t size)
Evaluates a size of output buffer needed to decode 'size' symbols into binary string using Z85_decode().
char * Z85_encode_unsafe (const char *source, const char *sourceEnd, char *dest)
Encodes bytes from [source;sourceEnd) range into 'dest'. It can be used for implementation of your own padding scheme. Preconditions:
char * Z85_decode_unsafe (const char *source, const char *sourceEnd, char *dest)
Decodes symbols from [source;sourceEnd) range into 'dest'. It can be used for implementation of your own padding scheme. Preconditions:
Function Documentation
Z85_decode()
size_t Z85_decode (const char * source, char * dest, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source' into 'dest'. If 'inputSize' is not divisible by 5 with no remainder, 0 is returned. Destination buffer must be already allocated. Use Z85_decode_bound() to evaluate size of the destination buffer.
Parameters
source in, input buffer (printable string to be decoded)
dest out, destination buffer
inputSize in, number of symbols to be decoded
Returns
number of bytes written into 'dest' or 0 if something goes wrong
Definition at line 146 of file z85.cpp.
Referenced by z85::decode().
 {
     if (!source || !dest || inputSize % 5)
     {
         assert(!"wrong source, destination or input size");
         return 0;
     }
     return Z85_decode_unsafe(source, source + inputSize, dest) - dest;
 }
Z85_decode_bound()
size_t Z85_decode_bound (size_t size)
Evaluates a size of output buffer needed to decode 'size' symbols into binary string using Z85_decode().
Parameters
size in, number of symbols to be decoded
Returns
minimal size of output buffer in bytes
Definition at line 130 of file z85.cpp.
Referenced by z85::decode().
 {
     return size * 4 / 5;
 }
Z85_decode_unsafe()
char* Z85_decode_unsafe (const char * source, const char * sourceEnd, char * dest)
Decodes symbols from [source;sourceEnd) range into 'dest'. It can be used for implementation of your own padding scheme. Preconditions:
(sourceEnd - source) % 5 == 0
destination buffer must be already allocated
Parameters
source in, begin of input buffer
sourceEnd in, end of input buffer (not included)
dest out, output buffer
Returns
a pointer immediately after last byte written into the 'dest'
Definition at line 100 of file z85.cpp.
 {
     byte* src = (byte*)source;
     byte* end = (byte*)sourceEnd;
     byte* dst = (byte*)dest;
     uint32_t value;
     for (; src != end; src += 5, dst += 4)
     {
         value = base256[(src[0] - 32) & 127];
         value = value * 85 + base256[(src[1] - 32) & 127];
         value = value * 85 + base256[(src[2] - 32) & 127];
         value = value * 85 + base256[(src[3] - 32) & 127];
         value = value * 85 + base256[(src[4] - 32) & 127];
         // pack big-endian frame
         dst[0] = value >> 24;
         dst[1] = (byte)(value >> 16);
         dst[2] = (byte)(value >> 8);
         dst[3] = (byte)(value);
     }
     return (char*)dst;
 }
Z85_decode_with_padding()
size_t Z85_decode_with_padding (const char * source, char * dest, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source' into 'dest', encoded with Z85_encode_with_padding(). Destination buffer must be already allocated. Use Z85_decode_with_padding_bound() to evaluate size of the destination buffer.
Parameters
source in, input buffer (printable string to be decoded)
dest out, destination buffer
inputSize in, number of symbols to be decoded
Returns
number of bytes written into 'dest' or 0 if something goes wrong
Definition at line 203 of file z85.cpp.
Referenced by z85::decode_with_padding().
 {
     char*       dst = dest;
     size_t      tailBytes;
     char        tailBuf[4] = { 0 };
     const char* end = source + inputSize;
     assert(source && dest && (inputSize == 0 || (inputSize - 1) % 5 == 0));
     // zero length string is not padded
     if (!source || !dest || inputSize == 0 || (inputSize - 1) % 5)
     {
         return 0;
     }
     tailBytes = (source++)[0] - '0'; // possible values: 1, 2, 3 or 4
     if (tailBytes - 1 > 3)
     {
         assert(!"wrong tail bytes count");
         return 0;
     }
     end -= 5;
     if (source != end)
     {
         // decode body
         dst = Z85_decode_unsafe(source, end, dst);
     }
     // decode last 5 bytes chunk
     Z85_decode_unsafe(end, end + 5, tailBuf);
     switch (tailBytes)
     {
     case 4:
         dst[3] = tailBuf[3];
     case 3:
         dst[2] = tailBuf[2];
     case 2:
         dst[1] = tailBuf[1];
     case 1:
         dst[0] = tailBuf[0];
     }
     return dst - dest + tailBytes;
 }
Z85_decode_with_padding_bound()
size_t Z85_decode_with_padding_bound (const char * source, size_t size)
Evaluates a size of output buffer needed to decode 'size' symbols into binary string using Z85_decode_with_padding().
Parameters
source in, input buffer (first symbol is read from 'source' to evaluate padding)
size in, number of symbols to be decoded
Returns
minimal size of output buffer in bytes
Definition at line 164 of file z85.cpp.
Referenced by z85::decode_with_padding().
 {
     if (size == 0 || !source || (byte)(source[0] - '0' - 1) > 3) return 0;
     return Z85_decode_bound(size - 1) - 4 + (source[0] - '0');
 }
Z85_encode()
size_t Z85_encode (const char * source, char * dest, size_t inputSize)
Encodes 'inputSize' bytes from 'source' into 'dest'. If 'inputSize' is not divisible by 4 with no remainder, 0 is retured. Destination buffer must be already allocated. Use Z85_encode_bound() to evaluate size of the destination buffer.
Parameters
source in, input buffer (binary string to be encoded)
dest out, destination buffer
inputSize in, number of bytes to be encoded
Returns
number of printable symbols written into 'dest' or 0 if something goes wrong
Definition at line 135 of file z85.cpp.
Referenced by z85::encode().
 {
     if (!source || !dest || inputSize % 4)
     {
         assert(!"wrong source, destination or input size");
         return 0;
     }
     return Z85_encode_unsafe(source, source + inputSize, dest) - dest;
 }
Z85_encode_bound()
size_t Z85_encode_bound (size_t size)
Evaluates a size of output buffer needed to encode 'size' bytes into string of printable symbols using Z85_encode().
Parameters
size in, number of bytes to be encoded
Returns
minimal size of output buffer in bytes
Definition at line 125 of file z85.cpp.
Referenced by z85::encode().
 {
     return size * 5 / 4;
 }
Z85_encode_unsafe()
char* Z85_encode_unsafe (const char * source, const char * sourceEnd, char * dest)
Encodes bytes from [source;sourceEnd) range into 'dest'. It can be used for implementation of your own padding scheme. Preconditions:
(sourceEnd - source) % 4 == 0
destination buffer must be already allocated
Parameters
source in, begin of input buffer
sourceEnd in, end of input buffer (not included)
dest out, output buffer
Returns
a pointer immediately after last symbol written into the 'dest'
Definition at line 77 of file z85.cpp.
 {
     byte* src = (byte*)source;
     byte* end = (byte*)sourceEnd;
     byte* dst = (byte*)dest;
     uint32_t value;
     uint32_t value2;
     for (; src != end; src += 4, dst += 5)
     {
         // unpack big-endian frame
         value = (src[0] << 24) | (src[1] << 16) | (src[2] << 8) | src[3];
         value2 = DIV85(value); dst[4] = base85[value - value2 * 85]; value = value2;
         value2 = DIV85(value); dst[3] = base85[value - value2 * 85]; value = value2;
         value2 = DIV85(value); dst[2] = base85[value - value2 * 85]; value = value2;
         value2 = DIV85(value); dst[1] = base85[value - value2 * 85];
         dst[0] = base85[value2];
     }
     return (char*)dst;
 }
Z85_encode_with_padding()
size_t Z85_encode_with_padding (const char * source, char * dest, size_t inputSize)
Encodes 'inputSize' bytes from 'source' into 'dest'. If 'inputSize' is not divisible by 4 with no remainder, 'source' is padded. Destination buffer must be already allocated. Use Z85_encode_with_padding_bound() to evaluate size of the destination buffer.
Parameters
source in, input buffer (binary string to be encoded)
dest out, destination buffer
inputSize in, number of bytes to be encoded
Returns
number of printable symbols written into 'dest' or 0 if something goes wrong
Definition at line 170 of file z85.cpp.
Referenced by z85::encode_with_padding().
 {
     size_t      tailBytes = inputSize % 4;
     char        tailBuf[4] = { 0 };
     char*       dst = dest;
     const char* end = source + inputSize - tailBytes;
     assert(source && dest);
     // zero length string is not padded
     if (!source || !dest || inputSize == 0)
     {
         return 0;
     }
     (dst++)[0] = (tailBytes == 0 ? '4' : '0' + (char)tailBytes); // write tail bytes count
     dst = Z85_encode_unsafe(source, end, dst);                   // write body
                                                                  // write tail
     switch (tailBytes)
     {
     case 3:
         tailBuf[2] = end[2];
     case 2:
         tailBuf[1] = end[1];
     case 1:
         tailBuf[0] = end[0];
         dst = Z85_encode_unsafe(tailBuf, tailBuf + 4, dst);
     }
     return dst - dest;
 }
Z85_encode_with_padding_bound()
size_t Z85_encode_with_padding_bound (size_t size)
Evaluates a size of output buffer needed to encode 'size' bytes into string of printable symbols using Z85_encode_with_padding().
Parameters
size in, number of bytes to be encoded
Returns
minimal size of output buffer in bytes
Definition at line 157 of file z85.cpp.
Referenced by z85::encode_with_padding().
 {
     if (size == 0) return 0;
     size = Z85_encode_bound(size);
     return size + (5 - size % 5) % 5 + 1;
 }