AssemblerEmulator - Nikola Bebic: Code/Emulator/Source/Main.cpp File Reference
Main.cpp File Reference
#include <iostream>
#include "CommandLineHelper.h"
#include "FileReader.h"
#include "AddressSpace.h"
#include "Context.h"
#include "Processor.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 8 of file Main.cpp.
References bnssemulator::Processor::executeProgram(), bnssemulator::FileReader::parse(), and bnssemulator::CommandLineHelper::parse().
{
     try {
         auto input = bnssemulator::CommandLineHelper::parse(argc, argv);
         auto data = bnssemulator::FileReader::parse(input);
         bnssemulator::Context context(std::move(data));
         bnssemulator::Processor::executeProgram(context);
     }
     catch (const std::exception &exception) {
         std::cerr << exception.what() << std::endl;
         return EXIT_FAILURE;
     }
     catch (...) {
         std::cerr << "Unknown exception" << std::endl;
         return EXIT_FAILURE;
     }
     return EXIT_SUCCESS;
 }