AssemblerEmulator - Nikola Bebic: bnssassembler::Immediate Class Reference
bnssassembler::Immediate Class Reference
Class representing the immediate operand.
#include <Immediate.h>
Public Member Functions
Immediate (MicroRiscExpression value) noexcept
Constructs an Immediate object.
void packToInstruction (InstructionBitFieldUnion &instruction, uint32_t &second_word, std::list< RelocationRecord > &relocations) const override
Packs the operand into the instruction.
void resolveSymbols (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves the defined symbols in the expressions.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
AddressMode addressMode () const noexcept override
Gets the address mode of the operand.
Public Member Functions inherited from bnssassembler::Operand
virtual ~Operand ()=default
Private Attributes
MicroRiscExpression value_
Detailed Description
Class representing the immediate operand.
Definition at line 11 of file Immediate.h.
Constructor & Destructor Documentation
Immediate()
bnssassembler::Immediate::Immediate (MicroRiscExpression value) explicit noexcept
Constructs an Immediate object.
Parameters
value Value of the immediate operand
Definition at line 5 of file Immediate.cpp.
 : value_(value) {}
Member Function Documentation
addressMode()
AddressMode bnssassembler::Immediate::addressMode () const override virtual noexcept
Gets the address mode of the operand.
Returns
Address mode of the operand
Implements bnssassembler::Operand.
Definition at line 31 of file Immediate.cpp.
References bnssassembler::IMMEDIATE.
{
         return IMMEDIATE;
     }
packToInstruction()
void bnssassembler::Immediate::packToInstruction (InstructionBitFieldUnion & instruction, uint32_t & second_word, std::list< RelocationRecord > & relocations) const override virtual
Packs the operand into the instruction.
Parameters
instruction Reference to the first word of the instruction containing the instruction info
second_word Reference to the second word of the instruction containing the address/value/displacement
relocations Reference to the list of relocation records
Implements bnssassembler::Operand.
Definition at line 7 of file Immediate.cpp.
References bnssassembler::InstructionBitField::address_mode, bnssassembler::InstructionBitFieldUnion::bit_field, bnssassembler::MicroRiscExpression::generateRelocations(), bnssassembler::IMMEDIATE, bnssassembler::MicroRiscExpression::value(), and value_.
{
         instruction.bit_field.address_mode = IMMEDIATE;
         second_word = value_.value();
         relocations.splice(relocations.end(), value_.generateRelocations());
     }
resolveCurrentPcSymbol()
void bnssassembler::Immediate::resolveCurrentPcSymbol (size_t section_index, size_t offset) override virtual noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Reimplemented from bnssassembler::Operand.
Definition at line 27 of file Immediate.cpp.
References bnssassembler::MicroRiscExpression::resolveCurrentPcSymbol(), and value_.
{
         value_.resolveCurrentPcSymbol(section_index, offset);
     }
resolveImports()
void bnssassembler::Immediate::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates the relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Operand.
Definition at line 23 of file Immediate.cpp.
References bnssassembler::MicroRiscExpression::resolveImports(), and value_.
{
         value_.resolveImports(imported_symbols);
     }
resolveSymbols()
void bnssassembler::Immediate::resolveSymbols (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves the defined symbols in the expressions.
Parameters
symbols Collection of symbol definitions
Reimplemented from bnssassembler::Operand.
Definition at line 13 of file Immediate.cpp.
References bnssassembler::MicroRiscExpression::setValue(), and value_.
{
         for (auto &symbol : symbols) {
             value_.setValue(symbol.name(), symbol.expression());
         }
     }
resolveSymbolTable()
void bnssassembler::Immediate::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates the relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Operand.
Definition at line 19 of file Immediate.cpp.
References bnssassembler::MicroRiscExpression::resolveSymbolTable(), and value_.
{
         value_.resolveSymbolTable(symbol_table);
     }
Member Data Documentation
value_
MicroRiscExpression bnssassembler::Immediate::value_ private
Definition at line 26 of file Immediate.h.
Referenced by packToInstruction(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbols(), and resolveSymbolTable().
The documentation for this class was generated from the following files:
Code/Assembler/Include/Immediate.h
Code/Assembler/Source/Immediate.cpp