AssemblerEmulator - Nikola Bebic: cxxopts::Options Class Reference
cxxopts::Options Class Reference
#include <cxxopts.h>
Public Member Functions
Options (std::string program, std::string help_string="")
Options & positional_help (std::string help_text)
void parse (int &argc, char **&argv)
OptionAdder add_options (std::string group="")
void add_option (const std::string &group, const std::string &s, const std::string &l, std::string desc, std::shared_ptr< const Value > value, std::string arg_help)
int count (const std::string &o) const
const OptionDetails & operator[] (const std::string &option) const
void parse_positional (std::string option)
void parse_positional (std::vector< std::string > options)
std::string help (const std::vector< std::string > &groups={ "" }) const
std::vector< std::string > groups () const
const HelpGroupDetails & group_help (const std::string &group) const
Options (std::string program, std::string help_string="")
Options & positional_help (std::string help_text)
void parse (int &argc, char **&argv)
OptionAdder add_options (std::string group="")
void add_option (const std::string &group, const std::string &s, const std::string &l, std::string desc, std::shared_ptr< const Value > value, std::string arg_help)
int count (const std::string &o) const
const OptionDetails & operator[] (const std::string &option) const
void parse_positional (std::string option)
void parse_positional (std::vector< std::string > options)
std::string help (const std::vector< std::string > &groups={ "" }) const
std::vector< std::string > groups () const
const HelpGroupDetails & group_help (const std::string &group) const
Private Member Functions
void add_one_option (const std::string &option, std::shared_ptr< OptionDetails > details)
bool consume_positional (std::string a)
void add_to_option (const std::string &option, const std::string &arg)
String help_one_group (const std::string &group) const
void generate_group_help (String &result, const std::vector< std::string > &groups) const
void generate_all_groups_help (String &result) const
void add_one_option (const std::string &option, std::shared_ptr< OptionDetails > details)
bool consume_positional (std::string a)
void add_to_option (const std::string &option, const std::string &arg)
String help_one_group (const std::string &group) const
void generate_group_help (String &result, const std::vector< std::string > &groups) const
void generate_all_groups_help (String &result) const
Static Private Member Functions
static void parse_option (std::shared_ptr< OptionDetails > value, const std::string &name, const std::string &arg="")
static void checked_parse_arg (int argc, char *argv[], int &current, std::shared_ptr< OptionDetails > value, const std::string &name)
static void parse_option (std::shared_ptr< OptionDetails > value, const std::string &name, const std::string &arg="")
static void checked_parse_arg (int argc, char *argv[], int &current, std::shared_ptr< OptionDetails > value, const std::string &name)
Private Attributes
std::string m_program
String m_help_string
std::string m_positional_help
std::map< std::string, std::shared_ptr< OptionDetails > > m_options
std::vector< std::string > m_positional
std::vector< std::string >::iterator m_next_positional
std::unordered_set< std::string > m_positional_set
std::map< std::string, HelpGroupDetails > m_help
Detailed Description
Definition at line 667 of file cxxopts.h.
Constructor & Destructor Documentation
Options() [1/2]
cxxopts::Options::Options (std::string program, std::string help_string = "") inline
Definition at line 671 of file cxxopts.h.
             : m_program(std::move(program))
             , m_help_string(toLocalString(std::move(help_string)))
             , m_positional_help("positional parameters")
             , m_next_positional(m_positional.end())
         {
         }
Options() [2/2]
cxxopts::Options::Options (std::string program, std::string help_string = "") inline
Definition at line 671 of file cxxopts.h.
             : m_program(std::move(program))
             , m_help_string(toLocalString(std::move(help_string)))
             , m_positional_help("positional parameters")
             , m_next_positional(m_positional.end())
         {
         }
Member Function Documentation
add_one_option() [1/2]
void cxxopts::Options::add_one_option (const std::string & option, std::shared_ptr< OptionDetails > details) inline private
Definition at line 1347 of file cxxopts.h.
Referenced by add_option(), and cxxopts::OptionAdder::OptionAdder().
     {
         auto in = m_options.emplace(option, details);
         if (!in.second)
         {
             throw option_exists_error(option);
         }
     }
add_one_option() [2/2]
void cxxopts::Options::add_one_option (const std::string & option, std::shared_ptr< OptionDetails > details) inline private
add_option() [1/2]
void cxxopts::Options::add_option (const std::string & group, const std::string & s, const std::string & l, std::string desc, std::shared_ptr< const Value > value, std::string arg_help) inline
add_option() [2/2]
void cxxopts::Options::add_option (const std::string & group, const std::string & s, const std::string & l, std::string desc, std::shared_ptr< const Value > value, std::string arg_help) inline
Definition at line 1312 of file cxxopts.h.
References add_one_option(), cxxopts::HelpOptionDetails::has_arg, cxxopts::toLocalString(), and cxxopts::value().
Referenced by cxxopts::OptionAdder::OptionAdder(), and parse().
     {
         auto stringDesc = toLocalString(std::move(desc));
         auto option = std::make_shared<OptionDetails>(stringDesc, value);
         if (s.size() > 0)
         {
             add_one_option(s, option);
         }
         if (l.size() > 0)
         {
             add_one_option(l, option);
         }
         //add the help details
         auto& options = m_help[group];
         options.options.emplace_back(HelpOptionDetails{ s, l, stringDesc,
             value->has_arg(),
             value->has_default(), value->get_default_value(),
             value->has_implicit(), value->get_implicit_value(),
             std::move(arg_help),
             value->is_container() });
     }
add_options() [1/2]
OptionAdder cxxopts::Options::add_options (std::string group = "") inline
Definition at line 981 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder(), bnssemulator::CommandLineHelper::parse(), and bnssassembler::CommandLineHelper::parse().
     {
         return OptionAdder(*this, std::move(group));
     }
add_options() [2/2]
OptionAdder cxxopts::Options::add_options (std::string group = "") inline
add_to_option() [1/2]
void cxxopts::Options::add_to_option (const std::string & option, const std::string & arg) inline private
add_to_option() [2/2]
void cxxopts::Options::add_to_option (const std::string & option, const std::string & arg) inline private
Definition at line 1091 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         auto iter = m_options.find(option);
         if (iter == m_options.end())
         {
             throw option_not_exists_exception(option);
         }
         parse_option(iter->second, option, arg);
     }
checked_parse_arg() [1/2]
void cxxopts::Options::checked_parse_arg (int argc, char * argv[], int & current, std::shared_ptr< OptionDetails > value, const std::string & name) inline static private
Definition at line 1057 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder(), and parse_option().
     {
         if (current + 1 >= argc)
         {
             if (value->value().has_implicit())
             {
                 parse_option(value, name, value->value().get_implicit_value());
             }
             else
             {
                 throw missing_argument_exception(name);
             }
         }
         else
         {
             if (argv[current + 1][0] == '-' && value->value().has_implicit())
             {
                 parse_option(value, name, value->value().get_implicit_value());
             }
             else
             {
                 parse_option(value, name, argv[current + 1]);
                 ++current;
             }
         }
     }
checked_parse_arg() [2/2]
static void cxxopts::Options::checked_parse_arg (int argc, char * argv[], int & current, std::shared_ptr< OptionDetails > value, const std::string & name) inline static private
consume_positional() [1/2]
bool cxxopts::Options::consume_positional (std::string a) inline private
consume_positional() [2/2]
bool cxxopts::Options::consume_positional (std::string a) inline private
Definition at line 1104 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         while (m_next_positional != m_positional.end())
         {
             auto iter = m_options.find(*m_next_positional);
             if (iter != m_options.end())
             {
                 if (!iter->second->value().is_container())
                 {
                     if (iter->second->count() == 0)
                     {
                         add_to_option(*m_next_positional, a);
                         ++m_next_positional;
                         return true;
                     }
                     else
                     {
                         ++m_next_positional;
                         continue;
                     }
                 }
                 else
                 {
                     add_to_option(*m_next_positional, a);
                     return true;
                 }
             }
             ++m_next_positional;
         }
         return false;
     }
count() [1/2]
int cxxopts::Options::count (const std::string & o) const inline
Definition at line 708 of file cxxopts.h.
Referenced by cxxopts::check_required(), cxxopts::OptionAdder::OptionAdder(), bnssassembler::CommandLineHelper::parse(), and bnssemulator::CommandLineHelper::parse().
         {
             auto iter = m_options.find(o);
             if (iter == m_options.end())
             {
                 return 0;
             }
             return iter->second->count();
         }
count() [2/2]
int cxxopts::Options::count (const std::string & o) const inline
Definition at line 708 of file cxxopts.h.
         {
             auto iter = m_options.find(o);
             if (iter == m_options.end())
             {
                 return 0;
             }
             return iter->second->count();
         }
generate_all_groups_help() [1/2]
void cxxopts::Options::generate_all_groups_help (String & result) const inline private
Definition at line 1453 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         std::vector<std::string> all_groups;
         all_groups.reserve(m_help.size());
         for (auto& group : m_help)
         {
             all_groups.push_back(group.first);
         }
         generate_group_help(result, all_groups);
     }
generate_all_groups_help() [2/2]
void cxxopts::Options::generate_all_groups_help (String & result) const inline private
generate_group_help() [1/2]
void cxxopts::Options::generate_group_help (String & result, const std::vector< std::string > & groups) const inline private
generate_group_help() [2/2]
void cxxopts::Options::generate_group_help (String & result, const std::vector< std::string > & groups) const inline private
Definition at line 1432 of file cxxopts.h.
References cxxopts::empty().
Referenced by help_one_group(), and cxxopts::OptionAdder::OptionAdder().
     {
         for (size_t i = 0; i != print_groups.size(); ++i)
         {
             const String& group_help_text = help_one_group(print_groups[i]);
             if (empty(group_help_text))
             {
                 continue;
             }
             result += group_help_text;
             if (i < print_groups.size() - 1)
             {
                 result += '\n';
             }
         }
     }
group_help() [1/2]
const HelpGroupDetails & cxxopts::Options::group_help (const std::string & group) const inline
Definition at line 1509 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         return m_help.at(group);
     }
group_help() [2/2]
const HelpGroupDetails& cxxopts::Options::group_help (const std::string & group) const inline
groups() [1/2]
std::vector< std::string > cxxopts::Options::groups () const inline
Definition at line 1491 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         std::vector<std::string> g;
         std::transform(
             m_help.begin(),
             m_help.end(),
             std::back_inserter(g),
             [](const std::map<std::string, HelpGroupDetails>::value_type& pair)
         {
             return pair.first;
         }
         );
         return g;
     }
groups() [2/2]
std::vector<std::string> cxxopts::Options::groups () const inline
help() [1/2]
std::string cxxopts::Options::help (const std::vector< std::string > & groups = { "" }) const inline
Definition at line 1467 of file cxxopts.h.
References cxxopts::toLocalString(), and cxxopts::toUTF8String().
Referenced by cxxopts::OptionAdder::OptionAdder(), bnssemulator::CommandLineHelper::parse(), and bnssassembler::CommandLineHelper::parse().
     {
         String result = m_help_string + "\nUsage:\n  " +
             toLocalString(m_program) + " [OPTION...]";
         if (m_positional.size() > 0) {
             result += " " + toLocalString(m_positional_help);
         }
         result += "\n\n";
         if (help_groups.size() == 0)
         {
             generate_all_groups_help(result);
         }
         else
         {
             generate_group_help(result, help_groups);
         }
         return toUTF8String(result);
     }
help() [2/2]
std::string cxxopts::Options::help (const std::vector< std::string > & groups = { "" }) const inline
help_one_group() [1/2]
String cxxopts::Options::help_one_group (const std::string & group) const inline private
help_one_group() [2/2]
String cxxopts::Options::help_one_group (const std::string & group) const inline private
Definition at line 1361 of file cxxopts.h.
References cxxopts::anonymous_namespace{cxxopts.h}::format_description(), cxxopts::anonymous_namespace{cxxopts.h}::format_option(), generate_group_help(), cxxopts::anonymous_namespace{cxxopts.h}::OPTION_DESC_GAP, cxxopts::stringLength(), and cxxopts::toLocalString().
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         typedef std::vector<std::pair<String, String>> OptionHelp;
         auto group = m_help.find(g);
         if (group == m_help.end())
         {
             return "";
         }
         OptionHelp format;
         size_t longest = 0;
         String result;
         if (!g.empty())
         {
             result += toLocalString(" " + g + " options:\n");
         }
         for (const auto& o : group->second.options)
         {
             if (o.is_container && m_positional_set.find(o.l) != m_positional_set.end())
             {
                 continue;
             }
             auto s = format_option(o);
             longest = std::max(longest, stringLength(s));
             format.push_back(std::make_pair(s, String()));
         }
         longest = std::min(longest, static_cast<size_t>(OPTION_LONGEST));
         //widest allowed description
         auto allowed = size_t{ 76 } -longest - OPTION_DESC_GAP;
         auto fiter = format.begin();
         for (const auto& o : group->second.options)
         {
             if (o.is_container && m_positional_set.find(o.l) != m_positional_set.end())
             {
                 continue;
             }
             auto d = format_description(o, longest + OPTION_DESC_GAP, allowed);
             result += fiter->first;
             if (stringLength(fiter->first) > longest)
             {
                 result += '\n';
                 result += toLocalString(std::string(longest + OPTION_DESC_GAP, ' '));
             }
             else
             {
                 result += toLocalString(std::string(longest + OPTION_DESC_GAP -
                     stringLength(fiter->first),
                     ' '));
             }
             result += d;
             result += '\n';
             ++fiter;
         }
         return result;
     }
operator[]() [1/2]
const OptionDetails& cxxopts::Options::operator[] (const std::string & option) const inline
Definition at line 720 of file cxxopts.h.
References bnssassembler::name().
         {
             auto iter = m_options.find(option);
             if (iter == m_options.end())
             {
                 throw option_not_present_exception(option);
             }
             return *iter->second;
         }
operator[]() [2/2]
const OptionDetails& cxxopts::Options::operator[] (const std::string & option) const inline
Definition at line 720 of file cxxopts.h.
References bnssassembler::name().
         {
             auto iter = m_options.find(option);
             if (iter == m_options.end())
             {
                 throw option_not_present_exception(option);
             }
             return *iter->second;
         }
parse() [1/2]
void cxxopts::Options::parse (int & argc, char **& argv) inline
parse() [2/2]
void cxxopts::Options::parse (int & argc, char **& argv) inline
Definition at line 1153 of file cxxopts.h.
References add_option(), bnssassembler::name(), and cxxopts::anonymous_namespace{cxxopts.h}::option_matcher().
Referenced by cxxopts::OptionAdder::OptionAdder(), bnssemulator::CommandLineHelper::parse(), and bnssassembler::CommandLineHelper::parse().
     {
         int current = 1;
         int nextKeep = 1;
         bool consume_remaining = false;
         while (current != argc)
         {
             if (strcmp(argv[current], "--") == 0)
             {
                 consume_remaining = true;
                 ++current;
                 break;
             }
             std::match_results<const char*> result;
             std::regex_match(argv[current], result, option_matcher);
             if (result.empty())
             {
                 //not a flag
                 //if true is returned here then it was consumed, otherwise it is
                 //ignored
                 if (consume_positional(argv[current]))
                 {
                 }
                 else
                 {
                     argv[nextKeep] = argv[current];
                     ++nextKeep;
                 }
                 //if we return from here then it was parsed successfully, so continue
             }
             else
             {
                 //short or long option?
                 if (result[4].length() != 0)
                 {
                     const std::string& s = result[4];
                     for (std::size_t i = 0; i != s.size(); ++i)
                     {
                         std::string name(1, s[i]);
                         auto iter = m_options.find(name);
                         if (iter == m_options.end())
{
                             throw option_not_exists_exception(name);
                         }
                         auto value = iter->second;
                         //if no argument then just add it
                         if (!value->has_arg())
{
                             parse_option(value, name);
                         }
                         else
{
                             //it must be the last argument
                             if (i + 1 == s.size())
{
                                 checked_parse_arg(argc, argv, current, value, name);
                             }
                             else if (value->value().has_implicit())
{
                                 parse_option(value, name, value->value().get_implicit_value());
                             }
                             else
{
                                 //error
                                 throw option_requires_argument_exception(name);
                             }
                         }
                     }
                 }
                 else if (result[1].length() != 0)
                 {
                     const std::string& name = result[1];
                     auto iter = m_options.find(name);
                     if (iter == m_options.end())
                     {
                         throw option_not_exists_exception(name);
                     }
                     auto opt = iter->second;
                     //equals provided for long option?
                     if (result[3].length() != 0)
                     {
                         //parse the option given
                         //but if it doesn't take an argument, this is an error
                         if (!opt->has_arg())
{
                             throw option_not_has_argument_exception(name, result[3]);
                         }
                         parse_option(opt, name, result[3]);
                     }
                     else
                     {
                         if (opt->has_arg())
{
                             //parse the next argument
                             checked_parse_arg(argc, argv, current, opt, name);
                         }
                         else
{
                             //parse with empty argument
                             parse_option(opt, name);
                         }
                     }
                 }
             }
             ++current;
         }
         for (auto& opt : m_options)
         {
             auto& detail = opt.second;
             auto& value = detail->value();
             if (!detail->count() && value.has_default()) {
                 detail->parse_default();
             }
         }
         if (consume_remaining)
         {
             while (current < argc)
             {
                 if (!consume_positional(argv[current])) {
                     break;
                 }
                 ++current;
             }
             //adjust argv for any that couldn't be swallowed
             while (current != argc) {
                 argv[nextKeep] = argv[current];
                 ++nextKeep;
                 ++current;
             }
         }
         argc = nextKeep;
     }
parse_option() [1/2]
static void cxxopts::Options::parse_option (std::shared_ptr< OptionDetails > value, const std::string & name, const std::string & arg = "") inline static private
parse_option() [2/2]
void cxxopts::Options::parse_option (std::shared_ptr< OptionDetails > value, const std::string & name, const std::string & arg = "") inline static private
Definition at line 1046 of file cxxopts.h.
References checked_parse_arg().
Referenced by cxxopts::OptionAdder::operator()(), and cxxopts::OptionAdder::OptionAdder().
     {
         value->parse(arg);
     }
parse_positional() [1/4]
void cxxopts::Options::parse_positional (std::string option) inline
Definition at line 1138 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         parse_positional(std::vector<std::string>{option});
     }
parse_positional() [2/4]
void cxxopts::Options::parse_positional (std::string option) inline
parse_positional() [3/4]
void cxxopts::Options::parse_positional (std::vector< std::string > options) inline
parse_positional() [4/4]
void cxxopts::Options::parse_positional (std::vector< std::string > options) inline
Definition at line 1144 of file cxxopts.h.
     {
         m_positional = std::move(options);
         m_next_positional = m_positional.begin();
         m_positional_set.insert(m_positional.begin(), m_positional.end());
     }
positional_help() [1/2]
Options& cxxopts::Options::positional_help (std::string help_text) inline
Definition at line 681 of file cxxopts.h.
References cxxopts::value().
         {
             m_positional_help = std::move(help_text);
             return *this;
         }
positional_help() [2/2]
Options& cxxopts::Options::positional_help (std::string help_text) inline
Definition at line 681 of file cxxopts.h.
References cxxopts::value().
         {
             m_positional_help = std::move(help_text);
             return *this;
         }
Member Data Documentation
m_help
std::map< std::string, HelpGroupDetails > cxxopts::Options::m_help private
Definition at line 817 of file cxxopts.h.
m_help_string
String cxxopts::Options::m_help_string private
Definition at line 808 of file cxxopts.h.
m_next_positional
std::vector< std::string >::iterator cxxopts::Options::m_next_positional private
Definition at line 813 of file cxxopts.h.
m_options
std::map< std::string, std::shared_ptr< OptionDetails > > cxxopts::Options::m_options private
Definition at line 811 of file cxxopts.h.
m_positional
std::vector< std::string > cxxopts::Options::m_positional private
Definition at line 812 of file cxxopts.h.
m_positional_help
std::string cxxopts::Options::m_positional_help private
Definition at line 809 of file cxxopts.h.
m_positional_set
std::unordered_set< std::string > cxxopts::Options::m_positional_set private
Definition at line 814 of file cxxopts.h.
m_program
std::string cxxopts::Options::m_program private
Definition at line 807 of file cxxopts.h.
The documentation for this class was generated from the following file:
Code/Assembler/Include/cxxopts.h