AssemblerEmulator - Nikola Bebic: bnssassembler::DataDefinitionToken Class Reference
bnssassembler::DataDefinitionToken Class Reference
Class representing the data definition token.
#include <DataDefinitionToken.h>
Public Member Functions
DataDefinitionToken (std::vector< Data > data, size_t line_number, std::string line) noexcept
Constructs a DataDefinitionToken object.
void resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves symbol definitions in a token.
void firstPass (FirstPassData &data) const override
Executes the first pass over the token.
void secondPass (SecondPassData &data) const override
Executes the second pass over the token.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates relocation info.
Public Member Functions inherited from bnssassembler::Token
Token (size_t line_number, std::string line) noexcept
Constructs a token.
virtual bool usesAddress () const noexcept
Check whether the token can use the ORG address.
virtual void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept
Resolves the current PC symbol and sets the relocation info.
size_t lineNumber () const noexcept
Get the line number of the token.
std::string line () const noexcept
Get the line of the token.
virtual ~Token ()=default
Private Member Functions
size_t dataSize () const noexcept
Gets the size of the data defined with this token.
Private Attributes
std::vector< Data > data_
Detailed Description
Class representing the data definition token.
Definition at line 12 of file DataDefinitionToken.h.
Constructor & Destructor Documentation
DataDefinitionToken()
bnssassembler::DataDefinitionToken::DataDefinitionToken (std::vector< Data > data, size_t line_number, std::string line) noexcept
Constructs a DataDefinitionToken object.
Parameters
data Data that is defined
line_number Number of the line where data is defined
line Line where data is defined
Definition at line 8 of file DataDefinitionToken.cpp.
 : Token(line_number, line), data_(data) {}
Member Function Documentation
dataSize()
size_t bnssassembler::DataDefinitionToken::dataSize () const private noexcept
Gets the size of the data defined with this token.
Returns
Size of the data defined
Definition at line 77 of file DataDefinitionToken.cpp.
References data_, and bnssassembler::DataTypeParser::size().
Referenced by firstPass().
{
         size_t ret = 0;
         for (auto &data : data_) {
             ret += data.count().value() * DataTypeParser::size(data.type());
         }
         return ret;
     }
firstPass()
void bnssassembler::DataDefinitionToken::firstPass (FirstPassData & data) const override virtual
Executes the first pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 22 of file DataDefinitionToken.cpp.
References dataSize(), and bnssassembler::FirstPassData::incLocationCounter().
{
         data.incLocationCounter(dataSize());
     }
resolveImports()
void bnssassembler::DataDefinitionToken::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Token.
Definition at line 67 of file DataDefinitionToken.cpp.
References data_.
{
         for (auto &data: data_) {
             if (data.initialized()) {
                 data.value().resolveImports(imported_symbols);
             }
             data.count().resolveImports(imported_symbols);
         }
     }
resolveSymbolDefinitions()
void bnssassembler::DataDefinitionToken::resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves symbol definitions in a token.
Parameters
symbols Vector od symbol definitions that should be resolved
Reimplemented from bnssassembler::Token.
Definition at line 10 of file DataDefinitionToken.cpp.
{
         for (auto &symbol : symbols) {
             for (auto &data : data_) {
                 if (data.initialized()) {
                     data.value().setValue(symbol.name(), symbol.expression());
                 }
                 data.count().setValue(symbol.name(), symbol.expression());
             }
         }
     }
resolveSymbolTable()
void bnssassembler::DataDefinitionToken::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Token.
Definition at line 57 of file DataDefinitionToken.cpp.
References data_.
{
         for (auto &data: data_) {
             if (data.initialized()) {
                 data.value().resolveSymbolTable(symbol_table);
             }
             data.count().resolveSymbolTable(symbol_table);
         }
     }
secondPass()
void bnssassembler::DataDefinitionToken::secondPass (SecondPassData & data) const override virtual
Executes the second pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 26 of file DataDefinitionToken.cpp.
References bnssassembler::SecondPassData::addData(), bnssassembler::BSS, bnssassembler::BYTE, bnssassembler::SecondPassData::currentSectionType(), bnssassembler::DATA, data_, bnssassembler::DOUBLE_WORD, bnssassembler::RODATA, and bnssassembler::WORD.
{
         for (auto &data_definition : data_) {
             if (data_definition.initialized()) {
                 if (data.currentSectionType() != DATA && data.currentSectionType() != RODATA) {
                     throw MessageException("Initialized values can only exist in DATA and RODATA sections");
                 }
                 for (auto i = 0; i < data_definition.count().value(); i++) {
                     switch (data_definition.type()) {
                     case DOUBLE_WORD:
                         data.addData(static_cast<uint32_t>(data_definition.value().value()), data_definition.value().generateRelocations());
                         break;
                     case WORD:
                         data.addData(static_cast<uint16_t>(data_definition.value().value()), data_definition.value().generateRelocations());
                         break;
                     case BYTE:
                         data.addData(static_cast<uint8_t>(data_definition.value().value()), data_definition.value().generateRelocations());
                         break;
                     default:
                         throw MessageException("Data type not implemented");
                     }
                 }
             }
             else {
                 if (data.currentSectionType() != BSS) {
                     throw MessageException("Uninitialized values can only exist in the BSS section");
                 }
             }
         }
     }
Member Data Documentation
data_
std::vector<Data> bnssassembler::DataDefinitionToken::data_ private
Definition at line 28 of file DataDefinitionToken.h.
Referenced by dataSize(), resolveImports(), resolveSymbolTable(), and secondPass().
The documentation for this class was generated from the following files:
Code/Assembler/Include/DataDefinitionToken.h
Code/Assembler/Source/DataDefinitionToken.cpp