AssemblerEmulator - Nikola Bebic: bnssassembler::SectionTable Class Reference
bnssassembler::SectionTable Class Reference
Class representing the table of sections.
#include <SectionTable.h>
Public Member Functions
SectionTable & operator+= (const SectionData &data)
Insert new section into the table.
void nextSection () noexcept
Increasses the current section index.
SectionType currentSectionType () const noexcept
Gets the current section type.
void addData (uint8_t data, std::list< RelocationRecord > &relocations)
Adds 8 bits of data to the current section.
void addData (uint16_t data, std::list< RelocationRecord > &relocations)
Adds 16 bits of data to the current section.
void addData (uint32_t data, std::list< RelocationRecord > &relocations)
Adds 32 bits of data to the current section.
SectionData & current () noexcept
Gets the current section.
const SectionData & current () const noexcept
Gets the current section.
size_t currentIndex () const noexcept
Gets the index of current section.
Private Attributes
std::unordered_set< SectionData > set_
size_t current_index_ = static_cast<size_t>(-1)
Friends
std::ostream & operator<< (std::ostream &os, const SectionTable &section_table)
Writes the content of the object to a stream.
Detailed Description
Class representing the table of sections.
Definition at line 12 of file SectionTable.h.
Member Function Documentation
addData() [1/3]
void bnssassembler::SectionTable::addData (uint8_t data, std::list< RelocationRecord > & relocations)
Adds 8 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 29 of file SectionTable.cpp.
References current_index_.
Referenced by bnssassembler::SecondPassData::addData().
{
         (*this)[current_index_].addData(data, relocations);
     }
addData() [2/3]
void bnssassembler::SectionTable::addData (uint16_t data, std::list< RelocationRecord > & relocations)
Adds 16 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 33 of file SectionTable.cpp.
References current_index_.
{
         (*this)[current_index_].addData(data, relocations);
     }
addData() [3/3]
void bnssassembler::SectionTable::addData (uint32_t data, std::list< RelocationRecord > & relocations)
Adds 32 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 37 of file SectionTable.cpp.
References current_index_.
{
         (*this)[current_index_].addData(data, relocations);
     }
current() [1/2]
SectionData & bnssassembler::SectionTable::current () noexcept
Gets the current section.
Returns
Current section
Definition at line 41 of file SectionTable.cpp.
References current_index_.
Referenced by current(), bnssassembler::SecondPassData::currentSectionOffset(), and bnssassembler::SecondPassData::nextSection().
{
         return (*this)[current_index_];
     }
current() [2/2]
const SectionData & bnssassembler::SectionTable::current () const noexcept
Gets the current section.
Returns
Current section
Definition at line 45 of file SectionTable.cpp.
References current().
{
         return const_cast<SectionTable &>(*this).current();
     }
currentIndex()
size_t bnssassembler::SectionTable::currentIndex () const noexcept
Gets the index of current section.
Returns
Index of current section
Definition at line 49 of file SectionTable.cpp.
References current_index_.
Referenced by bnssassembler::SecondPassData::currentSectionIndex().
{
         return current_index_;
     }
currentSectionType()
SectionType bnssassembler::SectionTable::currentSectionType () const noexcept
Gets the current section type.
Returns
Current section type
Definition at line 25 of file SectionTable.cpp.
References current_index_.
Referenced by bnssassembler::SecondPassData::currentSectionType().
{
         return (*this)[current_index_].type();
     }
nextSection()
void bnssassembler::SectionTable::nextSection () noexcept
Increasses the current section index.
Definition at line 21 of file SectionTable.cpp.
References current_index_.
Referenced by bnssassembler::SecondPassData::nextSection().
{
         current_index_++;
     }
operator+=()
SectionTable & bnssassembler::SectionTable::operator+= (const SectionData & data)
Insert new section into the table.
Parameters
data Section data to be inserted
Returns
Reference to this section table after the insertion
Definition at line 10 of file SectionTable.cpp.
References bnssassembler::SectionData::index(), bnssassembler::SectionData::indexed(), set_, bnssassembler::SectionTypeParser::toString(), and bnssassembler::SectionData::type().
{
         if (set_.count(data) > 0) {
             auto section_string = "." + SectionTypeParser::toString(data.type()) + (data.indexed() ? "." + data.index() : "");
             throw MessageException("Section " + section_string + " already exists");
         }
         set_.insert(data);
         push_back(data);
         return *this;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SectionTable & section_table) friend
Writes the content of the object to a stream.
Parameters
os Stream where the content will be written
section_table Data that will be written
Definition at line 53 of file SectionTable.cpp.
{
         os << section_table.size() << std::endl;
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Section table:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 81) << LOWER_RIGHT << std::endl;
         for (auto &section : section_table) {
             os << section << std::endl;
         }
         std::cout << std::endl << std::endl;
         return os;
     }
Member Data Documentation
current_index_
size_t bnssassembler::SectionTable::current_index_ = static_cast<size_t>(-1) private
Definition at line 83 of file SectionTable.h.
Referenced by addData(), current(), currentIndex(), currentSectionType(), and nextSection().
set_
std::unordered_set<SectionData> bnssassembler::SectionTable::set_ private
Definition at line 82 of file SectionTable.h.
Referenced by operator+=().
The documentation for this class was generated from the following files:
Code/Assembler/Include/SectionTable.h
Code/Assembler/Source/SectionTable.cpp