AssemblerEmulator - Nikola Bebic: bnssassembler::SubtractOperation Class Reference
bnssassembler::SubtractOperation Class Reference
Class implementing the behaviour of the - operator in expressions.
#include <SubtractOperation.h>
Public Member Functions
bool containsSymbol () const noexcept override
Tests whether the expression contains a Symbol.
int symbolCount () const noexcept override
Counts the symbols in the expression.
std::list< RelocationRecord > generateRelocations () const override
Generates the relocation records for the subtree.
Public Member Functions inherited from bnssassembler::Operation
int32_t value () const override
Evaluates the expression.
bool setValue (std::string symbol, std::shared_ptr< Expression > value) noexcept override
Traverses the subtree and sets the value for the symbol.
void pushChildren (std::stack< std::reference_wrapper< std::shared_ptr< Expression >>> &stack) const noexcept override
Pushes the children to the stack.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and sets the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and sets the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
void left (std::shared_ptr< Expression > left) noexcept
Sets the left side of the operator.
void right (std::shared_ptr< Expression > right) noexcept
Sets the right side of the operator.
Public Member Functions inherited from bnssassembler::Expression
virtual bool validate () const noexcept
Validates the expression.
virtual ~Expression ()=default
Static Public Member Functions
static std::list< RelocationRecord > generateRelocations (std::list< RelocationRecord > left_list, std::list< RelocationRecord > right_list)
Protected Member Functions
int32_t calculate (int32_t lhs, int32_t rhs) const noexcept override
Calculates the value of the subexpression.
Protected Member Functions inherited from bnssassembler::Operation
std::shared_ptr< Expression > left () const noexcept
Gets the left side of the operator.
std::shared_ptr< Expression > right () const noexcept
Gets the right side of the operator.
Detailed Description
Class implementing the behaviour of the - operator in expressions.
Definition at line 12 of file SubtractOperation.h.
Member Function Documentation
calculate()
int32_t bnssassembler::SubtractOperation::calculate (int32_t lhs, int32_t rhs) const override protected virtual noexcept
Calculates the value of the subexpression.
Parameters
lhs Left side of the operator
rhs Right side of the operator
Returns
Result of the operation
Exceptions
Throws if the expression can not be evaluated (example: division by zero)
Implements bnssassembler::Operation.
Definition at line 125 of file SubtractOperation.cpp.
{
         return lhs - rhs;
     }
containsSymbol()
bool bnssassembler::SubtractOperation::containsSymbol () const override virtual noexcept
Tests whether the expression contains a Symbol.
Returns
Boolean value indicating whether the expression contains a Symbol
Reimplemented from bnssassembler::Operation.
Definition at line 6 of file SubtractOperation.cpp.
References bnssassembler::Operation::containsSymbol(), and symbolCount().
{
         if (Operation::containsSymbol()) {
             return symbolCount() == 0;
         }
         return false;
     }
generateRelocations() [1/2]
std::list< RelocationRecord > bnssassembler::SubtractOperation::generateRelocations () const override virtual
Generates the relocation records for the subtree.
Returns
Collection of relocation records
Reimplemented from bnssassembler::Operation.
Definition at line 68 of file SubtractOperation.cpp.
References bnssassembler::Operation::left(), and bnssassembler::Operation::right().
Referenced by bnssassembler::AddOperation::generateRelocations().
{
         auto left_list = left()->generateRelocations();
         auto right_list = right()->generateRelocations();
         return generateRelocations(left_list, right_list);
     }
generateRelocations() [2/2]
std::list< RelocationRecord > bnssassembler::SubtractOperation::generateRelocations (std::list< RelocationRecord > left_list, std::list< RelocationRecord > right_list) static
Definition at line 74 of file SubtractOperation.cpp.
References bnssassembler::exchange(), and bnssassembler::generateMaps().
{
         std::unordered_map<size_t, std::pair<RelocationRecord, size_t>> left_sections;
         std::unordered_map<size_t, std::pair<RelocationRecord, size_t>> right_sections;
         std::unordered_map<std::string, std::pair<RelocationRecord, size_t>> left_symbols;
         std::unordered_map<std::string, std::pair<RelocationRecord, size_t>> right_symbols;
         exchange(left_list, right_list);
         generateMaps(left_list, left_sections, left_symbols);
         generateMaps(right_list, right_sections, right_symbols);
         std::list<RelocationRecord> ret;
         for (auto &element : left_sections) {
             if (right_sections.count(element.first) < left_sections.count(element.first)) {
                 for (size_t i = 0; i < element.second.second - right_sections[element.first].second; i++) {
                     ret.push_back(element.second.first);
                 }
             }
         }
         for (auto &element : right_sections) {
             if (left_sections.count(element.first) < right_sections.count(element.first)) {
                 for (size_t i = 0; i < element.second.second - left_sections[element.first].second; i++) {
                     element.second.first.toggleOpposite();
                     ret.push_back(element.second.first);
                 }
             }
         }
         for (auto &element : left_symbols) {
             if (right_symbols.count(element.first) < left_symbols.count(element.first)) {
                 for (size_t i = 0; i < element.second.second - right_symbols[element.first].second; i++) {
                     ret.push_back(element.second.first);
                 }
             }
         }
         for (auto &element : right_symbols) {
             if (left_symbols.count(element.first) < right_symbols.count(element.first)) {
                 for (size_t i = 0; i < element.second.second - right_symbols[element.first].second; i++) {
                     element.second.first.toggleOpposite();
                     ret.push_back(element.second.first);
                 }
             }
         }
         return ret;
     }
symbolCount()
int bnssassembler::SubtractOperation::symbolCount () const override virtual noexcept
Counts the symbols in the expression.
Returns
Number of symbols in the expression
Reimplemented from bnssassembler::Operation.
Definition at line 14 of file SubtractOperation.cpp.
References bnssassembler::Operation::left(), and bnssassembler::Operation::right().
Referenced by containsSymbol().
{
         return left()->symbolCount() - right()->symbolCount();
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/SubtractOperation.h
Code/Assembler/Source/SubtractOperation.cpp