AssemblerEmulator - Nikola Bebic: bnssemulator::ConditionalJumpExecuter Class Reference
bnssemulator::ConditionalJumpExecuter Class Reference abstract
Base executer for conditional jump instructions.
#include <ConditionalJumpExecuter.h>
Public Member Functions
void execute (InstructionBitField instruction, Context &context) const override
Executes the instruction.
Public Member Functions inherited from bnssemulator::Executer
virtual ~Executer ()=default
Protected Member Functions
virtual bool test (bool negative, bool zero, bool overflow, bool carry) const noexcept=0
Tests whether the jump should happen.
Detailed Description
Base executer for conditional jump instructions.
Definition at line 10 of file ConditionalJumpExecuter.h.
Member Function Documentation
execute()
void bnssemulator::ConditionalJumpExecuter::execute (InstructionBitField instruction, Context & context) const override virtual
Executes the instruction.
Parameters
instruction Instruction
context Processor context
Implements bnssemulator::Executer.
Definition at line 5 of file ConditionalJumpExecuter.cpp.
References bnssemulator::Context::getOperandAddress(), bnssemulator::Context::getRegister(), bnssemulator::Context::jumpTo(), bnssemulator::InstructionBitField::register0, and test().
{
         auto address = context.getOperandAddress(instruction, 1);
         auto &reg = context.getRegister(instruction.register0);
         if (test(reg.negativeFlag(), reg.zeroFlag(), reg.overflowFlag(), reg.carryFlag())) {
             context.jumpTo(address);
         }
     }
test()
virtual bool bnssemulator::ConditionalJumpExecuter::test (bool negative, bool zero, bool overflow, bool carry) const protected pure virtual noexcept
Tests whether the jump should happen.
Parameters
negative Negative flag of the register
zero Zero flag of the register
overflow Overflow flag of the register
carry Carry flag of the register
Returns
Whether the jump should happen
Implemented in bnssemulator::JgezExecuter, bnssemulator::JgzExecuter, bnssemulator::JlezExecuter, bnssemulator::JlzExecuter, bnssemulator::JnzExecuter, and bnssemulator::JzExecuter.
Referenced by execute().
The documentation for this class was generated from the following files:
Code/Emulator/Include/ConditionalJumpExecuter.h
Code/Emulator/Source/ConditionalJumpExecuter.cpp