AssemblerEmulator - Nikola Bebic: bnssassembler::SymbolTable Class Reference
bnssassembler::SymbolTable Class Reference
Class representing the symbol table.
#include <SymbolTable.h>
Public Member Functions
SymbolTable & operator+= (const SymbolData &data)
Inserts a symbol into the table.
bool contains (std::string symbol) const noexcept
Check if the table contains a symbol.
void exportSymbol (std::string symbol) noexcept
Export a symbol.
Friends
std::ostream & operator<< (std::ostream &os, const SymbolTable &table)
Writes the content of the object to a stream.
Detailed Description
Class representing the symbol table.
Definition at line 11 of file SymbolTable.h.
Member Function Documentation
contains()
bool bnssassembler::SymbolTable::contains (std::string symbol) const noexcept
Check if the table contains a symbol.
Parameters
symbol Symbol to be checked
Returns
Whether the symbol exists in the table
Definition at line 14 of file SymbolTable.cpp.
Referenced by bnssassembler::SecondPassData::contains(), and bnssassembler::FirstPassData::insertSymbol().
{
         return count(symbol) > 0;
     }
exportSymbol()
void bnssassembler::SymbolTable::exportSymbol (std::string symbol) noexcept
Export a symbol.
Parameters
symbol Symbol to be exported
Definition at line 18 of file SymbolTable.cpp.
Referenced by bnssassembler::SecondPassData::exportSymbol().
{
         (*this)[symbol].exportSymbol();
     }
operator+=()
SymbolTable & bnssassembler::SymbolTable::operator+= (const SymbolData & data)
Inserts a symbol into the table.
Parameters
data Symbol to be inserted
Returns
Reference to this SymbolTable object after the insertion
Definition at line 9 of file SymbolTable.cpp.
References bnssassembler::SymbolData::name().
{
         insert(make_pair(data.name(), data));
         return *this;
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SymbolTable & table) friend
Writes the content of the object to a stream.
Parameters
os Stream where the content will be written
table Data that will be written
Definition at line 22 of file SymbolTable.cpp.
{
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Symbol table:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 47) << T_DOWN << multiple(HORIZONTAL, 9) << T_DOWN << multiple(HORIZONTAL, 8) << T_DOWN << multiple(HORIZONTAL, 14) << T_LEFT << std::endl;
         std::cout << VERTICAL << "                     Name                      " << VERTICAL << " Section " << VERTICAL << " Offset " << VERTICAL << " Global/Local " << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 47) << ALL_FOUR << multiple(HORIZONTAL, 9) << ALL_FOUR << multiple(HORIZONTAL, 8) << ALL_FOUR << multiple(HORIZONTAL, 14) << T_LEFT << std::endl;
         os << table.size() << std::endl;
         for (auto &entry : table) {
             os << entry.second << std::endl;
         }
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 47) << T_UP << multiple(HORIZONTAL, 9) << T_UP << multiple(HORIZONTAL, 8) << T_UP << multiple(HORIZONTAL, 14) << LOWER_RIGHT << std::endl;
         return os;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/SymbolTable.h
Code/Assembler/Source/SymbolTable.cpp