AssemblerEmulator - Nikola Bebic: bnssemulator::CommandLineHelper Class Reference
bnssemulator::CommandLineHelper Class Reference final
Utility class used for parsing the command line.
#include <CommandLineHelper.h>
Static Public Member Functions
static std::string parse (int argc, char *argv[])
Parses the command line.
Private Member Functions
CommandLineHelper ()=delete
CommandLineHelper (CommandLineHelper &)=delete
void operator= (CommandLineHelper &)=delete
Detailed Description
Utility class used for parsing the command line.
Definition at line 11 of file CommandLineHelper.h.
Constructor & Destructor Documentation
CommandLineHelper() [1/2]
bnssemulator::CommandLineHelper::CommandLineHelper () private delete
CommandLineHelper() [2/2]
bnssemulator::CommandLineHelper::CommandLineHelper (CommandLineHelper &) private delete
Member Function Documentation
operator=()
void bnssemulator::CommandLineHelper::operator= (CommandLineHelper &) private delete
parse()
std::string bnssemulator::CommandLineHelper::parse (int argc, char * argv[]) static
Parses the command line.
Parameters
argc Arguments count
argv Arguments vector
Returns
Input file name
Definition at line 7 of file CommandLineHelper.cpp.
References cxxopts::Options::add_options(), cxxopts::Options::count(), cxxopts::Options::help(), and cxxopts::Options::parse().
Referenced by main().
{
         cxxopts::Options options(argv[0], "Emulator\nSystem software\nSchool of Electrical Engineering\nUniversity of Belgrade\nCopyright (c) 2017 Nikola Bebic\n");
         options.add_options()
             ("i,input", "Specifies input file", cxxopts::value<std::string>()->default_value("out.out"))
             ("h,help", "Prints help");
         options.parse(argc, argv);
         if (options.count("help")) {
             std::cout << options.help() << std::endl;
             exit(0);
         }
         return options["input"].as<std::string>();
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/CommandLineHelper.h
Code/Emulator/Source/CommandLineHelper.cpp