AssemblerEmulator - Nikola Bebic: cxxopts::values::standard_value< T > Class Template Reference
cxxopts::values::standard_value< T > Class Template Reference
#include <cxxopts.h>
Public Member Functions
standard_value ()
standard_value (T *t)
void parse (const std::string &text) const override
bool is_container () const override
void parse () const override
bool has_arg () const override
bool has_default () const override
bool has_implicit () const override
std::shared_ptr< Value > default_value (const std::string &value) override
std::shared_ptr< Value > implicit_value (const std::string &value) override
std::string get_default_value () const override
std::string get_implicit_value () const override
const T & get () const
standard_value ()
standard_value (T *t)
void parse (const std::string &text) const override
bool is_container () const override
void parse () const override
bool has_arg () const override
bool has_default () const override
bool has_implicit () const override
std::shared_ptr< Value > default_value (const std::string &value) override
std::shared_ptr< Value > implicit_value (const std::string &value) override
std::string get_default_value () const override
std::string get_implicit_value () const override
const T & get () const
Public Member Functions inherited from cxxopts::Value
virtual ~Value ()=default
virtual ~Value ()=default
Protected Attributes
std::shared_ptr< T > m_result
T * m_store
bool m_default = false
std::string m_default_value
bool m_implicit = false
std::string m_implicit_value
Detailed Description
template<typename T>
class cxxopts::values::standard_value< T >
Definition at line 474 of file cxxopts.h.
Constructor & Destructor Documentation
standard_value() [1/4]
template<typename T > cxxopts::values::standard_value< T >::standard_value () inline
Definition at line 477 of file cxxopts.h.
                 : m_result(std::make_shared<T>())
                 , m_store(m_result.get())
             {
             }
standard_value() [2/4]
template<typename T > cxxopts::values::standard_value< T >::standard_value (T * t) inline explicit
Definition at line 483 of file cxxopts.h.
                 : m_store(t)
             {
             }
standard_value() [3/4]
template<typename T > cxxopts::values::standard_value< T >::standard_value () inline
Definition at line 477 of file cxxopts.h.
                 : m_result(std::make_shared<T>())
                 , m_store(m_result.get())
             {
             }
standard_value() [4/4]
template<typename T > cxxopts::values::standard_value< T >::standard_value (T * t) inline explicit
Definition at line 483 of file cxxopts.h.
                 : m_store(t)
             {
             }
Member Function Documentation
default_value() [1/2]
template<typename T > std::shared_ptr<Value> cxxopts::values::standard_value< T >::default_value (const std::string & value) inline override virtual
Implements cxxopts::Value.
Definition at line 519 of file cxxopts.h.
References cxxopts::value().
{
                 m_default = true;
                 m_default_value = value;
                 return shared_from_this();
             }
default_value() [2/2]
template<typename T > std::shared_ptr<Value> cxxopts::values::standard_value< T >::default_value (const std::string & value) inline override virtual
Implements cxxopts::Value.
Definition at line 519 of file cxxopts.h.
References cxxopts::value().
{
                 m_default = true;
                 m_default_value = value;
                 return shared_from_this();
             }
get() [1/2]
template<typename T > const T& cxxopts::values::standard_value< T >::get () const inline
Definition at line 543 of file cxxopts.h.
Referenced by cxxopts::OptionDetails::as().
             {
                 if (m_store == nullptr)
                 {
                     return *m_result;
                 }
                 else
                 {
                     return *m_store;
                 }
             }
get() [2/2]
template<typename T > const T& cxxopts::values::standard_value< T >::get () const inline
Definition at line 543 of file cxxopts.h.
References cxxopts::value().
             {
                 if (m_store == nullptr)
                 {
                     return *m_result;
                 }
                 else
                 {
                     return *m_store;
                 }
             }
get_default_value() [1/2]
template<typename T > std::string cxxopts::values::standard_value< T >::get_default_value () const inline override virtual
Implements cxxopts::Value.
Definition at line 533 of file cxxopts.h.
{
                 return m_default_value;
             }
get_default_value() [2/2]
template<typename T > std::string cxxopts::values::standard_value< T >::get_default_value () const inline override virtual
Implements cxxopts::Value.
Definition at line 533 of file cxxopts.h.
{
                 return m_default_value;
             }
get_implicit_value() [1/2]
template<typename T > std::string cxxopts::values::standard_value< T >::get_implicit_value () const inline override virtual
Implements cxxopts::Value.
Definition at line 538 of file cxxopts.h.
{
                 return m_implicit_value;
             }
get_implicit_value() [2/2]
template<typename T > std::string cxxopts::values::standard_value< T >::get_implicit_value () const inline override virtual
Implements cxxopts::Value.
Definition at line 538 of file cxxopts.h.
{
                 return m_implicit_value;
             }
has_arg() [1/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_arg () const inline override virtual
Implements cxxopts::Value.
Definition at line 504 of file cxxopts.h.
{
                 return value_has_arg<T>::value;
             }
has_arg() [2/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_arg () const inline override virtual
Implements cxxopts::Value.
Definition at line 504 of file cxxopts.h.
{
                 return value_has_arg<T>::value;
             }
has_default() [1/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_default () const inline override virtual
Implements cxxopts::Value.
Definition at line 509 of file cxxopts.h.
{
                 return m_default;
             }
has_default() [2/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_default () const inline override virtual
Implements cxxopts::Value.
Definition at line 509 of file cxxopts.h.
{
                 return m_default;
             }
has_implicit() [1/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_implicit () const inline override virtual
Implements cxxopts::Value.
Definition at line 514 of file cxxopts.h.
{
                 return m_implicit;
             }
has_implicit() [2/2]
template<typename T > bool cxxopts::values::standard_value< T >::has_implicit () const inline override virtual
Implements cxxopts::Value.
Definition at line 514 of file cxxopts.h.
{
                 return m_implicit;
             }
implicit_value() [1/2]
template<typename T > std::shared_ptr<Value> cxxopts::values::standard_value< T >::implicit_value (const std::string & value) inline override virtual
Implements cxxopts::Value.
Definition at line 526 of file cxxopts.h.
References cxxopts::value().
{
                 m_implicit = true;
                 m_implicit_value = value;
                 return shared_from_this();
             }
implicit_value() [2/2]
template<typename T > std::shared_ptr<Value> cxxopts::values::standard_value< T >::implicit_value (const std::string & value) inline override virtual
Implements cxxopts::Value.
Definition at line 526 of file cxxopts.h.
References cxxopts::value().
{
                 m_implicit = true;
                 m_implicit_value = value;
                 return shared_from_this();
             }
is_container() [1/2]
template<typename T > bool cxxopts::values::standard_value< T >::is_container () const inline override virtual
Implements cxxopts::Value.
Definition at line 494 of file cxxopts.h.
{
                 return type_is_container<T>::value;
             }
is_container() [2/2]
template<typename T > bool cxxopts::values::standard_value< T >::is_container () const inline override virtual
Implements cxxopts::Value.
Definition at line 494 of file cxxopts.h.
{
                 return type_is_container<T>::value;
             }
parse() [1/4]
template<typename T > void cxxopts::values::standard_value< T >::parse (const std::string & text) const inline override virtual
Implements cxxopts::Value.
Definition at line 489 of file cxxopts.h.
References cxxopts::values::parse_value().
{
                 parse_value(text, *m_store);
             }
parse() [2/4]
template<typename T > void cxxopts::values::standard_value< T >::parse (const std::string & text) const inline override virtual
Implements cxxopts::Value.
Definition at line 489 of file cxxopts.h.
References cxxopts::values::parse_value().
{
                 parse_value(text, *m_store);
             }
parse() [3/4]
template<typename T > void cxxopts::values::standard_value< T >::parse () const inline override virtual
Implements cxxopts::Value.
Definition at line 499 of file cxxopts.h.
References cxxopts::values::parse_value().
{
                 parse_value(m_default_value, *m_store);
             }
parse() [4/4]
template<typename T > void cxxopts::values::standard_value< T >::parse () const inline override virtual
Implements cxxopts::Value.
Definition at line 499 of file cxxopts.h.
References cxxopts::values::parse_value().
{
                 parse_value(m_default_value, *m_store);
             }
Member Data Documentation
m_default
template<typename T > bool cxxopts::values::standard_value< T >::m_default = false protected
Definition at line 558 of file cxxopts.h.
m_default_value
template<typename T > std::string cxxopts::values::standard_value< T >::m_default_value protected
Definition at line 559 of file cxxopts.h.
m_implicit
template<typename T > bool cxxopts::values::standard_value< T >::m_implicit = false protected
Definition at line 560 of file cxxopts.h.
m_implicit_value
template<typename T > std::string cxxopts::values::standard_value< T >::m_implicit_value protected
Definition at line 561 of file cxxopts.h.
m_result
template<typename T > std::shared_ptr< T > cxxopts::values::standard_value< T >::m_result protected
Definition at line 556 of file cxxopts.h.
m_store
template<typename T > T * cxxopts::values::standard_value< T >::m_store protected
Definition at line 557 of file cxxopts.h.
The documentation for this class was generated from the following file:
Code/Assembler/Include/cxxopts.h