AssemblerEmulator - Nikola Bebic: bnssassembler::RegisterIndirectOffsetParser Class Reference
bnssassembler::RegisterIndirectOffsetParser Class Reference
Class representing the parser for the register indirect operand with offset.
#include <RegisterIndirectOffsetParser.h>
Protected Member Functions
std::shared_ptr< Operand > parse (std::string str) const override
Parses one operand. Does not call the next parser if it fails.
Additional Inherited Members
Public Member Functions inherited from bnssassembler::OperandParser
std::shared_ptr< Operand > tryParse (std::string str) const
Tries to parse one operand. Calls the next parser in the chain if it fails.
void next (std::shared_ptr< OperandParser > next) noexcept
Sets the next parser in the chain.
virtual ~OperandParser ()=default
Detailed Description
Class representing the parser for the register indirect operand with offset.
Definition at line 10 of file RegisterIndirectOffsetParser.h.
Member Function Documentation
parse()
std::shared_ptr< Operand > bnssassembler::RegisterIndirectOffsetParser::parse (std::string str) const override protected virtual
Parses one operand. Does not call the next parser if it fails.
Parameters
str Operand which should be parsed
Returns
Pointer to the operand or nullptr, if the parser failed parsing
Exceptions
Throws if the parser fails but identifies the error
Implements bnssassembler::OperandParser.
Definition at line 29 of file RegisterIndirectOffsetParser.cpp.
References bnssassembler::ExpressionBuilder::build(), bnssassembler::RegisterParser::parse(), and bnssassembler::parsePcrel().
{
         static std::regex regex("[[:space:]]*\\[[[:space:]]*([A-Za-z0-9]*)[[:space:]]*(.*)\\][[:space:]]*");
         if (!regex_match(str, regex)) {
             return parsePcrel(str);
         }
         auto reg_str = regex_replace(str, regex, "$1");
         auto off_str = "0" + regex_replace(str, regex, "$2");
         // This would be register indirect without offset
         if (off_str == "0") {
             return nullptr;
         }
         auto reg = RegisterParser::parse(reg_str);
         auto off = ExpressionBuilder::build(off_str);
         return std::make_shared<RegisterIndirectOffset>(reg, off, false);
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/RegisterIndirectOffsetParser.h
Code/Assembler/Source/RegisterIndirectOffsetParser.cpp