AssemblerEmulator - Nikola Bebic: bnssassembler::FileReader Class Reference
bnssassembler::FileReader Class Reference final
Utility class providing methods for reading the file.
#include <FileReader.h>
Static Public Member Functions
static std::vector< std::string > readAllLines (std::string filename)
Reads all lines of the file.
Private Member Functions
FileReader ()=delete
FileReader (FileReader &)=delete
void operator= (FileReader &)=delete
Detailed Description
Utility class providing methods for reading the file.
Definition at line 11 of file FileReader.h.
Constructor & Destructor Documentation
FileReader() [1/2]
bnssassembler::FileReader::FileReader () private delete
FileReader() [2/2]
bnssassembler::FileReader::FileReader (FileReader &) private delete
Member Function Documentation
operator=()
void bnssassembler::FileReader::operator= (FileReader &) private delete
readAllLines()
std::vector< std::string > bnssassembler::FileReader::readAllLines (std::string filename) static
Reads all lines of the file.
Parameters
filename Name of the file
Returns
All lines of the file
Exceptions
Throws if the file does not exist or could not be opened for reading
Definition at line 6 of file FileReader.cpp.
References bnssassembler::StringHelper::fileToString(), and bnssassembler::StringHelper::split().
Referenced by main().
{
         auto raw_file = StringHelper::fileToString(filename);
         return StringHelper::split(raw_file, "\n");
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/FileReader.h
Code/Assembler/Source/FileReader.cpp