AssemblerEmulator - Nikola Bebic: bnssassembler::OperationToken Class Reference
bnssassembler::OperationToken Class Reference abstract
Token class representing a math operator.
#include <OperationToken.h>
Public Member Functions
void process (std::list< std::shared_ptr< ExpressionToken >> &output, std::stack< std::shared_ptr< ExpressionToken >> &stack, int &expression_rank) const override
Processes the current token.
virtual std::string operation () const noexcept=0
Public Member Functions inherited from bnssassembler::ExpressionToken
virtual int inputPriority () const noexcept=0
Gets the input priority of the token.
virtual int stackPriority () const noexcept=0
Gets the stack priority of the token.
virtual int rank () const noexcept=0
Gets the rank of the token.
virtual std::shared_ptr< Expression > create () const =0
Creates an expression object out of the token.
virtual ~ExpressionToken ()=default
Protected Member Functions
virtual bool isClosingBrace () const noexcept
Checks if the operator is the closing brace (closing brace should not be on the stack)
Protected Member Functions inherited from bnssassembler::ExpressionToken
virtual std::shared_ptr< ExpressionToken > clone (std::string param) const =0
Clones the current object, using the string provided.
ExpressionToken ()=default
Detailed Description
Token class representing a math operator.
Definition at line 10 of file OperationToken.h.
Member Function Documentation
isClosingBrace()
bool bnssassembler::OperationToken::isClosingBrace () const protected virtual noexcept
Checks if the operator is the closing brace (closing brace should not be on the stack)
Returns
Whether the operator is the closing brace
Reimplemented in bnssassembler::ClosingBraceToken.
Definition at line 24 of file OperationToken.cpp.
Referenced by process().
{
         return false;
     }
operation()
virtual std::string bnssassembler::OperationToken::operation () const pure virtual noexcept
Implemented in bnssassembler::AddToken, bnssassembler::ClosingBraceToken, bnssassembler::DivideToken, bnssassembler::MultiplyToken, bnssassembler::OpeningBraceToken, and bnssassembler::SubtractToken.
process()
void bnssassembler::OperationToken::process (std::list< std::shared_ptr< ExpressionToken >> & output, std::stack< std::shared_ptr< ExpressionToken >> & stack, int & expression_rank) const override virtual
Processes the current token.
Parameters
output Output list of tokens
stack Helper stack of tokens
expression_rank Rank of the expression
Implements bnssassembler::ExpressionToken.
Definition at line 6 of file OperationToken.cpp.
References bnssassembler::ExpressionToken::clone(), bnssassembler::ExpressionToken::inputPriority(), isClosingBrace(), and bnssassembler::ExpressionBuilder::popToPostfix().
{
         while (!stack.empty() && stack.top()->stackPriority() >= inputPriority()) {
             ExpressionBuilder::popToPostfix(output, stack, expression_rank);
         }
         if (isClosingBrace()) {
             if (!stack.empty()) {
                 stack.pop();
             }
             else {
                 throw MessageException("The opening brace is missing");
             }
         }
         else {
             stack.push(clone("dummy"));
         }
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/OperationToken.h
Code/Assembler/Source/OperationToken.cpp