AssemblerEmulator - Nikola Bebic: bnssassembler::Operation Class Reference
bnssassembler::Operation Class Reference abstract
Class representing the mathematical operation with two operands.
#include <Operation.h>
Public Member Functions
int32_t value () const override
Evaluates the expression.
bool setValue (std::string symbol, std::shared_ptr< Expression > value) noexcept override
Traverses the subtree and sets the value for the symbol.
bool containsSymbol () const noexcept override
Tests whether the expression contains a Symbol.
int symbolCount () const noexcept override
Counts the symbols in the expression.
void pushChildren (std::stack< std::reference_wrapper< std::shared_ptr< Expression >>> &stack) const noexcept override
Pushes the children to the stack.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and sets the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and sets the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
std::list< RelocationRecord > generateRelocations () const override
Generates the relocation records for the subtree.
void left (std::shared_ptr< Expression > left) noexcept
Sets the left side of the operator.
void right (std::shared_ptr< Expression > right) noexcept
Sets the right side of the operator.
Public Member Functions inherited from bnssassembler::Expression
virtual bool validate () const noexcept
Validates the expression.
virtual ~Expression ()=default
Protected Member Functions
virtual int32_t calculate (int32_t lhs, int32_t rhs) const =0
Calculates the value of the subexpression.
std::shared_ptr< Expression > left () const noexcept
Gets the left side of the operator.
std::shared_ptr< Expression > right () const noexcept
Gets the right side of the operator.
Private Attributes
std::shared_ptr< Expression > left_
std::shared_ptr< Expression > right_
Detailed Description
Class representing the mathematical operation with two operands.
Definition at line 11 of file Operation.h.
Member Function Documentation
calculate()
virtual int32_t bnssassembler::Operation::calculate (int32_t lhs, int32_t rhs) const protected pure virtual
Calculates the value of the subexpression.
Parameters
lhs Left side of the operator
rhs Right side of the operator
Returns
Result of the operation
Exceptions
Throws if the expression can not be evaluated (example: division by zero)
Implemented in bnssassembler::SubtractOperation, bnssassembler::AddOperation, bnssassembler::DivideOperation, and bnssassembler::MultiplyOperation.
Referenced by value().
containsSymbol()
bool bnssassembler::Operation::containsSymbol () const override virtual noexcept
Tests whether the expression contains a Symbol.
Returns
Boolean value indicating whether the expression contains a Symbol
Reimplemented from bnssassembler::Expression.
Reimplemented in bnssassembler::SubtractOperation.
Definition at line 28 of file Operation.cpp.
References left_, and right_.
Referenced by bnssassembler::SubtractOperation::containsSymbol(), bnssassembler::DivideOperation::validate(), and bnssassembler::MultiplyOperation::validate().
{
         return left_->containsSymbol() || right_->containsSymbol();
     }
generateRelocations()
std::list< RelocationRecord > bnssassembler::Operation::generateRelocations () const override virtual
Generates the relocation records for the subtree.
Returns
Collection of relocation records
Reimplemented from bnssassembler::Expression.
Reimplemented in bnssassembler::SubtractOperation.
Definition at line 56 of file Operation.cpp.
References left(), left_, right(), and right_.
Referenced by bnssassembler::AddOperation::generateRelocations().
{
         auto left = left_->generateRelocations();
         auto right = right_->generateRelocations();
         left.splice(left.end(), move(right));
         return left;
     }
left() [1/2]
void bnssassembler::Operation::left (std::shared_ptr< Expression > left) noexcept
Sets the left side of the operator.
Parameters
left Pointer to the expression on the left side
Definition at line 12 of file Operation.cpp.
References left(), and left_.
{
         left_ = left;
     }
left() [2/2]
std::shared_ptr< Expression > bnssassembler::Operation::left () const protected noexcept
Gets the left side of the operator.
Returns
Pointer to the expression on the right side
Definition at line 20 of file Operation.cpp.
References left_.
Referenced by bnssassembler::AddOperation::generateRelocations(), bnssassembler::SubtractOperation::generateRelocations(), generateRelocations(), left(), and bnssassembler::SubtractOperation::symbolCount().
{
         return left_;
     }
pushChildren()
void bnssassembler::Operation::pushChildren (std::stack< std::reference_wrapper< std::shared_ptr< Expression >>> & stack) const override virtual noexcept
Pushes the children to the stack.
Parameters
stack Reference to the stack
Reimplemented from bnssassembler::Expression.
Definition at line 36 of file Operation.cpp.
References left_, and right_.
{
         stack.push(const_cast<std::shared_ptr<Expression>&>(left_));
         stack.push(const_cast<std::shared_ptr<Expression>&>(right_));
     }
resolveCurrentPcSymbol()
void bnssassembler::Operation::resolveCurrentPcSymbol (size_t section_index, size_t offset) override virtual noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Reimplemented from bnssassembler::Expression.
Definition at line 51 of file Operation.cpp.
References left_, and right_.
{
         left_->resolveCurrentPcSymbol(section_index, offset);
         right_->resolveCurrentPcSymbol(section_index, offset);
     }
resolveImports()
void bnssassembler::Operation::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and sets the relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Expression.
Definition at line 46 of file Operation.cpp.
References left_, and right_.
{
         left_->resolveImports(imported_symbols);
         right_->resolveImports(imported_symbols);
     }
resolveSymbolTable()
void bnssassembler::Operation::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and sets the relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Expression.
Definition at line 41 of file Operation.cpp.
References left_, and right_.
{
         left_->resolveSymbolTable(symbol_table);
         right_->resolveSymbolTable(symbol_table);
     }
right() [1/2]
void bnssassembler::Operation::right (std::shared_ptr< Expression > right) noexcept
Sets the right side of the operator.
Parameters
right Pointer to the expression on the right side
Definition at line 16 of file Operation.cpp.
References right(), and right_.
{
         right_ = right;
     }
right() [2/2]
std::shared_ptr< Expression > bnssassembler::Operation::right () const protected noexcept
Gets the right side of the operator.
Returns
Pointer to the expression on the right side
Definition at line 24 of file Operation.cpp.
References right_.
Referenced by bnssassembler::AddOperation::generateRelocations(), bnssassembler::SubtractOperation::generateRelocations(), generateRelocations(), right(), and bnssassembler::SubtractOperation::symbolCount().
{
         return right_;
     }
setValue()
bool bnssassembler::Operation::setValue (std::string symbol, std::shared_ptr< Expression > value) override virtual noexcept
Traverses the subtree and sets the value for the symbol.
Parameters
symbol Name of the symbol
value New value of the symbol
Returns
Whether the symbol was found and the value was set
Reimplemented from bnssassembler::Expression.
Definition at line 8 of file Operation.cpp.
References left_, right_, and value().
{
         return left_->setValue(symbol, value) || right_->setValue(symbol, value);
     }
symbolCount()
int bnssassembler::Operation::symbolCount () const override virtual noexcept
Counts the symbols in the expression.
Returns
Number of symbols in the expression
Reimplemented from bnssassembler::Expression.
Reimplemented in bnssassembler::SubtractOperation.
Definition at line 32 of file Operation.cpp.
References left_, and right_.
{
         return left_->symbolCount() + right_->symbolCount();
     }
value()
int32_t bnssassembler::Operation::value () const override virtual
Evaluates the expression.
Exceptions
Throws if the expression has variables or could not be evaluated (for example, division by zero)
Implements bnssassembler::Expression.
Definition at line 4 of file Operation.cpp.
References calculate(), left_, and right_.
Referenced by setValue().
{
         return calculate(left_->value(), right_->value());
     }
Member Data Documentation
left_
std::shared_ptr<Expression> bnssassembler::Operation::left_ private
Definition at line 58 of file Operation.h.
Referenced by containsSymbol(), generateRelocations(), left(), pushChildren(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbolTable(), setValue(), symbolCount(), and value().
right_
std::shared_ptr<Expression> bnssassembler::Operation::right_ private
Definition at line 59 of file Operation.h.
Referenced by containsSymbol(), generateRelocations(), pushChildren(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbolTable(), right(), setValue(), symbolCount(), and value().
The documentation for this class was generated from the following files:
Code/Assembler/Include/Operation.h
Code/Assembler/Source/Operation.cpp