AssemblerEmulator - Nikola Bebic: bnssassembler::OrgDirectiveToken Class Reference
bnssassembler::OrgDirectiveToken Class Reference
Class representing the origin directive token.
#include <OrgDirectiveToken.h>
Public Member Functions
OrgDirectiveToken (MicroRiscExpression expression, size_t line_number, std::string line) noexcept
Constructs an OrgDirectiveToken object.
void resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves symbol definitions in a token.
void firstPass (FirstPassData &data) const override
Executes the first pass over the token.
void secondPass (SecondPassData &data) const override
Executes the second pass over the token.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates relocation info.
Public Member Functions inherited from bnssassembler::Token
Token (size_t line_number, std::string line) noexcept
Constructs a token.
virtual bool usesAddress () const noexcept
Check whether the token can use the ORG address.
virtual void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept
Resolves the current PC symbol and sets the relocation info.
size_t lineNumber () const noexcept
Get the line number of the token.
std::string line () const noexcept
Get the line of the token.
virtual ~Token ()=default
Private Attributes
MicroRiscExpression expression_
Detailed Description
Class representing the origin directive token.
Definition at line 11 of file OrgDirectiveToken.h.
Constructor & Destructor Documentation
OrgDirectiveToken()
bnssassembler::OrgDirectiveToken::OrgDirectiveToken (MicroRiscExpression expression, size_t line_number, std::string line) noexcept
Constructs an OrgDirectiveToken object.
Parameters
expression Expression of this origin directive
line_number Number of the line where this directive is located
line Line where this directive is located
Definition at line 7 of file OrgDirectiveToken.cpp.
 : Token(line_number, line), expression_(expression) {}
Member Function Documentation
firstPass()
void bnssassembler::OrgDirectiveToken::firstPass (FirstPassData & data) const override virtual
Executes the first pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 15 of file OrgDirectiveToken.cpp.
{
         // Do nothing
     }
resolveImports()
void bnssassembler::OrgDirectiveToken::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Token.
Definition at line 31 of file OrgDirectiveToken.cpp.
References expression_, and bnssassembler::MicroRiscExpression::resolveImports().
{
         expression_.resolveImports(imported_symbols);
     }
resolveSymbolDefinitions()
void bnssassembler::OrgDirectiveToken::resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves symbol definitions in a token.
Parameters
symbols Vector od symbol definitions that should be resolved
Reimplemented from bnssassembler::Token.
Definition at line 9 of file OrgDirectiveToken.cpp.
{
         for (auto &symbol : symbols) {
             expression_.setValue(symbol.name(), symbol.expression());
         }
     }
resolveSymbolTable()
void bnssassembler::OrgDirectiveToken::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Token.
Definition at line 27 of file OrgDirectiveToken.cpp.
References expression_, and bnssassembler::MicroRiscExpression::resolveSymbolTable().
{
         expression_.resolveSymbolTable(symbol_table);
     }
secondPass()
void bnssassembler::OrgDirectiveToken::secondPass (SecondPassData & data) const override virtual
Executes the second pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 19 of file OrgDirectiveToken.cpp.
References expression_, bnssassembler::MicroRiscExpression::generateRelocations(), bnssassembler::SecondPassData::org(), and bnssassembler::MicroRiscExpression::value().
{
         if (!expression_.generateRelocations().empty()) {
             throw MessageException("ORG directive expression can not have labels");
         }
         data.org(static_cast<uint32_t>(expression_.value()));
     }
Member Data Documentation
expression_
MicroRiscExpression bnssassembler::OrgDirectiveToken::expression_ private
Definition at line 27 of file OrgDirectiveToken.h.
Referenced by resolveImports(), resolveSymbolTable(), and secondPass().
The documentation for this class was generated from the following files:
Code/Assembler/Include/OrgDirectiveToken.h
Code/Assembler/Source/OrgDirectiveToken.cpp