AssemblerEmulator - Nikola Bebic: bnssassembler::DataTypeParser Class Reference
bnssassembler::DataTypeParser Class Reference final
Utility class used for parsing data types.
#include <DataTypeParser.h>
Classes
struct DataTypeParserStaticData
Static Public Member Functions
static DataType parse (std::string str)
Parses the datatype from string.
static size_t size (DataType data)
Returns the size of the data type in bytes.
Private Member Functions
DataTypeParser ()=delete
DataTypeParser (DataTypeParser &)=delete
void operator= (DataTypeParser &)=delete
Static Private Member Functions
static DataTypeParserStaticData & staticData () noexcept
Detailed Description
Utility class used for parsing data types.
Definition at line 11 of file DataTypeParser.h.
Constructor & Destructor Documentation
DataTypeParser() [1/2]
bnssassembler::DataTypeParser::DataTypeParser () private delete
DataTypeParser() [2/2]
bnssassembler::DataTypeParser::DataTypeParser (DataTypeParser &) private delete
Member Function Documentation
operator=()
void bnssassembler::DataTypeParser::operator= (DataTypeParser &) private delete
parse()
DataType bnssassembler::DataTypeParser::parse (std::string str) static
Parses the datatype from string.
Parameters
str String containing the data type
Returns
Parsed data type
Definition at line 8 of file DataTypeParser.cpp.
References bnssassembler::DataTypeParser::DataTypeParserStaticData::map, and staticData().
Referenced by bnssassembler::parseData().
{
         transform(str.begin(), str.end(), str.begin(), tolower);
         if (staticData().map.count(str) == 0) {
             throw InvalidDataTypeException(str);
         }
         return staticData().map[str];
     }
size()
size_t bnssassembler::DataTypeParser::size (DataType data) static
Returns the size of the data type in bytes.
Parameters
data DataType
Definition at line 18 of file DataTypeParser.cpp.
References bnssassembler::BYTE, bnssassembler::DOUBLE_WORD, and bnssassembler::WORD.
Referenced by bnssassembler::DataDefinitionToken::dataSize().
{
         switch (data) {
         case BYTE: return 1;
         case WORD: return 2;
         case DOUBLE_WORD: return 4;
         default: throw MessageException("DataType not yet implemented");
         }
     }
staticData()
DataTypeParser::DataTypeParserStaticData & bnssassembler::DataTypeParser::staticData () static private noexcept
Definition at line 33 of file DataTypeParser.cpp.
Referenced by parse().
{
         static DataTypeParserStaticData static_data;
         return static_data;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/DataTypeParser.h
Code/Assembler/Source/DataTypeParser.cpp