AssemblerEmulator - Nikola Bebic: bnssassembler::CommandLineHelper Class Reference
bnssassembler::CommandLineHelper Class Reference final
Utility class used to parse the command line.
#include <CommandLineHelper.h>
Static Public Member Functions
static std::pair< std::string, std::string > parse (int argc, char *argv[])
Parses the command line.
Private Member Functions
CommandLineHelper ()=delete
CommandLineHelper (CommandLineHelper &)=delete
void operator= (CommandLineHelper &)=delete
Detailed Description
Utility class used to parse the command line.
Definition at line 11 of file CommandLineHelper.h.
Constructor & Destructor Documentation
CommandLineHelper() [1/2]
bnssassembler::CommandLineHelper::CommandLineHelper () private delete
CommandLineHelper() [2/2]
bnssassembler::CommandLineHelper::CommandLineHelper (CommandLineHelper &) private delete
Member Function Documentation
operator=()
void bnssassembler::CommandLineHelper::operator= (CommandLineHelper &) private delete
parse()
std::pair< std::string, std::string > bnssassembler::CommandLineHelper::parse (int argc, char * argv[]) static
Parses the command line.
Parameters
argc Arguments count
argv Arguments vector
Returns
Pair of strings - input and output file names
Definition at line 7 of file CommandLineHelper.cpp.
References cxxopts::Options::add_options(), cxxopts::Options::count(), cxxopts::Options::help(), and cxxopts::Options::parse().
Referenced by main().
{
         cxxopts::Options options(argv[0], "Assembler\nSystem software\nSchool of Electrical Engineering\nUniversity of Belgrade\nCopyright (c) 2017 Nikola Bebic\n");
         options.add_options()
             ("i,input", "Specifies input file", cxxopts::value<std::string>()->default_value("in.ss"))
             ("o,output", "Specifies output file", cxxopts::value<std::string>()->default_value("out.out"))
             ("h,help", "Prints help");
         options.parse(argc, argv);
         if (options.count("help")) {
             std::cout << options.help() << std::endl;
             exit(0);
         }
         return make_pair(options["input"].as<std::string>(), options["output"].as<std::string>());
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/CommandLineHelper.h
Code/Assembler/Source/CommandLineHelper.cpp