AssemblerEmulator - Nikola Bebic: bnssemulator::KeyboardListener Class Reference
bnssemulator::KeyboardListener Class Reference final
Class representing the keyboard listener thread.
#include <KeyboardListener.h>
Static Public Member Functions
static void listen (Context *context)
Listens to keyboard interrupts and sets the context flag every time they fire.
Detailed Description
Class representing the keyboard listener thread.
Definition at line 10 of file KeyboardListener.h.
Member Function Documentation
listen()
void bnssemulator::KeyboardListener::listen (Context * context) static
Listens to keyboard interrupts and sets the context flag every time they fire.
Definition at line 6 of file KeyboardListener.cpp.
References consoleio::getCharacter(), consoleio::keyboardHit(), bnssemulator::Context::pressCharacter(), and bnssemulator::Context::programFinished().
Referenced by bnssemulator::Processor::executeProgram().
{
         while (!context->programFinished()) {
             while (!consoleio::keyboardHit()) {
                 if (context->programFinished()) {
                     return;
                 }
             }
             auto character = consoleio::getCharacter();
             context->pressCharacter(character);
         }
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/KeyboardListener.h
Code/Emulator/Source/KeyboardListener.cpp