AssemblerEmulator - Nikola Bebic: bnssassembler::MessageException Class Reference
bnssassembler::MessageException Class Reference
Represents an exception with a string message.
#include <MessageException.h>
Public Member Functions
MessageException (std::string message) noexcept
Constructs a MessageException object with the message.
std::string message () const noexcept
Gets the message of the exception.
const char * what () const noexcept override
Private Attributes
std::string message_
Detailed Description
Represents an exception with a string message.
Definition at line 11 of file MessageException.h.
Constructor & Destructor Documentation
MessageException()
bnssassembler::MessageException::MessageException (std::string message) explicit noexcept
Constructs a MessageException object with the message.
Parameters
message Message
Definition at line 5 of file MessageException.cpp.
 : message_(message) {}
Member Function Documentation
message()
std::string bnssassembler::MessageException::message () const noexcept
Gets the message of the exception.
Definition at line 7 of file MessageException.cpp.
References message_.
Referenced by bnssassembler::FirstPass::execute(), bnssassembler::SecondPass::execute(), and bnssassembler::Parser::parse().
{
         return message_;
     }
what()
const char * bnssassembler::MessageException::what () const override noexcept
Definition at line 11 of file MessageException.cpp.
References message_.
{
         return message_.c_str();
     }
Member Data Documentation
message_
std::string bnssassembler::MessageException::message_ private
Definition at line 25 of file MessageException.h.
Referenced by message(), and what().
The documentation for this class was generated from the following files:
Code/Assembler/Include/MessageException.h
Code/Assembler/Source/MessageException.cpp