AssemblerEmulator - Nikola Bebic: cxxopts::OptionAdder Class Reference
cxxopts::OptionAdder Class Reference
#include <cxxopts.h>
Public Member Functions
OptionAdder (Options &options, std::string group)
OptionAdder & operator() (const std::string &opts, const std::string &desc, std::shared_ptr< const Value > value=::cxxopts::value< bool >(), std::string arg_help="")
OptionAdder (Options &options, std::string group)
OptionAdder & operator() (const std::string &opts, const std::string &desc, std::shared_ptr< const Value > value=::cxxopts::value< bool >(), std::string arg_help="")
Private Attributes
Options & m_options
std::string m_group
Detailed Description
Definition at line 820 of file cxxopts.h.
Constructor & Destructor Documentation
OptionAdder() [1/2]
cxxopts::OptionAdder::OptionAdder (Options & options, std::string group) inline
Definition at line 824 of file cxxopts.h.
References cxxopts::value().
             : m_options(options), m_group(std::move(group))
         {
         }
OptionAdder() [2/2]
cxxopts::OptionAdder::OptionAdder (Options & options, std::string group) inline
Definition at line 824 of file cxxopts.h.
References cxxopts::Options::add_one_option(), cxxopts::Options::add_option(), cxxopts::Options::add_options(), cxxopts::Options::add_to_option(), cxxopts::HelpOptionDetails::arg_help, cxxopts::check_required(), cxxopts::Options::checked_parse_arg(), cxxopts::Options::consume_positional(), cxxopts::Options::count(), cxxopts::HelpOptionDetails::default_value, cxxopts::HelpOptionDetails::desc, cxxopts::empty(), cxxopts::anonymous_namespace{cxxopts.h}::format_description(), cxxopts::anonymous_namespace{cxxopts.h}::format_option(), cxxopts::Options::generate_all_groups_help(), cxxopts::Options::generate_group_help(), cxxopts::Options::group_help(), cxxopts::Options::groups(), cxxopts::HelpOptionDetails::has_arg, cxxopts::HelpOptionDetails::has_default, cxxopts::HelpOptionDetails::has_implicit, cxxopts::Options::help(), cxxopts::Options::help_one_group(), cxxopts::HelpOptionDetails::implicit_value, cxxopts::HelpOptionDetails::l, bnssassembler::name(), cxxopts::anonymous_namespace{cxxopts.h}::OPTION_DESC_GAP, cxxopts::anonymous_namespace{cxxopts.h}::OPTION_LONGEST, cxxopts::anonymous_namespace{cxxopts.h}::option_matcher(), cxxopts::anonymous_namespace{cxxopts.h}::option_specifier(), cxxopts::Options::parse(), cxxopts::Options::parse_option(), cxxopts::Options::parse_positional(), cxxopts::HelpOptionDetails::s, cxxopts::stringAppend(), cxxopts::stringLength(), cxxopts::toLocalString(), cxxopts::toUTF8String(), and cxxopts::value().
             : m_options(options), m_group(std::move(group))
         {
         }
Member Function Documentation
operator()() [1/2]
OptionAdder & cxxopts::OptionAdder::operator() (const std::string & opts, const std::string & desc, std::shared_ptr< const Value > value = ::cxxopts::value<bool>(), std::string arg_help = "") inline
Definition at line 988 of file cxxopts.h.
References cxxopts::anonymous_namespace{cxxopts.h}::option_specifier(), and cxxopts::Options::parse_option().
     {
         std::match_results<const char*> result;
         std::regex_match(opts.c_str(), result, option_specifier);
         if (result.empty())
         {
             throw invalid_option_format_error(opts);
         }
         const auto& short_match = result[2];
         const auto& long_match = result[3];
         if (!short_match.length() && !long_match.length())
         {
             throw invalid_option_format_error(opts);
         }
         else if (long_match.length() == 1 && short_match.length())
         {
             throw invalid_option_format_error(opts);
         }
         auto option_names = []
         (
             const std::sub_match<const char*>& short_,
             const std::sub_match<const char*>& long_
             )
         {
             if (long_.length() == 1)
             {
                 return std::make_tuple(long_.str(), short_.str());
             }
             else
             {
                 return std::make_tuple(short_.str(), long_.str());
             }
         }(short_match, long_match);
         m_options.add_option
         (
             m_group,
             std::get<0>(option_names),
             std::get<1>(option_names),
             desc,
             value,
             std::move(arg_help)
         );
         return *this;
     }
operator()() [2/2]
OptionAdder& cxxopts::OptionAdder::operator() (const std::string & opts, const std::string & desc, std::shared_ptr< const Value > value = ::cxxopts::value< bool >(), std::string arg_help = "") inline
Member Data Documentation
m_group
std::string cxxopts::OptionAdder::m_group private
Definition at line 842 of file cxxopts.h.
m_options
Options & cxxopts::OptionAdder::m_options private
Definition at line 841 of file cxxopts.h.
The documentation for this class was generated from the following file:
Code/Assembler/Include/cxxopts.h