AssemblerEmulator - Nikola Bebic: bnssemulator::StringHelper Class Reference
bnssemulator::StringHelper Class Reference final
Utility class providing helper methods for std::string class.
#include <StringHelper.h>
Static Public Member Functions
static std::string fileToString (std::string file_name)
Reads the whole file into a string.
static std::vector< std::string > split (std::string string, std::string delimiters) noexcept
Splits the string using the specified delimiters.
static std::string join (std::vector< std::string > strings, std::string delimiter) noexcept
Joins the strings from a vector using the specified delimiter.
template<typename Num >
static std::string numberFormat (Num number) noexcept
Converts the number to its string representation.
template<typename Num >
static std::string toHexString (Num number) noexcept
Converts the number to its hex string representation.
static std::string toHexString (unsigned char number) noexcept
Converts the number to its hex string representation.
static std::string toHexString (signed char number) noexcept
Converts the number to its hex string representation.
template<typename Num >
static Num parseNumber (std::string number)
Parses the number from its string representation.
static bool isAllWhiteSpace (const std::string &string) noexcept
Checks if the string contains only whitespace characters.
Private Member Functions
StringHelper ()=delete
StringHelper (StringHelper &)=delete
void operator= (StringHelper &)=delete
Detailed Description
Utility class providing helper methods for std::string class.
Definition at line 16 of file StringHelper.h.
Constructor & Destructor Documentation
StringHelper() [1/2]
bnssemulator::StringHelper::StringHelper () private delete
StringHelper() [2/2]
bnssemulator::StringHelper::StringHelper (StringHelper &) private delete
Member Function Documentation
fileToString()
std::string bnssemulator::StringHelper::fileToString (std::string file_name) static
Reads the whole file into a string.
Parameters
file_name Name of the file
Returns
String containing the content of the file
Exceptions
Throws if the file does not exist or could not be opened for reading
Definition at line 10 of file StringHelper.cpp.
Referenced by bnssemulator::FileReader::parse().
{
         std::ifstream file(file_name);
         if (!file.is_open()) {
             throw std::invalid_argument("File " + file_name + " does not exist");
         }
         std::stringstream ss;
         ss << file.rdbuf();
         auto ret = ss.str();
         file.close();
         return ret;
     }
isAllWhiteSpace()
bool bnssemulator::StringHelper::isAllWhiteSpace (const std::string & string) static noexcept
Checks if the string contains only whitespace characters.
Parameters
string String to be checked
Returns
Boolean value indicating whether the string contains only whitespace characters
Definition at line 72 of file StringHelper.cpp.
{
         for (auto &ch : string) {
             if (!isspace(ch)) return false;
         }
         return true;
     }
join()
std::string bnssemulator::StringHelper::join (std::vector< std::string > strings, std::string delimiter) static noexcept
Joins the strings from a vector using the specified delimiter.
Parameters
strings Vector of strings to be joined
delimiter Delimiter to be joined
Definition at line 41 of file StringHelper.cpp.
Referenced by bnssemulator::Context::Context().
{
         switch (strings.size())
         {
         case 0:
             return "";
         case 1:
             return strings[0];
         default:
             std::ostringstream os;
             copy(strings.begin(), strings.end() - 1, std::ostream_iterator<std::string>(os, delimiter.c_str()));
             os << *strings.rbegin();
             return os.str();
         }
     }
numberFormat()
template<typename Num > std::string bnssemulator::StringHelper::numberFormat (Num number) static noexcept
Converts the number to its string representation.
Template Parameters
Num Type of the number
Parameters
number Number to be converted
Returns
String representation of the number
Definition at line 97 of file StringHelper.h.
Referenced by bnssemulator::getRegisterIndex().
{
         return std::to_string(number);
     }
operator=()
void bnssemulator::StringHelper::operator= (StringHelper &) private delete
parseNumber()
template<typename Num > Num bnssemulator::StringHelper::parseNumber (std::string number) static
Parses the number from its string representation.
Template Parameters
Num Type of the number
Parameters
number String representation of the number to be parsed
Returns
Parsed number
Definition at line 111 of file StringHelper.h.
References bnssemulator::BINARY_REGEX, bnssemulator::CHARACTER_REGEX, bnssemulator::DECIMAL_REGEX, bnssemulator::HEX_REGEX, bnssemulator::OCT_REGEX, and bnssemulator::ZERO_REGEX.
{
         long long long_long;
         try {
             if (regex_match(number, ZERO_REGEX)) {
                 long_long = 0;
             }
             else if (regex_match(number, DECIMAL_REGEX)) {
                 long_long = stoll(number);
             }
             else if (regex_match(number, HEX_REGEX)) {
                 long_long = stoll(number.substr(2), nullptr, 16);
             }
             else if (regex_match(number, OCT_REGEX)) {
                 long_long = stoll(number, nullptr, 8);
             }
             else if (regex_match(number, BINARY_REGEX)) {
                 long_long = stoll(number.substr(2), nullptr, 2);
             }
             else if (regex_match(number, CHARACTER_REGEX)) {
                 long_long = static_cast<long long>(number[1]);
             }
             else {
                 throw MessageException("The number " + number + " could not be parsed");
             }
         }
         catch (std::invalid_argument&) {
             throw MessageException("The number " + number + " could not be parsed");
         }
         catch (std::out_of_range&) {
             throw MessageException("The number " + number + " is out of range");
         }
         auto ret = static_cast<Num>(long_long);
         if (ret != long_long) {
             throw MessageException("The number + " + number + " is out of range");
         }
         return ret;
     }
split()
std::vector< std::string > bnssemulator::StringHelper::split (std::string string, std::string delimiters) static noexcept
Splits the string using the specified delimiters.
Parameters
string String to be split
delimiters Delimiter characters in the string
Definition at line 23 of file StringHelper.cpp.
{
         std::vector<std::string> ret;
         std::string::size_type last_pos = 0;
         auto pos = string.find_first_of(delimiters, last_pos);
         while (std::string::npos != pos && std::string::npos != last_pos)
         {
             ret.push_back(string.substr(last_pos, pos - last_pos));
             last_pos = pos + 1;
             pos = string.find_first_of(delimiters, last_pos);
         }
         ret.push_back(string.substr(last_pos, pos - last_pos));
         return ret;
     }
toHexString() [1/3]
template<typename Num > std::string bnssemulator::StringHelper::toHexString (Num number) static noexcept
Converts the number to its hex string representation.
Template Parameters
Num Type of the number
Parameters
number Number to be converted
Returns
Hex string representation of the number
Definition at line 102 of file StringHelper.h.
Referenced by bnssemulator::StoreExecuter::execute(), bnssemulator::Processor::executeInstruction(), bnssemulator::fill(), bnssemulator::Segment::getInstruction(), bnssemulator::Context::getOperand(), bnssemulator::Context::getOperandAddress(), bnssemulator::Segment::getSecondWordOfInstruction(), bnssemulator::Segment::readData(), bnssemulator::Segment::relocate(), bnssemulator::AddressSpace::segment(), and bnssemulator::Segment::writeData().
{
         std::stringstream stream;
         stream << "0x"
             << std::setfill('0') << std::setw(sizeof(Num) * 2)
             << std::hex << number;
         return stream.str();
     }
toHexString() [2/3]
std::string bnssemulator::StringHelper::toHexString (unsigned char number) static noexcept
Converts the number to its hex string representation.
Template Parameters
Num Type of the number
Parameters
number Number to be converted
Returns
Hex string representation of the number
Definition at line 56 of file StringHelper.cpp.
{
         std::stringstream stream;
         stream << "0x"
             << std::setfill('0') << std::setw(2)
             << std::hex << static_cast<unsigned int>(number);
         return stream.str();
     }
toHexString() [3/3]
std::string bnssemulator::StringHelper::toHexString (signed char number) static noexcept
Converts the number to its hex string representation.
Template Parameters
Num Type of the number
Parameters
number Number to be converted
Returns
Hex string representation of the number
Definition at line 64 of file StringHelper.cpp.
{
         std::stringstream stream;
         stream << "0x"
             << std::setfill('0') << std::setw(2)
             << std::hex << static_cast<signed int>(number);
         return stream.str();
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/StringHelper.h
Code/Emulator/Source/StringHelper.cpp