AssemblerEmulator - Nikola Bebic: bnssassembler::ExpressionBuilder Class Reference
bnssassembler::ExpressionBuilder Class Reference final
Utility class used for building math expressions.
#include <ExpressionBuilder.h>
Static Public Member Functions
static MicroRiscExpression build (std::string infix_expression)
Builds one MicroRiscExpression object from the infix string.
static void popToPostfix (std::list< std::shared_ptr< ExpressionToken >> &output, std::stack< std::shared_ptr< ExpressionToken >> &stack, int &expression_rank)
Pops one item from the stack to the postfix output, and updates the rank.
Private Member Functions
ExpressionBuilder ()=delete
ExpressionBuilder (ExpressionBuilder &)=delete
void operator= (ExpressionBuilder &)=delete
Detailed Description
Utility class used for building math expressions.
Definition at line 12 of file ExpressionBuilder.h.
Constructor & Destructor Documentation
ExpressionBuilder() [1/2]
bnssassembler::ExpressionBuilder::ExpressionBuilder () private delete
ExpressionBuilder() [2/2]
bnssassembler::ExpressionBuilder::ExpressionBuilder (ExpressionBuilder &) private delete
Member Function Documentation
build()
MicroRiscExpression bnssassembler::ExpressionBuilder::build (std::string infix_expression) static
Builds one MicroRiscExpression object from the infix string.
Parameters
infix_expression Infix string
Definition at line 93 of file ExpressionBuilder.cpp.
References bnssassembler::infixToPostfix(), and bnssassembler::postfixToTree().
Referenced by bnssassembler::ImmediateParser::parse(), bnssassembler::SymbolDefinitionLineParser::parse(), bnssassembler::RegisterIndirectOffsetParser::parse(), bnssassembler::OrgDirectiveLineParser::parse(), bnssassembler::MemoryDirectParser::parse(), bnssassembler::parseData(), and bnssassembler::parsePcrel().
{
         auto postfix = infixToPostfix(infix_expression);
         auto tree = postfixToTree(postfix);
         return MicroRiscExpression(tree);
     }
operator=()
void bnssassembler::ExpressionBuilder::operator= (ExpressionBuilder &) private delete
popToPostfix()
void bnssassembler::ExpressionBuilder::popToPostfix (std::list< std::shared_ptr< ExpressionToken >> & output, std::stack< std::shared_ptr< ExpressionToken >> & stack, int & expression_rank) static
Pops one item from the stack to the postfix output, and updates the rank.
Parameters
output Postfix output
stack Postfix stack
expression_rank Postfix expression rank
Definition at line 99 of file ExpressionBuilder.cpp.
Referenced by bnssassembler::infixToPostfix(), and bnssassembler::OperationToken::process().
{
         if (stack.empty()) {
             throw MessageException("The opening brace is missing");
         }
         auto top = stack.top();
         stack.pop();
         output.push_back(top);
         expression_rank += top->rank();
         if (expression_rank < 1) {
             throw MessageException("The expression is invalid - too many operators");
         }
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/ExpressionBuilder.h
Code/Assembler/Source/ExpressionBuilder.cpp