AssemblerEmulator - Nikola Bebic: bnssassembler Namespace Reference
bnssassembler Namespace Reference
Classes
class AddOperation
Class implementing the behaviour of the + operator in expressions.
class AddToken
Token class representing the + operation.
class AluInstructionParser
Class representing the parser for ALU instructions.
class AssemblerException
Class representing the custom exception for the assembler.
class ClosingBraceToken
Token class representing the opening brace.
class CommandLineHelper
Utility class used to parse the command line.
class ConditionalJumpInstructionParser
Class representing the parser for conditional jump instructions.
class Data
Class representing the MicroRISC data.
class DataDefinitionLineParser
Class used for parsing data definitions.
class DataDefinitionToken
Class representing the data definition token.
class DataTypeParser
Utility class used for parsing data types.
class DivideOperation
Class implementing the behaviour of the / operator in expressions.
class DivideToken
Token class representing the / operation.
class DivisionByZeroException
Exception class representing division by zero.
class Expression
Class representing the math expression.
class ExpressionBuilder
Utility class used for building math expressions.
class ExpressionToken
Class representing the token found in infix and postfix expressions.
class ExpressionTokenFactory
Utility class used for creating the ExpressionToken objects.
class FileReader
Utility class providing methods for reading the file.
class FileWriter
Utility class used to write the assembler result to a file.
class FirstPass
Class representing the executor of the first pass.
class FirstPassData
Class representing the data that the two-pass assembler will modify in the first pass.
class FirstPassException
Represents an exception that happend during the assembler first pass.
class GlobalSymbolsLineParser
Class used for parsing information about global symbols.
class GlobalSymbolsToken
Class representing the global symbols token.
class Immediate
Class representing the immediate operand.
class ImmediateParser
Class representing the parser for the immediate operands.
class IncorrectLabelException
Exception representing the incorrect label.
struct InstructionBitField
Bit field that enables easier manipulation of instructions.
union InstructionBitFieldUnion
Union that enables easier manipulation of the instruction bit field.
class InstructionCodeParser
Utility class used for parsing instruction codes.
class InstructionLineParser
Class used for parsing instructions.
class InstructionParser
Abstract lass used for parsing one instruction.
class InstructionToken
Class representing the instruction in an assembler source file.
class InterruptInstructionParser
Class representing the parser for the interrupt instruction.
class InvalidDataDefinitionException
Exception representing invalid data definition.
class InvalidDataTypeException
Exception representing the invalid data type.
class InvalidExpressionException
Exception representing the invalid expression.
class LabelToken
Class representing the label token.
class LineParser
Chain of command abstract class used for parsing one line of file.
class Literal
Class representing the literal value.
class LiteralToken
Token class representing a math literal value.
class LoadInstructionParser
Class representing the load instruction parser.
class MemoryDirect
Class representing the memory direct operand.
class MemoryDirectParser
Class representing the parser for the memory direct operand.
class MessageException
Represents an exception with a string message.
class MicroRiscExpression
Adapter class for Expression.
class MicroRiscParser
Class representing the parser for the MicroRISC assembly.
class MultiplyOperation
Class implementing the behaviour of the * operator in expressions.
class MultiplyToken
Token class representing the * operation.
class NonExistingSymbolException
Exception representing the non existing symbol.
class NoOperandInstructionParser
Class representing the parser for the instruction without operands.
class NotInstructionParser
Class representing the parser for the not instruction.
class OpeningBraceToken
Token class representing the opening brace.
class Operand
Class representing one operand in an instruction.
class OperandParser
Chain of command class used to parse operands of the instructions.
class Operation
Class representing the mathematical operation with two operands.
class OperationToken
Token class representing a math operator.
class OrgDirectiveLineParser
Class representing a line parser for the origin directive.
class OrgDirectiveToken
Class representing the origin directive token.
class Parser
Abstract class representing a text parser.
class ParserException
Represents an exception that happend during the parsing of the file.
class RegisterDirect
Class representing the register direct operand.
class RegisterDirectParser
Class representing the parser for the register direct operand.
class RegisterIndirect
Class representing the register indirect operand.
class RegisterIndirectOffset
Class representing the register indirect operand with offset.
class RegisterIndirectOffsetParser
Class representing the parser for the register indirect operand with offset.
class RegisterIndirectParser
Class representing the parser for the register indirect operand.
class RegisterParser
Utility class used for parsing registers.
class RelocationRecord
Class representing one relocation record.
class SecondPass
Utility class executing the second pass.
class SecondPassData
Class representing the data that will be updated during the second pass.
class SecondPassException
Represents an exception that happened during the assembler second pass.
class SectionData
Class representing the data about one section.
class SectionStartLineParser
Class used for parsing section start definitions.
class SectionStartToken
Class representing the section start token.
class SectionTable
Class representing the table of sections.
class SectionTypeParser
Utility class representing the parser for the section types.
class StackInstructionParser
Class representing the parser for stack instructions.
class StoreInstructionParser
Class representing the parser for the store instruction.
class StringHelper
Utility class providing helper methods for std::string class.
class SubtractOperation
Class implementing the behaviour of the - operator in expressions.
class SubtractToken
Token class representing the - operation.
class Symbol
Class representing a symbol inside an expression.
class SymbolData
Class representing data about one symbol.
class SymbolDefinition
Class representing a symbol definition.
class SymbolDefinitionLineParser
Class used for parsing symbol definitions.
class SymbolDefinitionToken
Class representing the symbol definition token.
class SymbolTable
Class representing the symbol table.
class SymbolToken
Token class representing a math symbol.
class Token
Class representing one token of the assembler source file.
class UndonditionalJumpInstructionParser
Class representing the parser for the unconditional jump instructions.
Enumerations
enum AddressMode {
IMMEDIATE = 0b100, REGISTER_DIRECT = 0b000, MEMORY_DIRECT = 0b110, REGISTER_INDIRECT = 0b010,
REGISTER_INDIRECT_OFFSET = 0b111
}
Enum representing the address mode.
enum DataType { DOUBLE_WORD = 0, WORD, BYTE }
Enum representing a data type.
enum InstructionCode : int8_t {
INT = 0x00, JMP = 0x02, CALL = 0x03, RET = 0x01,
JZ = 0x04, JNZ = 0x05, JGZ = 0x06, JGEZ = 0x07,
JLZ = 0x08, JLEZ = 0x09, LOAD = 0x10, STORE = 0x11,
PUSH = 0x20, POP = 0x21, ADD = 0x30, SUB = 0x31,
MUL = 0x32, DIV = 0x33, MOD = 0x34, AND = 0x35,
OR = 0x36, XOR = 0x37, NOT = 0x38, ASL = 0x39,
ASR = 0x3A
}
Enum representing the instruction code.
enum OperandType : int8_t {
DEFAULT = 0b000, UNSIGNED_BYTE = 0b011, SIGNED_BYTE = 0b111, REGULAR_BYTE = 0b111,
UNSIGNED_WORD = 0b001, SIGNED_WORD = 0b101, REGULAR_WORD = 0b101, REGULAR_DOUBLE_WORD = 0b000
}
Enum representing the operand type.
enum Register {
R0 = 0x00, R1, R2, R3,
R4, R5, R6, R7,
R8, R9, R10, R11,
R12, R13, R14, R15,
SP = 0x10, PC = 0x11, NONE = 0x1F
}
Enum representing a register.
enum SectionType : int8_t { TEXT = 0, DATA, RODATA, BSS }
Enum representing the type of the section.
Functions
std::string multiple (unsigned char c, size_t times)
Returns a string containing multiple of the same characters.
std::string multiple (std::string s, size_t times)
Returns a string containing multiple of the same strings.
static void split (std::list< RelocationRecord > &original, std::list< RelocationRecord > &left, std::list< RelocationRecord > &right)
Data parseData (std::string str)
Parses the data from the string.
static void fixUnaryMinusStart (std::string &infix_expression, std::regex token_extractor)
Fixes the expression that starts with an unary minus sign.
static std::list< std::shared_ptr< ExpressionToken > > infixToPostfix (std::string infix_expression)
Builds a postfix expression from the infix string.
static std::shared_ptr< Expression > postfixToTree (const std::list< std::shared_ptr< ExpressionToken >> &postfix_expression)
Builds a tree from the postfix expression.
static void loadStoreFixup (std::string &instruction, OperandType &type)
Hack to fix the load and store instructions which can have various operands.
static void stripComment (std::string &line, std::vector< std::string > one_line_comment_delimiters)
Strips the comment from one line of the file.
static std::string extractLabel (std::string &line, std::vector< std::string > label_delimiters)
Extracts the label (if any) from the line.
std::shared_ptr< Operand > parsePcrel (std::string str)
Parses the input as a PC relative address.
std::ostream & operator<< (std::ostream &os, const RelocationRecord &record)
bool operator== (const RelocationRecord &lhs, const RelocationRecord &rhs)
bool operator!= (const RelocationRecord &lhs, const RelocationRecord &rhs)
std::ostream & operator<< (std::ostream &os, const SecondPassData &data)
bool operator== (const SectionData &lhs, const SectionData &rhs) noexcept
bool operator!= (const SectionData &lhs, const SectionData &rhs) noexcept
bool operator< (const SectionData &lhs, const SectionData &rhs) noexcept
bool operator> (const SectionData &lhs, const SectionData &rhs) noexcept
bool operator<= (const SectionData &lhs, const SectionData &rhs) noexcept
bool operator>= (const SectionData &lhs, const SectionData &rhs) noexcept
static std::string name (SectionType type, bool indexed, size_t index)
static void writeDescription (SectionType type, bool indexed, size_t index, bool org_valid, uint32_t org_address, size_t size)
std::ostream & operator<< (std::ostream &os, const SectionData &data)
std::ostream & operator<< (std::ostream &os, const SectionTable &section_table)
static void generateMaps (const std::list< RelocationRecord > &source, std::unordered_map< size_t, std::pair< RelocationRecord, size_t >> &sections, std::unordered_map< std::string, std::pair< RelocationRecord, size_t >> &symbols)
static void exchange (std::list< RelocationRecord > &left, std::list< RelocationRecord > &right)
std::ostream & operator<< (std::ostream &os, const SymbolData &data)
bool operator== (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
bool operator!= (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
bool operator< (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
bool operator> (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
bool operator<= (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
bool operator>= (const SymbolDefinition &lhs, const SymbolDefinition &rhs)
std::ostream & operator<< (std::ostream &os, const SymbolTable &table)
Variables
const std::string ZERO = "0"
const std::string DECIMAL = "[1-9][0-9]*"
const std::string HEX = "0x[0-9a-fA-F][0-9a-fA-F]*"
const std::string BINARY = "0b[01][01]*"
const std::string OCT = "0[0-7][0-7]*"
const std::string CHARACTER = "'[[:print:]]'"
const std::string LITERAL = "(" + ZERO + "|" + DECIMAL + "|" + HEX + "|" + BINARY + "|" + OCT + "|" + CHARACTER + ")"
const std::string OPERATOR = "[-+*/()]"
const std::string SYMBOL = "(([a-zA-Z_][a-zA-Z_0-9]*)|\\$)"
const std::string LABEL = SYMBOL
const std::string CONSTANT_TERM = "([[:space:]]*(" + LITERAL + "|" + OPERATOR + "|" + SYMBOL + ")[[:space:]]*)*"
const std::string ORG_DIRECTIVE = "[Oo][Rr][Gg]"
const std::string SYMBOL_DEFINITION = "[Dd][Ee][Ff]"
const std::string DUPLICATE_DIRECTIVE = "[Dd][Uu][Pp]"
const std::string GLOBAL_DIRECTIVE = "[.][Gg][Ll][Oo][Bb][Aa][Ll]"
const std::string COMMA_TOKENIZER = "[[:space:]]*(.*?)[[:space:]]*,(.*)"
const std::string LAST_COMMA_TOKEN = "[[:space:]]*(.*)[[:space:]]*"
const std::regex ZERO_REGEX = std::regex(ZERO)
const std::regex DECIMAL_REGEX = std::regex(DECIMAL)
const std::regex HEX_REGEX = std::regex(HEX)
const std::regex BINARY_REGEX = std::regex(BINARY)
const std::regex OCT_REGEX = std::regex(OCT)
const std::regex CHARACTER_REGEX = std::regex(CHARACTER)
const std::regex LITERAL_REGEX = std::regex(LITERAL)
const std::regex OPERATOR_REGEX = std::regex(OPERATOR)
const std::regex SYMBOL_REGEX = std::regex(SYMBOL)
const std::regex LABEL_REGEX = std::regex(LABEL)
const std::regex CONSTANT_TERM_REGEX = std::regex(CONSTANT_TERM)
const std::regex ORG_DIRECTIVE_REGEX = std::regex(ORG_DIRECTIVE)
const std::regex SYMBOL_DEFINITION_REGEX = std::regex(SYMBOL_DEFINITION)
const std::regex DUPLICATE_DIRECTIVE_REGEX = std::regex(DUPLICATE_DIRECTIVE)
const std::regex GLOBAL_DIRECTIVE_REGEX = std::regex(GLOBAL_DIRECTIVE)
const std::regex COMMA_TOKENIZER_REGEX = std::regex(COMMA_TOKENIZER)
const std::regex LAST_COMMA_TOKEN_REGEX = std::regex(LAST_COMMA_TOKEN)
const std::string UPPER_LEFT = "\u2554"
const std::string UPPER_RIGHT = "\u2557"
const std::string LOWER_LEFT = "\u255a"
const std::string LOWER_RIGHT = "\u255d"
const std::string HORIZONTAL = "\u2550"
const std::string VERTICAL = "\u2551"
const std::string T_LEFT = "\u2563"
const std::string T_RIGHT = "\u2560"
const std::string T_UP = "\u2569"
const std::string T_DOWN = "\u2566"
const std::string ALL_FOUR = "\u256c"
const size_t NUM_OF_REGISTERS = 16
Number of all purpose registers (excluding PC and SP)
Enumeration Type Documentation
AddressMode
enum bnssassembler::AddressMode
Enum representing the address mode.
Enumerator
IMMEDIATE
REGISTER_DIRECT
MEMORY_DIRECT
REGISTER_INDIRECT
REGISTER_INDIRECT_OFFSET
Definition at line 9 of file AddressMode.h.
                      {
         IMMEDIATE                   = 0b100,
         REGISTER_DIRECT             = 0b000,
         MEMORY_DIRECT               = 0b110,
         REGISTER_INDIRECT           = 0b010,
         REGISTER_INDIRECT_OFFSET    = 0b111
     };
DataType
enum bnssassembler::DataType
Enum representing a data type.
Enumerator
DOUBLE_WORD
32bit value
WORD
16bit value
BYTE
8bit value
Definition at line 9 of file DataType.h.
                   {
         DOUBLE_WORD = 0,
         WORD,
         BYTE
     };
InstructionCode
enum bnssassembler::InstructionCode : int8_t
Enum representing the instruction code.
Enumerator
INT
JMP
CALL
RET
JZ
JNZ
JGZ
JGEZ
JLZ
JLEZ
LOAD
STORE
PUSH
POP
ADD
SUB
MUL
DIV
MOD
AND
OR
XOR
NOT
ASL
ASR
Definition at line 12 of file InstructionCode.h.
                          : int8_t {
         INT   = 0x00,
         JMP   = 0x02,
         CALL  = 0x03,
         RET   = 0x01,
         JZ    = 0x04,
         JNZ   = 0x05,
         JGZ   = 0x06,
         JGEZ  = 0x07,
         JLZ   = 0x08,
         JLEZ  = 0x09,
         LOAD  = 0x10,
         STORE = 0x11,
         PUSH  = 0x20,
         POP   = 0x21,
         ADD   = 0x30,
         SUB   = 0x31,
         MUL   = 0x32,
         DIV   = 0x33,
         MOD   = 0x34,
         AND   = 0x35,
         OR    = 0x36,
         XOR   = 0x37,
         NOT   = 0x38,
         ASL   = 0x39,
         ASR   = 0x3A
     };
OperandType
enum bnssassembler::OperandType : int8_t
Enum representing the operand type.
Enumerator
DEFAULT
UNSIGNED_BYTE
SIGNED_BYTE
REGULAR_BYTE
UNSIGNED_WORD
SIGNED_WORD
REGULAR_WORD
REGULAR_DOUBLE_WORD
Definition at line 10 of file OperandType.h.
                      : int8_t {
         DEFAULT                 = 0b000,
         UNSIGNED_BYTE           = 0b011,
         SIGNED_BYTE             = 0b111,
         REGULAR_BYTE            = 0b111,
         UNSIGNED_WORD           = 0b001,
         SIGNED_WORD             = 0b101,
         REGULAR_WORD            = 0b101,
         REGULAR_DOUBLE_WORD     = 0b000
     };
Register
enum bnssassembler::Register
Enum representing a register.
Enumerator
R0
R1
R2
R3
R4
R5
R6
R7
R8
R9
R10
R11
R12
R13
R14
R15
SP
PC
NONE
Definition at line 16 of file Register.h.
                   {
         R0 = 0x00,
         R1,
         R2,
         R3,
         R4,
         R5,
         R6,
         R7,
         R8,
         R9,
         R10,
         R11,
         R12,
         R13,
         R14,
         R15,
         SP = 0x10,
         PC = 0x11,
         NONE = 0x1F
     };
SectionType
enum bnssassembler::SectionType : int8_t
Enum representing the type of the section.
Enumerator
TEXT
Text section
DATA
Data section
RODATA
Read-only data section
BSS
Block started by symbol section
Definition at line 11 of file SectionType.h.
                      : int8_t {
         TEXT = 0,
         DATA,
         RODATA,
         BSS
     };
Function Documentation
exchange()
static void bnssassembler::exchange (std::list< RelocationRecord > & left, std::list< RelocationRecord > & right) static
Definition at line 39 of file SubtractOperation.cpp.
Referenced by bnssassembler::SubtractOperation::generateRelocations().
{
         std::list<RelocationRecord> for_right;
         std::list<RelocationRecord> for_left;
         for (auto &element : left) {
             if (element.opposite()) {
                 for_right.push_back(element);
             }
         }
         for (auto &element : right) {
             if (element.opposite()) {
                 for_left.push_back(element);
             }
         }
         for (auto &element : for_right) {
             element.toggleOpposite();
             right.push_back(element);
             left.remove(element);
         }
         for (auto &element : for_left) {
             element.toggleOpposite();
             left.push_back(element);
             right.remove(element);
         }
     }
extractLabel()
static std::string bnssassembler::extractLabel (std::string & line, std::vector< std::string > label_delimiters) static
Extracts the label (if any) from the line.
Parameters
line Reference to the line. After this method does not contain the label
label_delimiters Strings that separate the label from the rest of the line
Definition at line 30 of file Parser.cpp.
References bnssassembler::StringHelper::join(), and LABEL.
Referenced by bnssassembler::Parser::parse().
{
         auto delimiters = StringHelper::join(label_delimiters, "|");
         static std::regex regex("[[:space:]]*(.*)[[:space:]]*(" + delimiters + ")[[:space:]]*(.*)[[:space:]]*");
         static std::regex characters_fix(".*'" + delimiters + "'.*");
         if (regex_match(line, regex) && !regex_match(line, characters_fix)) {
             static std::regex label_regex("[[:space:]]*(" + LABEL + ")[[:space:]]*");
             auto ret = regex_replace(line, regex, "$1");
             if (regex_match(ret, label_regex)) {
                 ret = regex_replace(ret, label_regex, "$1");
             }
             else {
                 throw IncorrectLabelException(ret);
             }
             line = regex_replace(line, regex, "$3");
             return ret;
         }
         return "";
     }
fixUnaryMinusStart()
static void bnssassembler::fixUnaryMinusStart (std::string & infix_expression, std::regex token_extractor) static
Fixes the expression that starts with an unary minus sign.
Parameters
infix_expression Reference to the expression that will be fixed
token_extractor Regex used to extract the first token from the string
Definition at line 16 of file ExpressionBuilder.cpp.
Referenced by infixToPostfix().
{
         if (regex_match(infix_expression, token_extractor)) {
             auto token_string = regex_replace(infix_expression, token_extractor, "$1");
             if (token_string == "-") {
                 infix_expression = "0 " + infix_expression;
             }
         }
     }
generateMaps()
static void bnssassembler::generateMaps (const std::list< RelocationRecord > & source, std::unordered_map< size_t, std::pair< RelocationRecord, size_t >> & sections, std::unordered_map< std::string, std::pair< RelocationRecord, size_t >> & symbols) static
Definition at line 18 of file SubtractOperation.cpp.
Referenced by bnssassembler::SubtractOperation::generateRelocations().
{
         for (auto &element : source) {
             if (element.section()) {
                 if (sections.count(element.sectionIndex()) > 0) {
                     sections[element.sectionIndex()].second++;
                 }
                 else {
                     sections[element.sectionIndex()] = std::make_pair(element, 1);
                 }
             }
             else {
                 if (symbols.count(element.symbolName()) > 0) {
                     symbols[element.symbolName()].second++;
                 }
                 else {
                     symbols[element.symbolName()] = std::make_pair(element, 1);
                 }
             }
         }
     }
infixToPostfix()
static std::list<std::shared_ptr<ExpressionToken> > bnssassembler::infixToPostfix (std::string infix_expression) static
Builds a postfix expression from the infix string.
Parameters
infix_expression Infix expression string
Returns
Postfix expression list of tokens
Definition at line 30 of file ExpressionBuilder.cpp.
References bnssassembler::ExpressionTokenFactory::create(), fixUnaryMinusStart(), LITERAL, OPERATOR, bnssassembler::ExpressionBuilder::popToPostfix(), and SYMBOL.
Referenced by bnssassembler::ExpressionBuilder::build().
{
         std::list<std::shared_ptr<ExpressionToken>> ret;
         std::stack<std::shared_ptr<ExpressionToken>> stack;
         auto rank = 0;
         static std::regex end_of_infix("[[:space:]]*");
         static std::regex token_extractor("[[:space:]]*(" + LITERAL + "|" + OPERATOR + "|" + SYMBOL + ")(.*)[[:space:]]*");
         fixUnaryMinusStart(infix_expression, token_extractor);
         while (true) {
             if (infix_expression.size() == 0 || regex_match(infix_expression, end_of_infix)) {
                 break;
             }
             if (!regex_match(infix_expression, token_extractor)) {
                 throw InvalidExpressionException();
             }
             auto token_string = regex_replace(infix_expression, token_extractor, "$1");
             infix_expression = regex_replace(infix_expression, token_extractor, "$5");
             auto token = ExpressionTokenFactory::create(token_string);
             token->process(ret, stack, rank);
         }
         while (!stack.empty()) {
             ExpressionBuilder::popToPostfix(ret, stack, rank);
         }
         if (rank != 1) {
             throw MessageException("Invalid expression - too many operands");
         }
         return ret;
     }
loadStoreFixup()
static void bnssassembler::loadStoreFixup (std::string & instruction, OperandType & type) static
Hack to fix the load and store instructions which can have various operands.
Parameters
instruction String that should be fixed
type Operand type of the instruction that should be set
Load and store instructions can have suffices UB, SB, UW, SW, B and W. Those are still the same instructions with the same instruction codes, but different operand types. This function fixes the string containing the instruction, making it look like it is a regular load or store, but sets the operand type to the specific type. If the instruction is not load or store, this function does nothing
Definition at line 29 of file InstructionLineParser.cpp.
References REGULAR_BYTE, REGULAR_DOUBLE_WORD, REGULAR_WORD, SIGNED_BYTE, SIGNED_WORD, UNSIGNED_BYTE, and UNSIGNED_WORD.
Referenced by bnssassembler::InstructionLineParser::parse().
{
         transform(instruction.begin(), instruction.end(), instruction.begin(), tolower);
         if (instruction == "loadub") {
             instruction = "load";
             type = UNSIGNED_BYTE;
         }
         else if (instruction == "loadsb") {
             instruction = "load";
             type = SIGNED_BYTE;
         }
         else if (instruction == "loaduw") {
             instruction = "load";
             type = UNSIGNED_WORD;
         }
         else if (instruction == "loadsw") {
             instruction = "load";
             type = SIGNED_WORD;
         }
         else if (instruction == "load") {
             type = REGULAR_DOUBLE_WORD;
         }
         else if (instruction == "storeb") {
             instruction = "store";
             type = REGULAR_BYTE;
         }
         else if (instruction == "storew") {
             instruction = "store";
             type = REGULAR_WORD;
         }
         else if (instruction == "store") {
             type = REGULAR_DOUBLE_WORD;
         }
     }
multiple() [1/2]
std::string bnssassembler::multiple (unsigned char c, size_t times) inline
Returns a string containing multiple of the same characters.
Parameters
c Character
times Number of times this character should be in the string
Returns
String containing all the characters
Definition at line 37 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
{
         std::string ret;
         for (size_t i = 0; i < times; i++) {
             ret += c;
         }
         return ret;
     }
multiple() [2/2]
std::string bnssassembler::multiple (std::string s, size_t times) inline
Returns a string containing multiple of the same strings.
Parameters
s String
times Number of times this string should be in the returning string
Returns
String containing all the strings
Definition at line 52 of file PrintHelpers.h.
{
         std::string ret;
         for (size_t i = 0; i < times; i++) {
             ret += s;
         }
         return ret;
     }
name()
static std::string bnssassembler::name (SectionType type, bool indexed, size_t index) static
Definition at line 123 of file SectionData.cpp.
References BSS, DATA, RODATA, and TEXT.
Referenced by cxxopts::OptionDetails::as(), cxxopts::Options::operator[](), cxxopts::OptionAdder::OptionAdder(), bnssassembler::SymbolDefinitionLineParser::parse(), cxxopts::Options::parse(), bnssassembler::MicroRiscExpression::setValue(), and writeDescription().
{
         std::string ret(" .");
         switch (type) {
         case TEXT:
             ret += "text";
             break;
         case DATA:
             ret += "data";
             break;
         case RODATA:
             ret += "rodata";
             break;
         case BSS:
             ret += "bss";
             break;
         default:
             break;
         }
         if (indexed) {
             ret += "." + std::to_string(index);
         }
         return ret;
     }
operator!=() [1/3]
bool bnssassembler::operator!= (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 19 of file SymbolDefinition.cpp.
{
         return !(lhs == rhs);
     }
operator!=() [2/3]
bool bnssassembler::operator!= (const RelocationRecord & lhs, const RelocationRecord & rhs)
Definition at line 69 of file RelocationRecord.cpp.
{
         return !(lhs == rhs);
     }
operator!=() [3/3]
bool bnssassembler::operator!= (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 83 of file SectionData.cpp.
{
         return !(lhs == rhs);
     }
operator<() [1/2]
bool bnssassembler::operator< (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 23 of file SymbolDefinition.cpp.
References bnssassembler::SymbolDefinition::name_.
{
         return lhs.name_ < rhs.name_;
     }
operator<() [2/2]
bool bnssassembler::operator< (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 87 of file SectionData.cpp.
{
         if (lhs.type_ < rhs.type_) {
             return true;
         }
         if (lhs.type_ > rhs.type_) {
             return false;
         }
         if (!lhs.indexed_ && rhs.indexed_) {
             return true;
         }
         if (lhs.indexed_ && !rhs.indexed_) {
             return false;
         }
         if (lhs.indexed_) {
             return lhs.index_ < rhs.index_;
         }
         return false;
     }
operator<<() [1/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const SymbolTable & table)
Parameters
os Stream where the content will be written
table Data that will be written
Definition at line 22 of file SymbolTable.cpp.
References ALL_FOUR, HORIZONTAL, LOWER_LEFT, LOWER_RIGHT, multiple(), T_DOWN, T_LEFT, T_RIGHT, T_UP, UPPER_LEFT, UPPER_RIGHT, and VERTICAL.
{
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Symbol table:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 47) << T_DOWN << multiple(HORIZONTAL, 9) << T_DOWN << multiple(HORIZONTAL, 8) << T_DOWN << multiple(HORIZONTAL, 14) << T_LEFT << std::endl;
         std::cout << VERTICAL << "                     Name                      " << VERTICAL << " Section " << VERTICAL << " Offset " << VERTICAL << " Global/Local " << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 47) << ALL_FOUR << multiple(HORIZONTAL, 9) << ALL_FOUR << multiple(HORIZONTAL, 8) << ALL_FOUR << multiple(HORIZONTAL, 14) << T_LEFT << std::endl;
         os << table.size() << std::endl;
         for (auto &entry : table) {
             os << entry.second << std::endl;
         }
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 47) << T_UP << multiple(HORIZONTAL, 9) << T_UP << multiple(HORIZONTAL, 8) << T_UP << multiple(HORIZONTAL, 14) << LOWER_RIGHT << std::endl;
         return os;
     }
operator<<() [2/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const SymbolData & data)
Parameters
os Stream where the content will be written
data Data that will be written
Definition at line 30 of file SymbolData.cpp.
References bnssassembler::SymbolData::local_, bnssassembler::SymbolData::name_, bnssassembler::SymbolData::offset_, bnssassembler::SymbolData::section_index_, and VERTICAL.
{
         os << data.name_ << std::endl;
         os << data.section_index_ << std::endl;
         os << data.offset_ << std::endl;
         os << data.local_ << std::endl;
         std::cout << VERTICAL << " " << std::setw(46) << std::left << data.name_ << VERTICAL << " " << std::setw(8) << std::left << data.section_index_ << VERTICAL << " " << std::setw(7) << std::left << data.offset_ << VERTICAL << std::setw(14) << std::left << (data.local_ ? " Local" : " Global") << VERTICAL << std::endl;
         return os;
     }
operator<<() [3/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const RelocationRecord & record)
Parameters
os Stream where the content will be written
record Data that will be written
Definition at line 39 of file RelocationRecord.cpp.
References bnssassembler::RelocationRecord::absolute_, bnssassembler::RelocationRecord::offset_, bnssassembler::RelocationRecord::section_, bnssassembler::RelocationRecord::section_index_, bnssassembler::RelocationRecord::symbol_name_, and VERTICAL.
{
         os << record.offset_ << std::endl;
         os << record.absolute_ << std::endl;
         os << record.section_ << std::endl;
         if (record.section_) {
             os << record.section_index_ << std::endl;
         }
         else {
             os << record.symbol_name_ << std::endl;
         }
         std::cout << VERTICAL << " " << std::setw(7) << std::left << record.offset_ << VERTICAL << " " << (record.absolute_ ? "Absolute" : "Relative") << " " << VERTICAL << " ";
         if (record.section_) {
             std::cout << std::setw(8) << std::left << std::to_string(record.section_index_) + "." << VERTICAL << std::setw(51) << " " << VERTICAL << std::endl;
         }
         else {
             std::cout << std::setw(8) << " " << VERTICAL << std::setw(51) << std::left << record.symbol_name_ << VERTICAL << std::endl;
         }
         return os;
     }
operator<<() [4/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const SectionTable & section_table)
Parameters
os Stream where the content will be written
section_table Data that will be written
Definition at line 53 of file SectionTable.cpp.
References HORIZONTAL, LOWER_LEFT, LOWER_RIGHT, multiple(), UPPER_LEFT, UPPER_RIGHT, and VERTICAL.
{
         os << section_table.size() << std::endl;
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Section table:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 81) << LOWER_RIGHT << std::endl;
         for (auto &section : section_table) {
             os << section << std::endl;
         }
         std::cout << std::endl << std::endl;
         return os;
     }
operator<<() [5/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const SecondPassData & data)
Parameters
os Stream where the content will be written
data Data that will be written
Definition at line 83 of file SecondPassData.cpp.
References HORIZONTAL, bnssassembler::SecondPassData::imported_symbols_, LOWER_LEFT, LOWER_RIGHT, multiple(), bnssassembler::SecondPassData::section_table_, bnssassembler::SecondPassData::symbol_table_, T_LEFT, T_RIGHT, UPPER_LEFT, UPPER_RIGHT, and VERTICAL.
{
         os << data.imported_symbols_.size() << std::endl;
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Imported symbols:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 81) << T_LEFT << std::endl;
         for (auto &symbol : data.imported_symbols_) {
             os << symbol << std::endl;
             std::cout << VERTICAL << " " << std::setw(80) << std::left << symbol << VERTICAL << std::endl;
         }
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 81) << LOWER_RIGHT << std::endl << std::endl << std::endl;
         os << data.section_table_ << std::endl;
         os << data.symbol_table_ << std::endl;
         return os;
     }
operator<<() [6/6]
std::ostream& bnssassembler::operator<< (std::ostream & os, const SectionData & data)
Parameters
os Stream where the content will be written
data Data that will be written
Definition at line 156 of file SectionData.cpp.
References ALL_FOUR, bnssassembler::SectionData::data_, HORIZONTAL, bnssassembler::SectionData::index_, bnssassembler::SectionData::indexed_, bnssassembler::SectionData::location_counter_, LOWER_LEFT, LOWER_RIGHT, multiple(), bnssassembler::StringHelper::numberFormat(), bnssassembler::SectionData::org_address_, bnssassembler::SectionData::org_valid_, bnssassembler::SectionData::relocation_records_, T_DOWN, T_LEFT, T_RIGHT, T_UP, bnssassembler::StringHelper::toHexString(), bnssassembler::SectionData::type_, VERTICAL, and writeDescription().
{
         os << data.type_ << std::endl;
         os << data.indexed_ << std::endl;
         if (data.indexed_) {
             os << data.index_ << std::endl;
         }
         os << data.org_valid_ << std::endl;
         if (data.org_valid_) {
             os << data.org_address_ << std::endl;
         }
         os << data.location_counter_ << std::endl;
         os << data.data_.size() << std::endl;
         for (auto &entry : data.data_) {
             os << StringHelper::numberFormat(entry) << std::endl;
         }
         writeDescription(data.type_, data.indexed_, data.index_, data.org_valid_, data.org_address_, data.location_counter_);
         std::cout << VERTICAL << " ";
         size_t i;
         for (i = 0; i < data.data_.size(); i++) {
             auto entry = data.data_[i];
             if (i % 16 == 0 && i != 0) {
                 std::cout << VERTICAL << std::endl << VERTICAL << " ";
             }
             std::cout << StringHelper::toHexString(entry) << " ";
         }
         for (; i % 16 != 0 || i == 0; i++) {
             std::cout << "     ";
         }
         std::cout << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 81) << T_LEFT << std::endl;
         std::cout << VERTICAL << std::setw(81) << std::left << " Relocation table:" << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 8) << T_DOWN << multiple(HORIZONTAL, 10) << T_DOWN << multiple(HORIZONTAL, 9) << T_DOWN << multiple(HORIZONTAL, 51) << T_LEFT << std::endl;
         std::cout << VERTICAL << " Offset " << VERTICAL << " Absolute " << VERTICAL << " Section " << VERTICAL << "                      Symbol                       " << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 8) << ALL_FOUR << multiple(HORIZONTAL, 10) << ALL_FOUR << multiple(HORIZONTAL, 9) << ALL_FOUR << multiple(HORIZONTAL, 51) << T_LEFT << std::endl;
         os << data.relocation_records_.size() << std::endl;
         for (auto &record : data.relocation_records_) {
             os << record << std::endl;
         }
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 8) << T_UP << multiple(HORIZONTAL, 10) << T_UP << multiple(HORIZONTAL, 9) << T_UP << multiple(HORIZONTAL, 51) << LOWER_RIGHT << std::endl;
         return os;
     }
operator<=() [1/2]
bool bnssassembler::operator<= (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 31 of file SymbolDefinition.cpp.
{
         return !(lhs > rhs);
     }
operator<=() [2/2]
bool bnssassembler::operator<= (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 115 of file SectionData.cpp.
{
         return !(lhs > rhs);
     }
operator==() [1/3]
bool bnssassembler::operator== (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 15 of file SymbolDefinition.cpp.
References bnssassembler::SymbolDefinition::name_.
{
         return lhs.name_ == rhs.name_;
     }
operator==() [2/3]
bool bnssassembler::operator== (const RelocationRecord & lhs, const RelocationRecord & rhs)
Definition at line 61 of file RelocationRecord.cpp.
References bnssassembler::RelocationRecord::absolute_, bnssassembler::RelocationRecord::offset_, bnssassembler::RelocationRecord::section_, bnssassembler::RelocationRecord::section_index_, and bnssassembler::RelocationRecord::symbol_name_.
{
         return
             lhs.offset_ == rhs.offset_ &&
             lhs.absolute_ == rhs.absolute_ &&
             lhs.section_ == rhs.section_ &&
             (lhs.section_ ? lhs.section_index_ == rhs.section_index_ : lhs.symbol_name_ == rhs.symbol_name_);
     }
operator==() [3/3]
bool bnssassembler::operator== (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 79 of file SectionData.cpp.
{
         return lhs.type_ == rhs.type_ && lhs.indexed_ == rhs.indexed_ && (lhs.indexed_ ? lhs.index_ == rhs.index_ : true);
     }
operator>() [1/2]
bool bnssassembler::operator> (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 27 of file SymbolDefinition.cpp.
{
         return !(lhs < rhs || lhs == rhs);
     }
operator>() [2/2]
bool bnssassembler::operator> (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 111 of file SectionData.cpp.
{
         return !(lhs < rhs || lhs == rhs);
     }
operator>=() [1/2]
bool bnssassembler::operator>= (const SymbolDefinition & lhs, const SymbolDefinition & rhs)
Definition at line 35 of file SymbolDefinition.cpp.
{
         return !(lhs < rhs);
     }
operator>=() [2/2]
bool bnssassembler::operator>= (const SectionData & lhs, const SectionData & rhs) noexcept
Definition at line 119 of file SectionData.cpp.
{
         return !(lhs < rhs);
     }
parseData()
Data bnssassembler::parseData (std::string str)
Parses the data from the string.
Parameters
str String that will be parsed
Returns
Parsed data
Exceptions
Throws if the data could not be parsed
Definition at line 19 of file DataDefinitionLineParser.cpp.
References bnssassembler::ExpressionBuilder::build(), CONSTANT_TERM, DUPLICATE_DIRECTIVE, and bnssassembler::DataTypeParser::parse().
Referenced by bnssassembler::DataDefinitionLineParser::parse().
{
         static std::regex splitter("(.*)" + DUPLICATE_DIRECTIVE + "(.*)");
         static std::regex left_regex("[[:space:]]*([Dd][BbWwDd])(" + CONSTANT_TERM + ")");
         static std::regex uninitialized_value("[[:space:]]*\\?[[:space:]]*");
         auto left = str;
         std::string right;
         if (regex_match(str, splitter)) {
             left = regex_replace(str, splitter, "$1");
             right = regex_replace(str, splitter, "$2");
         }
         if (!regex_match(left, left_regex)) {
             throw InvalidDataDefinitionException(str);
         }
         auto data_type_string = regex_replace(left, left_regex, "$1");
         auto left_expression_string = regex_replace(left, left_regex, "$2");
         auto data_type = DataTypeParser::parse(data_type_string);
         auto left_expression = ExpressionBuilder::build(left_expression_string);
         if (right.empty()) {
             return Data(data_type, left_expression, ExpressionBuilder::build("1"));
         }
         if (regex_match(right, uninitialized_value)) {
             return Data(data_type, left_expression);
         }
         auto right_expression = ExpressionBuilder::build(right);
         return Data(data_type, right_expression, left_expression);
     }
parsePcrel()
std::shared_ptr<Operand> bnssassembler::parsePcrel (std::string str)
Parses the input as a PC relative address.
Parameters
str String representation of an operand
Returns
Pointer to the parsed operand or nullptr if the input is not a PC relative address
Exceptions
Throws if the string could not be parsed
Definition at line 16 of file RegisterIndirectOffsetParser.cpp.
References bnssassembler::ExpressionBuilder::build(), CONSTANT_TERM, and PC.
Referenced by bnssassembler::RegisterIndirectOffsetParser::parse().
{
         static std::regex regex("[[:space:]]*\\$(" + CONSTANT_TERM + ")");
         if (!regex_match(str, regex)) {
             return nullptr;
         }
         auto address_string = regex_replace(str, regex, "$1");
         auto address = ExpressionBuilder::build(address_string);
         return std::make_shared<RegisterIndirectOffset>(PC, address, true);
     }
postfixToTree()
static std::shared_ptr<Expression> bnssassembler::postfixToTree (const std::list< std::shared_ptr< ExpressionToken >> & postfix_expression) static
Builds a tree from the postfix expression.
Parameters
postfix_expression Postfix expression
Returns
Pointer to the root of the tree
Definition at line 71 of file ExpressionBuilder.cpp.
Referenced by bnssassembler::ExpressionBuilder::build().
{
         if (postfix_expression.size() == 0) {
             return nullptr;
         }
         std::stack<std::reference_wrapper<std::shared_ptr<Expression>>> stack;
         std::shared_ptr<Expression> root = nullptr;
         stack.push(root);
         for (auto iterator = postfix_expression.rbegin(); iterator != postfix_expression.rend(); ++iterator) {
             if (stack.empty()) {
                 throw MessageException("Invalid expression - not enough operators");
             }
             std::shared_ptr<Expression> &curr = stack.top();
             stack.pop();
             curr = iterator->get()->create();
             curr->pushChildren(stack);
         }
         return root;
     }
split()
static void bnssassembler::split (std::list< RelocationRecord > & original, std::list< RelocationRecord > & left, std::list< RelocationRecord > & right) static
Definition at line 11 of file AddOperation.cpp.
Referenced by bnssassembler::AddOperation::generateRelocations().
{
         for (auto &element : original) {
             if (element.opposite()) {
                 element.toggleOpposite();
                 right.push_back(element);
             }
             else {
                 left.push_back(element);
             }
         }
     }
stripComment()
static void bnssassembler::stripComment (std::string & line, std::vector< std::string > one_line_comment_delimiters) static
Strips the comment from one line of the file.
Parameters
line Line of the file
one_line_comment_delimiters Delimiters for one-line comments
Definition at line 18 of file Parser.cpp.
References bnssassembler::StringHelper::join().
Referenced by bnssassembler::Parser::parse().
{
         auto delimiters = StringHelper::join(one_line_comment_delimiters, "|");
         std::regex regex("(.*?)(" + delimiters + ").*");
         line = regex_replace(line, regex, "$1");
     }
writeDescription()
static void bnssassembler::writeDescription (SectionType type, bool indexed, size_t index, bool org_valid, uint32_t org_address, size_t size) static
Definition at line 149 of file SectionData.cpp.
References HORIZONTAL, multiple(), name(), T_LEFT, T_RIGHT, bnssassembler::StringHelper::toHexString(), UPPER_LEFT, UPPER_RIGHT, and VERTICAL.
Referenced by operator<<().
{
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         auto description = name(type, indexed, index) + " size: " + StringHelper::toHexString(size) + (org_valid ? " ORG: " + StringHelper::toHexString(org_address) : "");
         std::cout << VERTICAL << std::setw(81) << std::left << description << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 81) << T_LEFT << std::endl;
     }
Variable Documentation
ALL_FOUR
const std::string bnssassembler::ALL_FOUR = "\u256c"
Definition at line 29 of file PrintHelpers.h.
Referenced by operator<<().
BINARY
const std::string bnssassembler::BINARY = "0b[01][01]*"
Definition at line 10 of file CommonRegexes.h.
BINARY_REGEX
const std::regex bnssassembler::BINARY_REGEX = std::regex(BINARY)
Definition at line 36 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().
CHARACTER
const std::string bnssassembler::CHARACTER = "'[[:print:]]'"
Definition at line 12 of file CommonRegexes.h.
CHARACTER_REGEX
const std::regex bnssassembler::CHARACTER_REGEX = std::regex(CHARACTER)
Definition at line 38 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().
COMMA_TOKENIZER
const std::string bnssassembler::COMMA_TOKENIZER = "[[:space:]]*(.*?)[[:space:]]*,(.*)"
Definition at line 30 of file CommonRegexes.h.
COMMA_TOKENIZER_REGEX
const std::regex bnssassembler::COMMA_TOKENIZER_REGEX = std::regex(COMMA_TOKENIZER)
Definition at line 51 of file CommonRegexes.h.
Referenced by bnssassembler::DataDefinitionLineParser::parse(), and bnssassembler::InstructionParser::parse().
CONSTANT_TERM
const std::string bnssassembler::CONSTANT_TERM = "([[:space:]]*(" + LITERAL + "|" + OPERATOR + "|" + SYMBOL + ")[[:space:]]*)*"
Definition at line 23 of file CommonRegexes.h.
Referenced by bnssassembler::ImmediateParser::parse(), bnssassembler::SymbolDefinitionLineParser::parse(), bnssassembler::OrgDirectiveLineParser::parse(), parseData(), and parsePcrel().
CONSTANT_TERM_REGEX
const std::regex bnssassembler::CONSTANT_TERM_REGEX = std::regex(CONSTANT_TERM)
Definition at line 44 of file CommonRegexes.h.
Referenced by bnssassembler::MemoryDirectParser::parse().
DECIMAL
const std::string bnssassembler::DECIMAL = "[1-9][0-9]*"
Definition at line 8 of file CommonRegexes.h.
DECIMAL_REGEX
const std::regex bnssassembler::DECIMAL_REGEX = std::regex(DECIMAL)
Definition at line 34 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().
DUPLICATE_DIRECTIVE
const std::string bnssassembler::DUPLICATE_DIRECTIVE = "[Dd][Uu][Pp]"
Definition at line 27 of file CommonRegexes.h.
Referenced by parseData().
DUPLICATE_DIRECTIVE_REGEX
const std::regex bnssassembler::DUPLICATE_DIRECTIVE_REGEX = std::regex(DUPLICATE_DIRECTIVE)
Definition at line 48 of file CommonRegexes.h.
GLOBAL_DIRECTIVE
const std::string bnssassembler::GLOBAL_DIRECTIVE = "[.][Gg][Ll][Oo][Bb][Aa][Ll]"
Definition at line 28 of file CommonRegexes.h.
Referenced by bnssassembler::GlobalSymbolsLineParser::parse().
GLOBAL_DIRECTIVE_REGEX
const std::regex bnssassembler::GLOBAL_DIRECTIVE_REGEX = std::regex(GLOBAL_DIRECTIVE)
Definition at line 49 of file CommonRegexes.h.
HEX
const std::string bnssassembler::HEX = "0x[0-9a-fA-F][0-9a-fA-F]*"
Definition at line 9 of file CommonRegexes.h.
HEX_REGEX
const std::regex bnssassembler::HEX_REGEX = std::regex(HEX)
Definition at line 35 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().
HORIZONTAL
const std::string bnssassembler::HORIZONTAL = "\u2550"
Definition at line 23 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
LABEL
const std::string bnssassembler::LABEL = SYMBOL
Definition at line 22 of file CommonRegexes.h.
Referenced by extractLabel().
LABEL_REGEX
const std::regex bnssassembler::LABEL_REGEX = std::regex(LABEL)
Definition at line 43 of file CommonRegexes.h.
LAST_COMMA_TOKEN
const std::string bnssassembler::LAST_COMMA_TOKEN = "[[:space:]]*(.*)[[:space:]]*"
Definition at line 31 of file CommonRegexes.h.
LAST_COMMA_TOKEN_REGEX
const std::regex bnssassembler::LAST_COMMA_TOKEN_REGEX = std::regex(LAST_COMMA_TOKEN)
Definition at line 52 of file CommonRegexes.h.
Referenced by bnssassembler::DataDefinitionLineParser::parse(), and bnssassembler::InstructionParser::parse().
LITERAL
const std::string bnssassembler::LITERAL = "(" + ZERO + "|" + DECIMAL + "|" + HEX + "|" + BINARY + "|" + OCT + "|" + CHARACTER + ")"
Definition at line 17 of file CommonRegexes.h.
Referenced by infixToPostfix().
LITERAL_REGEX
const std::regex bnssassembler::LITERAL_REGEX = std::regex(LITERAL)
Definition at line 40 of file CommonRegexes.h.
Referenced by bnssassembler::ExpressionTokenFactory::create().
LOWER_LEFT
const std::string bnssassembler::LOWER_LEFT = "\u255a"
Definition at line 21 of file PrintHelpers.h.
Referenced by operator<<().
LOWER_RIGHT
const std::string bnssassembler::LOWER_RIGHT = "\u255d"
Definition at line 22 of file PrintHelpers.h.
Referenced by operator<<().
NUM_OF_REGISTERS
const size_t bnssassembler::NUM_OF_REGISTERS = 16
Number of all purpose registers (excluding PC and SP)
Definition at line 11 of file Register.h.
Referenced by bnssassembler::RegisterParser::RegisterParserStaticData::RegisterParserStaticData().
OCT
const std::string bnssassembler::OCT = "0[0-7][0-7]*"
Definition at line 11 of file CommonRegexes.h.
OCT_REGEX
const std::regex bnssassembler::OCT_REGEX = std::regex(OCT)
Definition at line 37 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().
OPERATOR
const std::string bnssassembler::OPERATOR = "[-+*/()]"
Definition at line 20 of file CommonRegexes.h.
Referenced by infixToPostfix().
OPERATOR_REGEX
const std::regex bnssassembler::OPERATOR_REGEX = std::regex(OPERATOR)
Definition at line 41 of file CommonRegexes.h.
Referenced by bnssassembler::ExpressionTokenFactory::create().
ORG_DIRECTIVE
const std::string bnssassembler::ORG_DIRECTIVE = "[Oo][Rr][Gg]"
Definition at line 25 of file CommonRegexes.h.
Referenced by bnssassembler::OrgDirectiveLineParser::parse().
ORG_DIRECTIVE_REGEX
const std::regex bnssassembler::ORG_DIRECTIVE_REGEX = std::regex(ORG_DIRECTIVE)
Definition at line 46 of file CommonRegexes.h.
SYMBOL
const std::string bnssassembler::SYMBOL = "(([a-zA-Z_][a-zA-Z_0-9]*)|\\$)"
Definition at line 21 of file CommonRegexes.h.
Referenced by infixToPostfix(), bnssassembler::SymbolDefinitionLineParser::parse(), and bnssassembler::GlobalSymbolsLineParser::parse().
SYMBOL_DEFINITION
const std::string bnssassembler::SYMBOL_DEFINITION = "[Dd][Ee][Ff]"
Definition at line 26 of file CommonRegexes.h.
Referenced by bnssassembler::SymbolDefinitionLineParser::parse().
SYMBOL_DEFINITION_REGEX
const std::regex bnssassembler::SYMBOL_DEFINITION_REGEX = std::regex(SYMBOL_DEFINITION)
Definition at line 47 of file CommonRegexes.h.
SYMBOL_REGEX
const std::regex bnssassembler::SYMBOL_REGEX = std::regex(SYMBOL)
Definition at line 42 of file CommonRegexes.h.
Referenced by bnssassembler::ExpressionTokenFactory::create().
T_DOWN
const std::string bnssassembler::T_DOWN = "\u2566"
Definition at line 28 of file PrintHelpers.h.
Referenced by operator<<().
T_LEFT
const std::string bnssassembler::T_LEFT = "\u2563"
Definition at line 25 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
T_RIGHT
const std::string bnssassembler::T_RIGHT = "\u2560"
Definition at line 26 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
T_UP
const std::string bnssassembler::T_UP = "\u2569"
Definition at line 27 of file PrintHelpers.h.
Referenced by operator<<().
UPPER_LEFT
const std::string bnssassembler::UPPER_LEFT = "\u2554"
Definition at line 19 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
UPPER_RIGHT
const std::string bnssassembler::UPPER_RIGHT = "\u2557"
Definition at line 20 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
VERTICAL
const std::string bnssassembler::VERTICAL = "\u2551"
Definition at line 24 of file PrintHelpers.h.
Referenced by operator<<(), and writeDescription().
ZERO
const std::string bnssassembler::ZERO = "0"
Definition at line 7 of file CommonRegexes.h.
ZERO_REGEX
const std::regex bnssassembler::ZERO_REGEX = std::regex(ZERO)
Definition at line 33 of file CommonRegexes.h.
Referenced by bnssassembler::StringHelper::parseNumber().