AssemblerEmulator - Nikola Bebic: consoleio Namespace Reference
consoleio Namespace Reference
Functions
bool keyboardHit ()
int getCharacter ()
static void restore ()
static void initialize ()
Variables
static struct termios old_termios
static bool initialized = false
static const int STDIN_DESCRIPTOR_ID = 0
Function Documentation
getCharacter()
int consoleio::getCharacter ()
Definition at line 66 of file ConsoleInputOutput.cpp.
References initialize().
Referenced by bnssemulator::KeyboardListener::listen().
{
 #ifdef _MSC_VER
         return _getch();
 #else
         initialize();
         int r;
         unsigned char c;
         if ((r = read(0, &c, sizeof(c))) < 0) {
             return r;
         }
         else {
             return c;
         }
 #endif
     }
initialize()
static void consoleio::initialize () static
Definition at line 28 of file ConsoleInputOutput.cpp.
References old_termios, and restore().
Referenced by getCharacter(), and keyboardHit().
{
         if (!initialized) {
             initialized = true;
             // Get the file descriptor for standard input terminal
             tcgetattr(STDIN_DESCRIPTOR_ID, &old_termios);
             // Create a copy of the descriptor to work on
             struct termios new_termios;
             memcpy(&new_termios, &old_termios, sizeof(new_termios));
             // Restore old descriptor on exit
             atexit(restore);
             // Unset the ECHO and ICANON flags, and set the descriptor
             // Unsetting the ECHO flag disables the output of characters to terminal
             // when they are typed
             // Unsetting the ICANON flag makes the read function read characters directly
             // from console, without the need for a newline
             new_termios.c_lflag &= ~(ICANON | ECHO);
             tcsetattr(STDIN_DESCRIPTOR_ID, TCSANOW, &new_termios);
         }
     }
keyboardHit()
bool consoleio::keyboardHit ()
Definition at line 53 of file ConsoleInputOutput.cpp.
References initialize().
Referenced by bnssemulator::KeyboardListener::listen().
{
 #ifdef _MSC_VER
         return _kbhit();
 #else
         initialize();
         struct timeval tv = { 0L, 0L };
         fd_set fds;
         FD_ZERO(&fds);
         FD_SET(0, &fds);
         return select(1, &fds, NULL, NULL, &tv);
 #endif
     }
restore()
static void consoleio::restore () static
Definition at line 24 of file ConsoleInputOutput.cpp.
References old_termios.
Referenced by initialize().
{
         tcsetattr(STDIN_DESCRIPTOR_ID, TCSANOW, &old_termios);
     }
Variable Documentation
initialized
bool consoleio::initialized = false static
Definition at line 21 of file ConsoleInputOutput.cpp.
old_termios
struct termios consoleio::old_termios static
Definition at line 20 of file ConsoleInputOutput.cpp.
Referenced by initialize(), and restore().
STDIN_DESCRIPTOR_ID
const int consoleio::STDIN_DESCRIPTOR_ID = 0 static
Definition at line 22 of file ConsoleInputOutput.cpp.