AssemblerEmulator - Nikola Bebic: bnssemulator::Context Class Reference
bnssemulator::Context Class Reference
Class representing the context of the processor.
#include <Context.h>
Public Member Functions
Context (AssemblerOutput &&assembler_output)
Constructs a Context object.
void pushToStack (int32_t value)
Pushes a value to the stack.
int32_t popFromStack ()
Pops a value from the stack.
Register & getRegister (size_t index) noexcept
Gets the reference to the register.
const Register & getRegister (size_t index) const noexcept
Gets the reference to the register.
AddressSpace & addressSpace () noexcept
Gets the address space.
const AddressSpace & addressSpace () const noexcept
Gets the address space.
void jumpTo (uint32_t address)
Jumps to address.
void jumpToSubroutine (uint32_t address)
Jumps to subroutine at address.
void jumpToInterrupt (size_t entry)
Jumps to interrupt routine at the specified entry.
void returnFromSubroutine ()
Returns from subroutine.
int32_t getOperand (InstructionBitField instruction, size_t register_index, size_t num_of_bytes=4)
Gets the operand based on the instruction.
int32_t getOperandAddress (InstructionBitField instruction, size_t register_index)
Gets the address of the operand based on the instruction.
InstructionBitField getInstruction ()
Gets the instruction to execute.
int32_t getSecondWordOfInstruction ()
Gets the second word of the instruction.
void finishProgram () noexcept
Finishes the program.
bool programFinished () const noexcept
Checks whether the program finished.
bool insideInterrupt () const noexcept
Checks whether the program is executing an interrupt routine.
void pressCharacter (char character) noexcept
Presses a character.
bool hasCharacters () const noexcept
Checks whether there are any characters that should be written to stdin.
char getCharacter () noexcept
Gets the first character to be written to stdin.
bool timerTriggered () const noexcept
Checks if the timer was triggered.
void timerTriggered (bool value) noexcept
Sets the timer triggered flag.
void jumpToErrorInterrupt () noexcept
Jumps to error interrupt.
void jumpToTimerInterrupt () noexcept
Jumps to timer interrupt.
void jumpToKeyboardInterrupt () noexcept
Jumps to keyboard interrupt.
Private Attributes
AddressSpace address_space_
std::vector< Register > registers_
Register & stack_pointer_
Register & program_counter_
bool inside_interrupt_ = false
size_t interrupt_call_stack_depth_ = 0
std::mutex characters_mutex_
std::queue< char > characters_
std::mutex timer_mutex_
bool timer_triggered_ = false
bool end_of_program_ = false
Detailed Description
Class representing the context of the processor.
Definition at line 15 of file Context.h.
Constructor & Destructor Documentation
Context()
bnssemulator::Context::Context (AssemblerOutput && assembler_output) explicit
Constructs a Context object.
Parameters
assembler_output R-value reference to the assembler output object
Exceptions
Throws if the context can not be constructed
Definition at line 8 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::initialStackPointer(), bnssemulator::StringHelper::join(), program_counter_, stack_pointer_, and bnssemulator::Register::value().
                                                         : address_space_(move(assembler_output.sectionTable()), assembler_output.symbolTable()), registers_(18), stack_pointer_(registers_[16]), program_counter_(registers_[17]) {
         if (assembler_output.importedSymbolsExist()) {
             throw MessageException("Can not resolve imported symbols: " + StringHelper::join(assembler_output.importedSymbolsAsVector(), ", "));
         }
         stack_pointer_.value(address_space_.initialStackPointer());
         program_counter_.value(assembler_output.startOfProgram("_start"));
     }
Member Function Documentation
addressSpace() [1/2]
AddressSpace & bnssemulator::Context::addressSpace () noexcept
Gets the address space.
Returns
Address space
Definition at line 37 of file Context.cpp.
References address_space_.
Referenced by addressSpace(), and bnssemulator::StoreExecuter::execute().
{
         return address_space_;
     }
addressSpace() [2/2]
const AddressSpace & bnssemulator::Context::addressSpace () const noexcept
Gets the address space.
Returns
Address space
Definition at line 41 of file Context.cpp.
References addressSpace().
{
         return const_cast<Context &>(*this).addressSpace();
     }
finishProgram()
void bnssemulator::Context::finishProgram () noexcept
Finishes the program.
Definition at line 153 of file Context.cpp.
References end_of_program_.
Referenced by bnssemulator::IntExecuter::execute(), and bnssemulator::Processor::executeProgram().
{
         end_of_program_ = true;
     }
getCharacter()
char bnssemulator::Context::getCharacter () noexcept
Gets the first character to be written to stdin.
Returns
Character to be written to stdin
Definition at line 178 of file Context.cpp.
References characters_, and characters_mutex_.
Referenced by jumpToKeyboardInterrupt().
{
         characters_mutex_.lock();
         auto ret = characters_.front();
         characters_.pop();
         characters_mutex_.unlock();
         return ret;
     }
getInstruction()
InstructionBitField bnssemulator::Context::getInstruction ()
Gets the instruction to execute.
Returns
Instruction
Definition at line 140 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::getInstruction(), and program_counter_.
Referenced by bnssemulator::Processor::executeInstruction().
{
         auto ret = address_space_.getInstruction(program_counter_);
         program_counter_ += 4;
         return ret;
     }
getOperand()
int32_t bnssemulator::Context::getOperand (InstructionBitField instruction, size_t register_index, size_t num_of_bytes = 4)
Gets the operand based on the instruction.
Parameters
instruction Instruction
register_index Index of the register to use in case of register address modes
num_of_bytes Number of bytes of the operand
Returns
Operand
Definition at line 94 of file Context.cpp.
References bnssemulator::InstructionBitField::address_mode, address_space_, bnssemulator::AddressSpace::get16bitData(), bnssemulator::AddressSpace::get32bitData(), bnssemulator::AddressSpace::get8bitData(), getOperandAddress(), bnssemulator::getRegisterIndex(), getSecondWordOfInstruction(), bnssemulator::IMMEDIATE, bnssemulator::MEMORY_DIRECT, bnssemulator::REGISTER_DIRECT, bnssemulator::REGISTER_INDIRECT, bnssemulator::REGISTER_INDIRECT_OFFSET, registers_, and bnssemulator::StringHelper::toHexString().
Referenced by bnssemulator::LoadExecuter::execute().
{
         int32_t val;
         switch (instruction.address_mode) {
         case IMMEDIATE:
             val = getSecondWordOfInstruction();
             return val;
         case REGISTER_DIRECT:
             return registers_[getRegisterIndex(instruction, register_index)];
         case MEMORY_DIRECT:
         case REGISTER_INDIRECT:
         case REGISTER_INDIRECT_OFFSET:
             val = getOperandAddress(instruction, register_index);
             switch (num_of_bytes) {
             case 1:
                 return address_space_.get8bitData(val);
             case 2:
                 return address_space_.get16bitData(val);
             case 4:
                 return address_space_.get32bitData(val);
             default:
                 throw MessageException("Invalid number of bytes");
             }
         default:
             throw MessageException("Invalid address mode: " + StringHelper::toHexString(instruction.address_mode));
         }
     }
getOperandAddress()
int32_t bnssemulator::Context::getOperandAddress (InstructionBitField instruction, size_t register_index)
Gets the address of the operand based on the instruction.
Parameters
instruction Instruction
register_index Index of the register to use in case of register address modes
Returns
Address of the operand
Definition at line 121 of file Context.cpp.
References bnssemulator::InstructionBitField::address_mode, bnssemulator::getRegisterIndex(), getSecondWordOfInstruction(), bnssemulator::MEMORY_DIRECT, bnssemulator::REGISTER_INDIRECT, bnssemulator::REGISTER_INDIRECT_OFFSET, registers_, and bnssemulator::StringHelper::toHexString().
Referenced by bnssemulator::CallExecuter::execute(), bnssemulator::StoreExecuter::execute(), bnssemulator::JmpExecuter::execute(), bnssemulator::ConditionalJumpExecuter::execute(), and getOperand().
{
         // ReSharper disable once CppJoinDeclarationAndAssignment
         uint32_t second_word;
         switch (instruction.address_mode) {
         case MEMORY_DIRECT:
             return getSecondWordOfInstruction();
         case REGISTER_INDIRECT:
             return registers_[getRegisterIndex(instruction, register_index)];
         case REGISTER_INDIRECT_OFFSET:
             // ReSharper disable once CppJoinDeclarationAndAssignment
             second_word = getSecondWordOfInstruction();
             return static_cast<uint32_t>(registers_[getRegisterIndex(instruction, register_index)]) + second_word;
         default:
             throw MessageException("Invalid address mode: " + StringHelper::toHexString(instruction.address_mode));
         }
     }
getRegister() [1/2]
Register & bnssemulator::Context::getRegister (size_t index) noexcept
Gets the reference to the register.
Parameters
index Index of the register
Returns
Reference to the register
Definition at line 29 of file Context.cpp.
References registers_.
Referenced by bnssemulator::AluExecuter::execute(), bnssemulator::StoreExecuter::execute(), bnssemulator::PushExecuter::execute(), bnssemulator::PopExecuter::execute(), bnssemulator::ConditionalJumpExecuter::execute(), bnssemulator::LoadExecuter::execute(), bnssemulator::IntExecuter::execute(), bnssemulator::NotExecuter::execute(), and getRegister().
{
         return registers_[index];
     }
getRegister() [2/2]
const Register & bnssemulator::Context::getRegister (size_t index) const noexcept
Gets the reference to the register.
Parameters
index Index of the register
Returns
Reference to the register
Definition at line 33 of file Context.cpp.
References getRegister().
{
         return const_cast<Context &>(*this).getRegister(index);
     }
getSecondWordOfInstruction()
int32_t bnssemulator::Context::getSecondWordOfInstruction ()
Gets the second word of the instruction.
Returns
Second word of the instruction
Definition at line 147 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::getSecondWordOfInstruction(), and program_counter_.
Referenced by getOperand(), and getOperandAddress().
{
         auto ret = address_space_.getSecondWordOfInstruction(program_counter_);
         program_counter_ += 4;
         return ret;
     }
hasCharacters()
bool bnssemulator::Context::hasCharacters () const noexcept
Checks whether there are any characters that should be written to stdin.
Definition at line 171 of file Context.cpp.
References characters_, and characters_mutex_.
Referenced by bnssemulator::Processor::executeProgram().
{
         characters_mutex_.lock();
         auto ret = !characters_.empty();
         characters_mutex_.unlock();
         return ret;
     }
insideInterrupt()
bool bnssemulator::Context::insideInterrupt () const noexcept
Checks whether the program is executing an interrupt routine.
Returns
Whether the program is executing an interrupt routine
Definition at line 161 of file Context.cpp.
References inside_interrupt_.
Referenced by bnssemulator::Processor::executeProgram().
{
         return inside_interrupt_;
     }
jumpTo()
void bnssemulator::Context::jumpTo (uint32_t address)
Jumps to address.
Parameters
address Address
Definition at line 46 of file Context.cpp.
References program_counter_.
Referenced by bnssemulator::ConditionalJumpExecuter::execute(), bnssemulator::JmpExecuter::execute(), and jumpToSubroutine().
{
         program_counter_ = address;
     }
jumpToErrorInterrupt()
void bnssemulator::Context::jumpToErrorInterrupt () noexcept
Jumps to error interrupt.
Definition at line 199 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::errorInterrupt(), and jumpToInterrupt().
Referenced by bnssemulator::Processor::executeProgram().
{
         jumpToInterrupt(address_space_.errorInterrupt());
     }
jumpToInterrupt()
void bnssemulator::Context::jumpToInterrupt (size_t entry)
Jumps to interrupt routine at the specified entry.
Parameters
entry Entry
Definition at line 59 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::getInterrupt(), inside_interrupt_, and jumpToSubroutine().
Referenced by bnssemulator::IntExecuter::execute(), jumpToErrorInterrupt(), jumpToKeyboardInterrupt(), and jumpToTimerInterrupt().
{
         inside_interrupt_ = true;
         jumpToSubroutine(address_space_.getInterrupt(entry));
     }
jumpToKeyboardInterrupt()
void bnssemulator::Context::jumpToKeyboardInterrupt () noexcept
Jumps to keyboard interrupt.
Definition at line 208 of file Context.cpp.
References address_space_, getCharacter(), jumpToInterrupt(), bnssemulator::AddressSpace::keyboardInterrupt(), and bnssemulator::AddressSpace::writeToStdin().
Referenced by bnssemulator::Processor::executeProgram().
{
         address_space_.writeToStdin(getCharacter());
         jumpToInterrupt(address_space_.keyboardInterrupt());
     }
jumpToSubroutine()
void bnssemulator::Context::jumpToSubroutine (uint32_t address)
Jumps to subroutine at address.
Parameters
address Address
Definition at line 50 of file Context.cpp.
References inside_interrupt_, interrupt_call_stack_depth_, jumpTo(), program_counter_, and pushToStack().
Referenced by bnssemulator::CallExecuter::execute(), and jumpToInterrupt().
{
         if (inside_interrupt_) {
             interrupt_call_stack_depth_++;
         }
         pushToStack(program_counter_);
         jumpTo(address);
     }
jumpToTimerInterrupt()
void bnssemulator::Context::jumpToTimerInterrupt () noexcept
Jumps to timer interrupt.
Definition at line 203 of file Context.cpp.
References address_space_, jumpToInterrupt(), timer_triggered_, and bnssemulator::AddressSpace::timerInterrupt().
Referenced by bnssemulator::Processor::executeProgram().
{
         timer_triggered_ = false;
         jumpToInterrupt(address_space_.timerInterrupt());
     }
popFromStack()
int32_t bnssemulator::Context::popFromStack ()
Pops a value from the stack.
Returns
Popped value
Exceptions
Throws if stack underflow happens
Definition at line 23 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::get32bitData(), and stack_pointer_.
Referenced by bnssemulator::PopExecuter::execute(), and returnFromSubroutine().
{
         int32_t ret = address_space_.get32bitData(stack_pointer_);
         stack_pointer_ -= 4;
         return ret;
     }
pressCharacter()
void bnssemulator::Context::pressCharacter (char character) noexcept
Presses a character.
Parameters
character Character
Definition at line 165 of file Context.cpp.
References characters_, and characters_mutex_.
Referenced by bnssemulator::KeyboardListener::listen().
{
         characters_mutex_.lock();
         characters_.push(character);
         characters_mutex_.unlock();
     }
programFinished()
bool bnssemulator::Context::programFinished () const noexcept
Checks whether the program finished.
Returns
Whether the program finished
Definition at line 157 of file Context.cpp.
References end_of_program_.
Referenced by bnssemulator::Processor::executeProgram(), bnssemulator::TimerListener::listen(), and bnssemulator::KeyboardListener::listen().
{
         return end_of_program_;
     }
pushToStack()
void bnssemulator::Context::pushToStack (int32_t value)
Pushes a value to the stack.
Parameters
value Value to be pushed
Exceptions
Throws if stack overflow happens
Definition at line 17 of file Context.cpp.
References address_space_, bnssemulator::AddressSpace::set32bitData(), and stack_pointer_.
Referenced by bnssemulator::PushExecuter::execute(), and jumpToSubroutine().
{
         stack_pointer_ += 4;
         address_space_.set32bitData(stack_pointer_, value);
     }
returnFromSubroutine()
void bnssemulator::Context::returnFromSubroutine ()
Returns from subroutine.
Definition at line 64 of file Context.cpp.
References inside_interrupt_, interrupt_call_stack_depth_, popFromStack(), and program_counter_.
Referenced by bnssemulator::RetExecuter::execute().
{
         if (inside_interrupt_) {
             interrupt_call_stack_depth_--;
             if (interrupt_call_stack_depth_ == 0) {
                 inside_interrupt_ = false;
             }
         }
         program_counter_ = popFromStack();
     }
timerTriggered() [1/2]
bool bnssemulator::Context::timerTriggered () const noexcept
Checks if the timer was triggered.
Returns
Whether the timer has been triggered
Definition at line 186 of file Context.cpp.
References timer_mutex_, and timer_triggered_.
Referenced by bnssemulator::Processor::executeProgram(), and bnssemulator::TimerListener::listen().
{
         timer_mutex_.lock();
         auto ret = timer_triggered_;
         timer_mutex_.unlock();
         return ret;
     }
timerTriggered() [2/2]
void bnssemulator::Context::timerTriggered (bool value) noexcept
Sets the timer triggered flag.
Parameters
value Flag
Definition at line 193 of file Context.cpp.
References timer_mutex_, timer_triggered_, and cxxopts::value().
{
         timer_mutex_.lock();
         timer_triggered_ = value;
         timer_mutex_.unlock();
     }
Member Data Documentation
address_space_
AddressSpace bnssemulator::Context::address_space_ private
Definition at line 177 of file Context.h.
Referenced by addressSpace(), Context(), getInstruction(), getOperand(), getSecondWordOfInstruction(), jumpToErrorInterrupt(), jumpToInterrupt(), jumpToKeyboardInterrupt(), jumpToTimerInterrupt(), popFromStack(), and pushToStack().
characters_
std::queue<char> bnssemulator::Context::characters_ private
Definition at line 186 of file Context.h.
Referenced by getCharacter(), hasCharacters(), and pressCharacter().
characters_mutex_
std::mutex bnssemulator::Context::characters_mutex_ mutable private
Definition at line 185 of file Context.h.
Referenced by getCharacter(), hasCharacters(), and pressCharacter().
end_of_program_
bool bnssemulator::Context::end_of_program_ = false private
Definition at line 191 of file Context.h.
Referenced by finishProgram(), and programFinished().
inside_interrupt_
bool bnssemulator::Context::inside_interrupt_ = false private
Definition at line 182 of file Context.h.
Referenced by insideInterrupt(), jumpToInterrupt(), jumpToSubroutine(), and returnFromSubroutine().
interrupt_call_stack_depth_
size_t bnssemulator::Context::interrupt_call_stack_depth_ = 0 private
Definition at line 183 of file Context.h.
Referenced by jumpToSubroutine(), and returnFromSubroutine().
program_counter_
Register& bnssemulator::Context::program_counter_ private
Definition at line 180 of file Context.h.
Referenced by Context(), getInstruction(), getSecondWordOfInstruction(), jumpTo(), jumpToSubroutine(), and returnFromSubroutine().
registers_
std::vector<Register> bnssemulator::Context::registers_ private
Definition at line 178 of file Context.h.
Referenced by getOperand(), getOperandAddress(), and getRegister().
stack_pointer_
Register& bnssemulator::Context::stack_pointer_ private
Definition at line 179 of file Context.h.
Referenced by Context(), popFromStack(), and pushToStack().
timer_mutex_
std::mutex bnssemulator::Context::timer_mutex_ mutable private
Definition at line 188 of file Context.h.
Referenced by timerTriggered().
timer_triggered_
bool bnssemulator::Context::timer_triggered_ = false private
Definition at line 189 of file Context.h.
Referenced by jumpToTimerInterrupt(), and timerTriggered().
The documentation for this class was generated from the following files:
Code/Emulator/Include/Context.h
Code/Emulator/Source/Context.cpp