AssemblerEmulator - Nikola Bebic: cxxopts::OptionDetails Class Reference
cxxopts::OptionDetails Class Reference
#include <cxxopts.h>
Public Member Functions
OptionDetails (const String &desc, std::shared_ptr< const Value > val)
const String & description () const
bool has_arg () const
void parse (const std::string &text)
void parse_default () const
int count () const
const Value & value () const
template<typename T >
const T & as () const
OptionDetails (const String &desc, std::shared_ptr< const Value > val)
const String & description () const
bool has_arg () const
void parse (const std::string &text)
void parse_default () const
int count () const
const Value & value () const
template<typename T >
const T & as () const
Private Attributes
String m_desc
std::shared_ptr< const Value > m_value
int m_count
Detailed Description
Definition at line 581 of file cxxopts.h.
Constructor & Destructor Documentation
OptionDetails() [1/2]
cxxopts::OptionDetails::OptionDetails (const String & desc, std::shared_ptr< const Value > val) inline
Definition at line 585 of file cxxopts.h.
             : m_desc(desc)
             , m_value(val)
             , m_count(0)
         {
         }
OptionDetails() [2/2]
cxxopts::OptionDetails::OptionDetails (const String & desc, std::shared_ptr< const Value > val) inline
Definition at line 585 of file cxxopts.h.
             : m_desc(desc)
             , m_value(val)
             , m_count(0)
         {
         }
Member Function Documentation
as() [1/2]
template<typename T > const T& cxxopts::OptionDetails::as () const inline
Definition at line 631 of file cxxopts.h.
References cxxopts::values::standard_value< T >::get().
         {
 #ifdef CXXOPTS_NO_RTTI
             return static_cast<const values::standard_value<T>&>(*m_value).get();
 #else
             return dynamic_cast<const values::standard_value<T>&>(*m_value).get();
 #endif
         }
as() [2/2]
template<typename T > const T& cxxopts::OptionDetails::as () const inline
Definition at line 631 of file cxxopts.h.
References cxxopts::values::standard_value< T >::get(), and bnssassembler::name().
         {
 #ifdef CXXOPTS_NO_RTTI
             return static_cast<const values::standard_value<T>&>(*m_value).get();
 #else
             return dynamic_cast<const values::standard_value<T>&>(*m_value).get();
 #endif
         }
count() [1/2]
int cxxopts::OptionDetails::count () const inline
Definition at line 620 of file cxxopts.h.
         {
             return m_count;
         }
count() [2/2]
int cxxopts::OptionDetails::count () const inline
Definition at line 620 of file cxxopts.h.
         {
             return m_count;
         }
description() [1/2]
const String& cxxopts::OptionDetails::description () const inline
Definition at line 596 of file cxxopts.h.
         {
             return m_desc;
         }
description() [2/2]
const String& cxxopts::OptionDetails::description () const inline
Definition at line 596 of file cxxopts.h.
         {
             return m_desc;
         }
has_arg() [1/2]
bool cxxopts::OptionDetails::has_arg () const inline
Definition at line 602 of file cxxopts.h.
         {
             return m_value->has_arg();
         }
has_arg() [2/2]
bool cxxopts::OptionDetails::has_arg () const inline
Definition at line 602 of file cxxopts.h.
         {
             return m_value->has_arg();
         }
parse() [1/2]
void cxxopts::OptionDetails::parse (const std::string & text) inline
Definition at line 608 of file cxxopts.h.
         {
             m_value->parse(text);
             ++m_count;
         }
parse() [2/2]
void cxxopts::OptionDetails::parse (const std::string & text) inline
Definition at line 608 of file cxxopts.h.
         {
             m_value->parse(text);
             ++m_count;
         }
parse_default() [1/2]
void cxxopts::OptionDetails::parse_default () const inline
Definition at line 615 of file cxxopts.h.
{
             m_value->parse();
         }
parse_default() [2/2]
void cxxopts::OptionDetails::parse_default () const inline
Definition at line 615 of file cxxopts.h.
{
             m_value->parse();
         }
value() [1/2]
const Value& cxxopts::OptionDetails::value () const inline
Definition at line 625 of file cxxopts.h.
{
             return *m_value;
         }
value() [2/2]
const Value& cxxopts::OptionDetails::value () const inline
Definition at line 625 of file cxxopts.h.
{
             return *m_value;
         }
Member Data Documentation
m_count
int cxxopts::OptionDetails::m_count private
Definition at line 643 of file cxxopts.h.
m_desc
String cxxopts::OptionDetails::m_desc private
Definition at line 641 of file cxxopts.h.
m_value
std::shared_ptr< const Value > cxxopts::OptionDetails::m_value private
Definition at line 642 of file cxxopts.h.
The documentation for this class was generated from the following file:
Code/Assembler/Include/cxxopts.h