AssemblerEmulator - Nikola Bebic: bnssassembler::ExpressionTokenFactory Class Reference
bnssassembler::ExpressionTokenFactory Class Reference final
Utility class used for creating the ExpressionToken objects.
#include <ExpressionTokenFactory.h>
Classes
struct ExpressionTokenFactoryData
Static Public Member Functions
static std::shared_ptr< ExpressionToken > create (std::string param)
Creates an expression token using the provided string.
Private Member Functions
ExpressionTokenFactory ()=delete
ExpressionTokenFactory (ExpressionTokenFactory &)=delete
void operator= (ExpressionTokenFactory &)=delete
Static Private Member Functions
static ExpressionTokenFactoryData & staticData () noexcept
Detailed Description
Utility class used for creating the ExpressionToken objects.
Definition at line 12 of file ExpressionTokenFactory.h.
Constructor & Destructor Documentation
ExpressionTokenFactory() [1/2]
bnssassembler::ExpressionTokenFactory::ExpressionTokenFactory () private delete
ExpressionTokenFactory() [2/2]
bnssassembler::ExpressionTokenFactory::ExpressionTokenFactory (ExpressionTokenFactory &) private delete
Member Function Documentation
create()
std::shared_ptr< ExpressionToken > bnssassembler::ExpressionTokenFactory::create (std::string param) static
Creates an expression token using the provided string.
Parameters
param String used for token creation
Returns
Pointer to the created token
Definition at line 16 of file ExpressionTokenFactory.cpp.
References bnssassembler::LITERAL_REGEX, bnssassembler::ExpressionTokenFactory::ExpressionTokenFactoryData::literals_, bnssassembler::OPERATOR_REGEX, bnssassembler::ExpressionTokenFactory::ExpressionTokenFactoryData::operators_, staticData(), bnssassembler::SYMBOL_REGEX, and bnssassembler::ExpressionTokenFactory::ExpressionTokenFactoryData::symbols_.
Referenced by bnssassembler::infixToPostfix().
{
         if (regex_match(param, LITERAL_REGEX)) {
             return staticData().literals_->clone(param);
         }
         if (regex_match(param, OPERATOR_REGEX)) {
             return staticData().operators_[param]->clone(param);
         }
         if (regex_match(param, SYMBOL_REGEX)) {
             return staticData().symbols_->clone(param);
         }
         throw MessageException("Invalid expression token: " + param);
     }
operator=()
void bnssassembler::ExpressionTokenFactory::operator= (ExpressionTokenFactory &) private delete
staticData()
ExpressionTokenFactory::ExpressionTokenFactoryData & bnssassembler::ExpressionTokenFactory::staticData () static private noexcept
Definition at line 32 of file ExpressionTokenFactory.cpp.
Referenced by create().
{
         static ExpressionTokenFactoryData static_data;
         return static_data;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/ExpressionTokenFactory.h
Code/Assembler/Source/ExpressionTokenFactory.cpp