AssemblerEmulator - Nikola Bebic: bnssemulator::LoadExecuter Class Reference
bnssemulator::LoadExecuter Class Reference
Class representing the executer for the load instruction.
#include <LoadExecuter.h>
Public Member Functions
void execute (InstructionBitField instruction, Context &context) const override
Executes the instruction.
Public Member Functions inherited from bnssemulator::Executer
virtual ~Executer ()=default
Detailed Description
Class representing the executer for the load instruction.
Definition at line 10 of file LoadExecuter.h.
Member Function Documentation
execute()
void bnssemulator::LoadExecuter::execute (InstructionBitField instruction, Context & context) const override virtual
Executes the instruction.
Parameters
instruction Instruction
context Processor context
Implements bnssemulator::Executer.
Definition at line 42 of file LoadExecuter.cpp.
References bnssemulator::fill(), bnssemulator::Context::getOperand(), bnssemulator::Context::getRegister(), bnssemulator::InstructionBitField::register0, bnssemulator::REGULAR_DOUBLE_WORD, bnssemulator::SIGNED_WORD, bnssemulator::InstructionBitField::type, bnssemulator::UNSIGNED_WORD, and bnssemulator::Register::value().
{
         auto num_of_bytes = instruction.type == REGULAR_DOUBLE_WORD ? 4 : instruction.type == UNSIGNED_WORD || instruction.type == SIGNED_WORD ? 2 : 1;
         auto operand = context.getOperand(instruction, 1, num_of_bytes);
         auto &reg = context.getRegister(instruction.register0);
         reg.value(fill(static_cast<OperandType>(instruction.type), operand));
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/LoadExecuter.h
Code/Emulator/Source/LoadExecuter.cpp