AssemblerEmulator - Nikola Bebic: bnssassembler::LiteralToken Class Reference
bnssassembler::LiteralToken Class Reference
Token class representing a math literal value.
#include <LiteralToken.h>
Public Member Functions
LiteralToken (std::string value)
int inputPriority () const noexcept override
Gets the input priority of the token.
int stackPriority () const noexcept override
Gets the stack priority of the token.
int rank () const noexcept override
Gets the rank of the token.
void process (std::list< std::shared_ptr< ExpressionToken >> &output, std::stack< std::shared_ptr< ExpressionToken >> &stack, int &expression_rank) const override
Processes the current token.
std::shared_ptr< Expression > create () const override
Creates an expression object out of the token.
Public Member Functions inherited from bnssassembler::ExpressionToken
virtual ~ExpressionToken ()=default
Protected Member Functions
std::shared_ptr< ExpressionToken > clone (std::string param) const override
Clones the current object, using the string provided.
Protected Member Functions inherited from bnssassembler::ExpressionToken
ExpressionToken ()=default
Private Attributes
int32_t value_
Detailed Description
Token class representing a math literal value.
Definition at line 10 of file LiteralToken.h.
Constructor & Destructor Documentation
LiteralToken()
bnssassembler::LiteralToken::LiteralToken (std::string value) explicit
Definition at line 8 of file LiteralToken.cpp.
References cxxopts::value(), and value_.
{
         value_ = StringHelper::parseNumber<int32_t>(value);
     }
Member Function Documentation
clone()
std::shared_ptr< ExpressionToken > bnssassembler::LiteralToken::clone (std::string param) const override protected virtual
Clones the current object, using the string provided.
Parameters
param String that will be used to construct the new object
Returns
Pointer to the cloned object
Implements bnssassembler::ExpressionToken.
Definition at line 21 of file LiteralToken.cpp.
{
         return std::make_shared<LiteralToken>(param);
     }
create()
std::shared_ptr< Expression > bnssassembler::LiteralToken::create () const override virtual
Creates an expression object out of the token.
Returns
Pointer to the expression
Exceptions
Throws if the token has no corresponding expression object
Implements bnssassembler::ExpressionToken.
Definition at line 17 of file LiteralToken.cpp.
References value_.
{
         return std::make_shared<Literal>(value_);
     }
inputPriority()
int bnssassembler::LiteralToken::inputPriority () const override virtual noexcept
Gets the input priority of the token.
Returns
Input priority of the token
Implements bnssassembler::ExpressionToken.
Definition at line 25 of file LiteralToken.cpp.
{
         return INT_MAX;
     }
process()
void bnssassembler::LiteralToken::process (std::list< std::shared_ptr< ExpressionToken >> & output, std::stack< std::shared_ptr< ExpressionToken >> & stack, int & expression_rank) const override virtual
Processes the current token.
Parameters
output Output list of tokens
stack Helper stack of tokens
expression_rank Rank of the expression
Implements bnssassembler::ExpressionToken.
Definition at line 12 of file LiteralToken.cpp.
References rank().
{
         output.push_back(std::make_shared<LiteralToken>(*this));
         expression_rank += rank();
     }
rank()
int bnssassembler::LiteralToken::rank () const override virtual noexcept
Gets the rank of the token.
Returns
Rank of the token
Implements bnssassembler::ExpressionToken.
Definition at line 33 of file LiteralToken.cpp.
Referenced by process().
{
         return 1;
     }
stackPriority()
int bnssassembler::LiteralToken::stackPriority () const override virtual noexcept
Gets the stack priority of the token.
Returns
Stack priority of the token
Implements bnssassembler::ExpressionToken.
Definition at line 29 of file LiteralToken.cpp.
{
         return INT_MAX;
     }
Member Data Documentation
value_
int32_t bnssassembler::LiteralToken::value_ private
Definition at line 23 of file LiteralToken.h.
Referenced by create(), and LiteralToken().
The documentation for this class was generated from the following files:
Code/Assembler/Include/LiteralToken.h
Code/Assembler/Source/LiteralToken.cpp