AssemblerEmulator - Nikola Bebic: bnssemulator::AddressSpace Class Reference
bnssemulator::AddressSpace Class Reference
Class representing the address space of the emulator.
#include <AddressSpace.h>
Public Member Functions
AddressSpace (std::vector< SectionData > &&section_table, const std::unordered_map< std::string, SymbolData > symbol_table)
Constructs an address space from the section table.
InstructionBitField getInstruction (uint32_t address) const
Gets the instruction at the specified address.
int32_t getSecondWordOfInstruction (uint32_t address) const
Gets the second word of the instruction at the specified address.
uint8_t get8bitData (uint32_t address) const
Gets 8 bits of data at the specified address.
uint16_t get16bitData (uint32_t address) const
Gets 16 bits of data at the specified address.
uint32_t get32bitData (uint32_t address) const
Gets 32 bits of data at the specified address.
void set8bitData (uint32_t address, uint8_t data)
Sets 8 bits of data at the specified address.
void set16bitData (uint32_t address, uint16_t data)
Sets 16 bits of data at the specified address.
void set32bitData (uint32_t address, uint32_t data)
Sets 32 bits of data at the specified address.
uint32_t initialStackPointer () const
Gets the initial value of the stack pointer.
size_t errorInterrupt () const noexcept
Gets the entry of the error interrupt routine.
size_t timerInterrupt () const noexcept
Gets the entry of the timer interrupt routine.
size_t keyboardInterrupt () const noexcept
Gets the entry of the keyboard interrupt routine.
uint32_t getInterrupt (uint32_t entry) const noexcept
Gets the address of the interrupt routine at the specified entry.
bool stdinRead () const noexcept
Check whether the standard input has been read.
void writeToStdin (char character) noexcept
Writes a character to stdin.
Private Member Functions
Segment & segment (uint32_t address)
const Segment & segment (uint32_t address) const
Private Attributes
uint32_t stdout_address_ = 128
uint32_t stdin_address_ = 132
size_t error_interrupt_ = 3
size_t timer_interrupt_ = 4
size_t keyboard_interrupt_ = 5
bool stdin_read_ = true
Detailed Description
Class representing the address space of the emulator.
Definition at line 16 of file AddressSpace.h.
Constructor & Destructor Documentation
AddressSpace()
bnssemulator::AddressSpace::AddressSpace (std::vector< SectionData > && section_table, const std::unordered_map< std::string, SymbolData > symbol_table) explicit
Constructs an address space from the section table.
Parameters
section_table Section table
symbol_table Symbol table
Definition at line 101 of file AddressSpace.cpp.
References bnssemulator::checkOverlaps(), bnssemulator::generateAddresses(), bnssemulator::getAvailable(), and bnssemulator::removeEmpty().
{
         removeEmpty(section_table);
         if (checkOverlaps(section_table)) {
             throw MessageException("Sections are overlapping");
         }
         auto available = getAvailable(section_table);
         generateAddresses(section_table, available);
         for (auto &section : section_table) {
             insert(make_pair(section.address(), Segment(section.address(), section.size(), section.type(), move(section.data()))));
         }
         for (auto &section : section_table) {
             for (auto &relocation_entry : section.relocations()) {
                 uint32_t relocation;
                 if (relocation_entry.section()) {
                     relocation = section_table.at(relocation_entry.sectionIndex()).address();
                 }
                 else {
                     auto &symbol = symbol_table.at(relocation_entry.symbolName());
                     relocation = section_table.at(symbol.sectionIndex()).address() + symbol.offset();
                 }
                 if (!relocation_entry.absolute()) {
                     relocation -= section.address() + relocation_entry.offset();
                 }
                 at(section.address()).relocate(section.address() + relocation_entry.offset(), relocation);
             }
         }
     }
Member Function Documentation
errorInterrupt()
size_t bnssemulator::AddressSpace::errorInterrupt () const noexcept
Gets the entry of the error interrupt routine.
Returns
Entry of the error interrupt routine
Definition at line 189 of file AddressSpace.cpp.
References error_interrupt_.
Referenced by bnssemulator::Context::jumpToErrorInterrupt().
{
         return error_interrupt_;
     }
get16bitData()
uint16_t bnssemulator::AddressSpace::get16bitData (uint32_t address) const
Gets 16 bits of data at the specified address.
Parameters
address Address
Returns
Data
Definition at line 152 of file AddressSpace.cpp.
References get8bitData().
Referenced by get32bitData(), and bnssemulator::Context::getOperand().
{
         return get8bitData(address) | (static_cast<uint16_t>(get8bitData(address + 1)) << 8);
     }
get32bitData()
uint32_t bnssemulator::AddressSpace::get32bitData (uint32_t address) const
Gets 32 bits of data at the specified address.
Parameters
address Address
Returns
Data
Definition at line 156 of file AddressSpace.cpp.
References get16bitData().
Referenced by getInterrupt(), bnssemulator::Context::getOperand(), initialStackPointer(), and bnssemulator::Context::popFromStack().
{
         return get16bitData(address) | (static_cast<uint32_t>(get16bitData(address + 2)) << 16);
     }
get8bitData()
uint8_t bnssemulator::AddressSpace::get8bitData (uint32_t address) const
Gets 8 bits of data at the specified address.
Parameters
address Address
Returns
Data
Definition at line 144 of file AddressSpace.cpp.
References bnssemulator::Segment::readData(), segment(), stdin_address_, and stdin_read_.
Referenced by get16bitData(), and bnssemulator::Context::getOperand().
{
         if (address == stdin_address_) {
             stdin_read_ = true;
         }
         return segment(address).readData(address);
     }
getInstruction()
InstructionBitField bnssemulator::AddressSpace::getInstruction (uint32_t address) const
Gets the instruction at the specified address.
Parameters
address Address
Returns
Instruction
Definition at line 136 of file AddressSpace.cpp.
References bnssemulator::Segment::getInstruction(), and segment().
Referenced by bnssemulator::Context::getInstruction().
{
         return segment(address).getInstruction(address);
     }
getInterrupt()
uint32_t bnssemulator::AddressSpace::getInterrupt (uint32_t entry) const noexcept
Gets the address of the interrupt routine at the specified entry.
Parameters
entry Entry
Returns
Address of the interrupt routine
Definition at line 201 of file AddressSpace.cpp.
References get32bitData().
Referenced by bnssemulator::Context::jumpToInterrupt().
{
         try {
             return get32bitData(entry * 4);
         }
         catch (...) {
             return 0;
         }
     }
getSecondWordOfInstruction()
int32_t bnssemulator::AddressSpace::getSecondWordOfInstruction (uint32_t address) const
Gets the second word of the instruction at the specified address.
Parameters
address Address
Returns
Second word of the instruction
Definition at line 140 of file AddressSpace.cpp.
References bnssemulator::Segment::getSecondWordOfInstruction(), and segment().
Referenced by bnssemulator::Context::getSecondWordOfInstruction().
{
         return segment(address).getSecondWordOfInstruction(address);
     }
initialStackPointer()
uint32_t bnssemulator::AddressSpace::initialStackPointer () const
Gets the initial value of the stack pointer.
Returns
Initial value of the stack pointer
Exceptions
Throws if the initial value of the stack pointer is not defined
Definition at line 180 of file AddressSpace.cpp.
References get32bitData().
Referenced by bnssemulator::Context::Context().
{
         try {
             return get32bitData(0);
         }
         catch (...) {
             throw MessageException("Initial stack pointer value is not defined");
         }
     }
keyboardInterrupt()
size_t bnssemulator::AddressSpace::keyboardInterrupt () const noexcept
Gets the entry of the keyboard interrupt routine.
Returns
Entry of the keyboard interrupt routine
Definition at line 197 of file AddressSpace.cpp.
References keyboard_interrupt_.
Referenced by bnssemulator::Context::jumpToKeyboardInterrupt().
{
         return keyboard_interrupt_;
     }
segment() [1/2]
Segment & bnssemulator::AddressSpace::segment (uint32_t address) private
Definition at line 218 of file AddressSpace.cpp.
References bnssemulator::StringHelper::toHexString().
Referenced by get8bitData(), getInstruction(), getSecondWordOfInstruction(), segment(), and set8bitData().
{
         auto upper = upper_bound(address);
         if (upper == begin()) {
             throw std::runtime_error("The address " + StringHelper::toHexString(address) + " is out of emulated scope");
         }
         --upper;
         return upper->second;
     }
segment() [2/2]
const Segment & bnssemulator::AddressSpace::segment (uint32_t address) const private
Definition at line 228 of file AddressSpace.cpp.
References segment().
{
         return const_cast<AddressSpace &>(*this).segment(address);
     }
set16bitData()
void bnssemulator::AddressSpace::set16bitData (uint32_t address, uint16_t data)
Sets 16 bits of data at the specified address.
Parameters
address Address
data Data
Definition at line 170 of file AddressSpace.cpp.
References set8bitData().
Referenced by bnssemulator::StoreExecuter::execute(), and set32bitData().
{
         set8bitData(address, static_cast<uint8_t>(data & 0x00ff));
         set8bitData(address + 1, static_cast<uint8_t>((data & 0xff00) >> 8));
     }
set32bitData()
void bnssemulator::AddressSpace::set32bitData (uint32_t address, uint32_t data)
Sets 32 bits of data at the specified address.
Parameters
address Address
data Data
Definition at line 175 of file AddressSpace.cpp.
References set16bitData().
Referenced by bnssemulator::StoreExecuter::execute(), and bnssemulator::Context::pushToStack().
{
         set16bitData(address, static_cast<uint16_t>(data & 0x0000ffff));
         set16bitData(address + 2, static_cast<uint16_t>((data & 0xffff0000) >> 16));
     }
set8bitData()
void bnssemulator::AddressSpace::set8bitData (uint32_t address, uint8_t data)
Sets 8 bits of data at the specified address.
Parameters
address Address
data Data
Definition at line 160 of file AddressSpace.cpp.
References segment(), stdin_address_, stdin_read_, stdout_address_, and bnssemulator::Segment::writeData().
Referenced by bnssemulator::StoreExecuter::execute(), set16bitData(), and writeToStdin().
{
         segment(address).writeData(address, data);
         if (address == stdout_address_) {
             std::cout << data;
         }
         else if (address == stdin_address_) {
             stdin_read_ = false;
         }
     }
stdinRead()
bool bnssemulator::AddressSpace::stdinRead () const noexcept
Check whether the standard input has been read.
Returns
Whether the standard input has been read
Definition at line 210 of file AddressSpace.cpp.
References stdin_read_.
{
         return stdin_read_;
     }
timerInterrupt()
size_t bnssemulator::AddressSpace::timerInterrupt () const noexcept
Gets the entry of the timer interrupt routine.
Returns
Entry of the timer interrupt routine
Definition at line 193 of file AddressSpace.cpp.
References timer_interrupt_.
Referenced by bnssemulator::Context::jumpToTimerInterrupt().
{
         return timer_interrupt_;
     }
writeToStdin()
void bnssemulator::AddressSpace::writeToStdin (char character) noexcept
Writes a character to stdin.
Definition at line 214 of file AddressSpace.cpp.
References set8bitData(), and stdin_address_.
Referenced by bnssemulator::Context::jumpToKeyboardInterrupt().
{
         set8bitData(stdin_address_, character);
     }
Member Data Documentation
error_interrupt_
size_t bnssemulator::AddressSpace::error_interrupt_ = 3 private
Definition at line 130 of file AddressSpace.h.
Referenced by errorInterrupt().
keyboard_interrupt_
size_t bnssemulator::AddressSpace::keyboard_interrupt_ = 5 private
Definition at line 132 of file AddressSpace.h.
Referenced by keyboardInterrupt().
stdin_address_
uint32_t bnssemulator::AddressSpace::stdin_address_ = 132 private
Definition at line 128 of file AddressSpace.h.
Referenced by get8bitData(), set8bitData(), and writeToStdin().
stdin_read_
bool bnssemulator::AddressSpace::stdin_read_ = true mutable private
Definition at line 134 of file AddressSpace.h.
Referenced by get8bitData(), set8bitData(), and stdinRead().
stdout_address_
uint32_t bnssemulator::AddressSpace::stdout_address_ = 128 private
Definition at line 127 of file AddressSpace.h.
Referenced by set8bitData().
timer_interrupt_
size_t bnssemulator::AddressSpace::timer_interrupt_ = 4 private
Definition at line 131 of file AddressSpace.h.
Referenced by timerInterrupt().
The documentation for this class was generated from the following files:
Code/Emulator/Include/AddressSpace.h
Code/Emulator/Source/AddressSpace.cpp