AssemblerEmulator - Nikola Bebic: bnssassembler::RegisterParser Class Reference
bnssassembler::RegisterParser Class Reference final
Utility class used for parsing registers.
#include <RegisterParser.h>
Classes
struct RegisterParserStaticData
Static Public Member Functions
static Register parse (std::string str)
Parses the register.
Private Member Functions
RegisterParser ()=delete
RegisterParser (RegisterParser &)=delete
void operator= (RegisterParser &)=delete
Static Private Member Functions
static RegisterParserStaticData & staticData () noexcept
Detailed Description
Utility class used for parsing registers.
Definition at line 11 of file RegisterParser.h.
Constructor & Destructor Documentation
RegisterParser() [1/2]
bnssassembler::RegisterParser::RegisterParser () private delete
RegisterParser() [2/2]
bnssassembler::RegisterParser::RegisterParser (RegisterParser &) private delete
Member Function Documentation
operator=()
void bnssassembler::RegisterParser::operator= (RegisterParser &) private delete
parse()
Register bnssassembler::RegisterParser::parse (std::string str) static
Parses the register.
Parameters
str String representing the register
Returns
Register
Exceptions
Throws if the register is not valid
Definition at line 8 of file RegisterParser.cpp.
References bnssassembler::RegisterParser::RegisterParserStaticData::map, and staticData().
Referenced by bnssassembler::RegisterDirectParser::parse(), bnssassembler::RegisterIndirectParser::parse(), and bnssassembler::RegisterIndirectOffsetParser::parse().
{
         static std::regex regex("[[:space:]]*([a-z0-9]*)[[:space:]]*");
         transform(str.begin(), str.end(), str.begin(), tolower);
         if (!regex_match(str, regex)) {
             throw MessageException("Invalid register: " + str);
         }
         str = regex_replace(str, regex, "$1");
         if (staticData().map.count(str) == 0) {
             throw MessageException("Invalid register: " + str);
         }
         return staticData().map[str];
     }
staticData()
RegisterParser::RegisterParserStaticData & bnssassembler::RegisterParser::staticData () static private noexcept
Definition at line 25 of file RegisterParser.cpp.
Referenced by parse().
{
         static RegisterParserStaticData static_data;
         return static_data;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/RegisterParser.h
Code/Assembler/Source/RegisterParser.cpp