AssemblerEmulator - Nikola Bebic: bnssassembler::MemoryDirect Class Reference
bnssassembler::MemoryDirect Class Reference
Class representing the memory direct operand.
#include <MemoryDirect.h>
Public Member Functions
MemoryDirect (MicroRiscExpression address) noexcept
Constructs a MemoryDirect object.
void packToInstruction (InstructionBitFieldUnion &instruction, uint32_t &second_word, std::list< RelocationRecord > &relocations) const override
Packs the operand into the instruction.
void resolveSymbols (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves the defined symbols in the expressions.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
AddressMode addressMode () const noexcept override
Gets the address mode of the operand.
Public Member Functions inherited from bnssassembler::Operand
virtual ~Operand ()=default
Private Attributes
MicroRiscExpression address_
Detailed Description
Class representing the memory direct operand.
Definition at line 11 of file MemoryDirect.h.
Constructor & Destructor Documentation
MemoryDirect()
bnssassembler::MemoryDirect::MemoryDirect (MicroRiscExpression address) explicit noexcept
Constructs a MemoryDirect object.
Parameters
address Address of the memory direct operand
Definition at line 5 of file MemoryDirect.cpp.
 : address_(address) {}
Member Function Documentation
addressMode()
AddressMode bnssassembler::MemoryDirect::addressMode () const override virtual noexcept
Gets the address mode of the operand.
Returns
Address mode of the operand
Implements bnssassembler::Operand.
Definition at line 31 of file MemoryDirect.cpp.
References bnssassembler::MEMORY_DIRECT.
{
         return MEMORY_DIRECT;
     }
packToInstruction()
void bnssassembler::MemoryDirect::packToInstruction (InstructionBitFieldUnion & instruction, uint32_t & second_word, std::list< RelocationRecord > & relocations) const override virtual
Packs the operand into the instruction.
Parameters
instruction Reference to the first word of the instruction containing the instruction info
second_word Reference to the second word of the instruction containing the address/value/displacement
relocations Reference to the list of relocation records
Implements bnssassembler::Operand.
Definition at line 7 of file MemoryDirect.cpp.
References address_, bnssassembler::InstructionBitField::address_mode, bnssassembler::InstructionBitFieldUnion::bit_field, bnssassembler::MicroRiscExpression::generateRelocations(), bnssassembler::MEMORY_DIRECT, and bnssassembler::MicroRiscExpression::value().
{
         instruction.bit_field.address_mode = MEMORY_DIRECT;
         second_word = address_.value();
         relocations.splice(relocations.end(), address_.generateRelocations());
     }
resolveCurrentPcSymbol()
void bnssassembler::MemoryDirect::resolveCurrentPcSymbol (size_t section_index, size_t offset) override virtual noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Reimplemented from bnssassembler::Operand.
Definition at line 27 of file MemoryDirect.cpp.
References address_, and bnssassembler::MicroRiscExpression::resolveCurrentPcSymbol().
{
         address_.resolveCurrentPcSymbol(section_index, offset);
     }
resolveImports()
void bnssassembler::MemoryDirect::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates the relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Operand.
Definition at line 23 of file MemoryDirect.cpp.
References address_, and bnssassembler::MicroRiscExpression::resolveImports().
{
         address_.resolveImports(imported_symbols);
     }
resolveSymbols()
void bnssassembler::MemoryDirect::resolveSymbols (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves the defined symbols in the expressions.
Parameters
symbols Collection of symbol definitions
Reimplemented from bnssassembler::Operand.
Definition at line 13 of file MemoryDirect.cpp.
References address_, and bnssassembler::MicroRiscExpression::setValue().
{
         for (auto &symbol : symbols) {
             address_.setValue(symbol.name(), symbol.expression());
         }
     }
resolveSymbolTable()
void bnssassembler::MemoryDirect::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates the relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Operand.
Definition at line 19 of file MemoryDirect.cpp.
References address_, and bnssassembler::MicroRiscExpression::resolveSymbolTable().
{
         address_.resolveSymbolTable(symbol_table);
     }
Member Data Documentation
address_
MicroRiscExpression bnssassembler::MemoryDirect::address_ private
Definition at line 26 of file MemoryDirect.h.
Referenced by packToInstruction(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbols(), and resolveSymbolTable().
The documentation for this class was generated from the following files:
Code/Assembler/Include/MemoryDirect.h
Code/Assembler/Source/MemoryDirect.cpp