AssemblerEmulator - Nikola Bebic: bnssemulator::Segment Class Reference
bnssemulator::Segment Class Reference
Class representing one segment of memory.
#include <Segment.h>
Public Member Functions
Segment (uint32_t address, size_t length, SectionType type, vector< uint8_t > &&data)
Constructs a segment.
InstructionBitField getInstruction (uint32_t address) const
Gets the instruction at the specified address.
int32_t getSecondWordOfInstruction (uint32_t address) const
Gets the second word of the instruction at the specified address.
uint8_t readData (uint32_t address) const
Reads a byte of data at the specified address.
void writeData (uint32_t address, uint8_t data)
Writes a byte of data at the specified address.
void relocate (uint32_t address, uint32_t relocation)
Fixes the value at the address by a relocation.
Private Attributes
uint32_t address_
size_t length_
SectionType type_
Detailed Description
Class representing one segment of memory.
Definition at line 13 of file Segment.h.
Constructor & Destructor Documentation
Segment()
bnssemulator::Segment::Segment (uint32_t address, size_t length, SectionType type, vector< uint8_t > && data)
Constructs a segment.
Parameters
address Starting address of the segment
length Length of the segment
type Type of the segment
data Data contained in the segment
Definition at line 8 of file Segment.cpp.
                                                                                               : vector(move(data)), address_(address), length_(length), type_(type) {
         if (size() == 0) {
             resize(length);
         }
     }
Member Function Documentation
getInstruction()
InstructionBitField bnssemulator::Segment::getInstruction (uint32_t address) const
Gets the instruction at the specified address.
Parameters
address Address
Returns
Instruction
Definition at line 14 of file Segment.cpp.
References address_, bnssemulator::InstructionBitFieldUnion::bit_field, bnssemulator::InstructionBitFieldUnion::data, length_, bnssemulator::TEXT, bnssemulator::StringHelper::toHexString(), and type_.
Referenced by bnssemulator::AddressSpace::getInstruction().
{
         if (type_ != TEXT) {
             throw MessageException("No execute permission at address " + StringHelper::toHexString(address));
         }
         if (address < address_ || address + 4 > address_ + length_) {
             throw MessageException("Address " + StringHelper::toHexString(address) + " is out of range");
         }
         auto offset = address - address_;
         InstructionBitFieldUnion ret;
         ret.data = 0;
         ret.data |= (*this)[offset];
         ret.data |= (*this)[offset + 1] << 8;
         ret.data |= (*this)[offset + 2] << 16;
         ret.data |= (*this)[offset + 3] << 24;
         return ret.bit_field;
     }
getSecondWordOfInstruction()
int32_t bnssemulator::Segment::getSecondWordOfInstruction (uint32_t address) const
Gets the second word of the instruction at the specified address.
Parameters
address Address
Returns
Second word of the instruction
Definition at line 35 of file Segment.cpp.
References address_, length_, bnssemulator::TEXT, bnssemulator::StringHelper::toHexString(), and type_.
Referenced by bnssemulator::AddressSpace::getSecondWordOfInstruction().
{
         if (type_ != TEXT) {
             throw MessageException("No execute permission at address " + StringHelper::toHexString(address));
         }
         if (address < address_ || address + 4 > address_ + length_) {
             throw MessageException("Address " + StringHelper::toHexString(address) + " is out of range");
         }
         auto offset = address - address_;
         // ReSharper disable once CppUseAuto
         int32_t ret = 0;
         ret |= (*this)[offset];
         ret |= (*this)[offset + 1] << 8;
         ret |= (*this)[offset + 2] << 16;
         ret |= (*this)[offset + 3] << 24;
         return ret;
     }
readData()
uint8_t bnssemulator::Segment::readData (uint32_t address) const
Reads a byte of data at the specified address.
Parameters
address Address
Returns
Byte of read data
Definition at line 56 of file Segment.cpp.
References address_, length_, and bnssemulator::StringHelper::toHexString().
Referenced by bnssemulator::AddressSpace::get8bitData().
{
         if (address < address_ || address > address_ + length_) {
             throw MessageException("Address " + StringHelper::toHexString(address) + " is out of range");
         }
         auto offset = address - address_;
         return (*this)[offset];
     }
relocate()
void bnssemulator::Segment::relocate (uint32_t address, uint32_t relocation)
Fixes the value at the address by a relocation.
Parameters
address Address
relocation Value to be added to the value at the address
Definition at line 78 of file Segment.cpp.
References address_, length_, and bnssemulator::StringHelper::toHexString().
{
         if (address < address_ || address + 4 > address_ + length_) {
             throw MessageException("Address " + StringHelper::toHexString(address) + " is out of range");
         }
         auto offset = address - address_;
         uint32_t data = 0;
         data |= (*this)[offset];
         data |= (*this)[offset + 1] << 8;
         data |= (*this)[offset + 2] << 16;
         data |= (*this)[offset + 3] << 24;
         data += relocation;
         (*this)[offset] = static_cast<uint8_t>(data & 0x000000ff);
         (*this)[offset + 1] = static_cast<uint8_t>((data & 0x0000ff00) >> 8);
         (*this)[offset + 2] = static_cast<uint8_t>((data & 0x00ff0000) >> 16);
         (*this)[offset + 3] = static_cast<uint8_t>((data & 0xff000000) >> 24);
     }
writeData()
void bnssemulator::Segment::writeData (uint32_t address, uint8_t data)
Writes a byte of data at the specified address.
Parameters
address Address
data Byte of data to be written
Definition at line 65 of file Segment.cpp.
References address_, bnssemulator::BSS, bnssemulator::DATA, length_, bnssemulator::StringHelper::toHexString(), and type_.
Referenced by bnssemulator::AddressSpace::set8bitData().
{
         if (type_ != DATA && type_ != BSS) {
             throw MessageException("No write permission at address " + StringHelper::toHexString(address));
         }
         if (address < address_ || address > address_ + length_) {
             throw MessageException("Address " + StringHelper::toHexString(address) + " is out of range");
         }
         auto offset = address - address_;
         (*this)[offset] = data;
     }
Member Data Documentation
address_
uint32_t bnssemulator::Segment::address_ private
Definition at line 62 of file Segment.h.
Referenced by getInstruction(), getSecondWordOfInstruction(), readData(), relocate(), and writeData().
length_
size_t bnssemulator::Segment::length_ private
Definition at line 63 of file Segment.h.
Referenced by getInstruction(), getSecondWordOfInstruction(), readData(), relocate(), and writeData().
type_
SectionType bnssemulator::Segment::type_ private
Definition at line 64 of file Segment.h.
Referenced by getInstruction(), getSecondWordOfInstruction(), and writeData().
The documentation for this class was generated from the following files:
Code/Emulator/Include/Segment.h
Code/Emulator/Source/Segment.cpp