AssemblerEmulator - Nikola Bebic: bnssemulator::Register Class Reference
bnssemulator::Register Class Reference
Class representing the register.
#include <Register.h>
Public Member Functions
Register ()=default
Constructs a Register object.
int32_t value () const noexcept
Gets the value of the register.
void value (int32_t value) noexcept
Sets the value of the register.
bool negativeFlag () const noexcept
Gets the negative flag of the register.
bool zeroFlag () const noexcept
Gets the zero flag of the register.
bool carryFlag () const noexcept
Gets the Carry flag of the register.
bool overflowFlag () const noexcept
Gets the overflow flag of the register.
Register (int32_t value) noexcept
Constructs a Register object.
Register (int32_t value, bool carry_flag, bool overflow_flag) noexcept
Constructs a Register object.
operator int32_t () const noexcept
Register operator- () const noexcept
Register operator~ () const noexcept
Register & operator+= (const Register &reg) noexcept
Register & operator-= (const Register &reg) noexcept
Register & operator*= (const Register &reg) noexcept
Register & operator/= (const Register &reg) noexcept
Register & operator%= (const Register &reg) noexcept
Register & operator &= (const Register &reg) noexcept
Register & operator|= (const Register &reg) noexcept
Register & operator^= (const Register &reg) noexcept
Register & operator<<= (const Register &reg) noexcept
Register & operator>>= (const Register &reg) noexcept
Private Attributes
int32_t value_ = 0
bool carry_flag_ = false
bool overflow_flag_ = false
Friends
Register operator+ (const Register &lhs, const Register &rhs) noexcept
Register operator- (const Register &lhs, const Register &rhs) noexcept
Register operator* (const Register &lhs, const Register &rhs) noexcept
Register operator/ (const Register &lhs, const Register &rhs) noexcept
Register operator% (const Register &lhs, const Register &rhs) noexcept
Register operator & (const Register &lhs, const Register &rhs) noexcept
Register operator| (const Register &lhs, const Register &rhs) noexcept
Register operator^ (const Register &lhs, const Register &rhs) noexcept
Register operator<< (const Register &lhs, const Register &rhs) noexcept
Register operator>> (const Register &lhs, const Register &rhs) noexcept
Detailed Description
Class representing the register.
Definition at line 10 of file Register.h.
Constructor & Destructor Documentation
Register() [1/3]
bnssemulator::Register::Register () default
Constructs a Register object.
Referenced by bnssemulator::operator &(), bnssemulator::operator%(), bnssemulator::operator*(), bnssemulator::operator+(), operator-(), bnssemulator::operator/(), bnssemulator::operator<<(), bnssemulator::operator>>(), bnssemulator::operator^(), bnssemulator::operator|(), and operator~().
Register() [2/3]
bnssemulator::Register::Register (int32_t value) noexcept
Constructs a Register object.
Parameters
value Starting value of the register
Definition at line 31 of file Register.cpp.
 : value_(value) {}
Register() [3/3]
bnssemulator::Register::Register (int32_t value, bool carry_flag, bool overflow_flag) noexcept
Constructs a Register object.
Parameters
value Starting value of the register
carry_flag Starting carry flag of the register
overflow_flag Starting overflow flag of the register
Definition at line 37 of file Register.cpp.
 : value_(value), carry_flag_(carry_flag), overflow_flag_(overflow_flag) {}
Member Function Documentation
carryFlag()
bool bnssemulator::Register::carryFlag () const noexcept
Gets the Carry flag of the register.
Returns
Carry flag
Definition at line 23 of file Register.cpp.
References carry_flag_.
{
         return carry_flag_;
     }
negativeFlag()
bool bnssemulator::Register::negativeFlag () const noexcept
Gets the negative flag of the register.
Returns
Negative flag
Definition at line 15 of file Register.cpp.
References value_.
{
         return value_ < 0;
     }
operator &=()
Register& bnssemulator::Register::operator&= (const Register & reg) noexcept
Referenced by operator%=().
operator int32_t()
bnssemulator::Register::operator int32_t () const noexcept
Definition at line 33 of file Register.cpp.
References value_.
{
         return value_;
     }
operator%=()
Register & bnssemulator::Register::operator%= (const Register & reg) noexcept
Definition at line 67 of file Register.cpp.
References operator &=().
{
         *this = *this % reg;
         return *this;
     }
operator*=()
Register & bnssemulator::Register::operator*= (const Register & reg) noexcept
Definition at line 57 of file Register.cpp.
{
         *this = *this * reg;
         return *this;
     }
operator+=()
Register & bnssemulator::Register::operator+= (const Register & reg) noexcept
Definition at line 47 of file Register.cpp.
{
         *this = *this + reg;
         return *this;
     }
operator-()
Register bnssemulator::Register::operator- () const noexcept
Definition at line 39 of file Register.cpp.
References Register(), and value_.
{
         return Register(-value_);
     }
operator-=()
Register & bnssemulator::Register::operator-= (const Register & reg) noexcept
Definition at line 52 of file Register.cpp.
{
         *this = *this - reg;
         return *this;
     }
operator/=()
Register & bnssemulator::Register::operator/= (const Register & reg) noexcept
Definition at line 62 of file Register.cpp.
{
         *this = *this / reg;
         return *this;
     }
operator<<=()
Register & bnssemulator::Register::operator<<= (const Register & reg) noexcept
Definition at line 87 of file Register.cpp.
{
         *this = *this << reg;
         return *this;
     }
operator>>=()
Register & bnssemulator::Register::operator>>= (const Register & reg) noexcept
Definition at line 92 of file Register.cpp.
{
         *this = *this >> reg;
         return *this;
     }
operator^=()
Register & bnssemulator::Register::operator^= (const Register & reg) noexcept
Definition at line 82 of file Register.cpp.
{
         *this = *this ^ reg;
         return *this;
     }
operator|=()
Register & bnssemulator::Register::operator|= (const Register & reg) noexcept
Definition at line 77 of file Register.cpp.
{
         *this = *this | reg;
         return *this;
     }
operator~()
Register bnssemulator::Register::operator~ () const noexcept
Definition at line 43 of file Register.cpp.
References Register(), and value_.
{
         return Register(~value_);
     }
overflowFlag()
bool bnssemulator::Register::overflowFlag () const noexcept
Gets the overflow flag of the register.
Returns
Overflow flag
Definition at line 27 of file Register.cpp.
References overflow_flag_.
{
         return overflow_flag_;
     }
value() [1/2]
int32_t bnssemulator::Register::value () const noexcept
Gets the value of the register.
Returns
Value of the register
Definition at line 7 of file Register.cpp.
References value_.
Referenced by bnssemulator::Context::Context(), bnssemulator::LoadExecuter::execute(), and value().
{
         return value_;
     }
value() [2/2]
void bnssemulator::Register::value (int32_t value) noexcept
Sets the value of the register.
Parameters
value Value of the register
Definition at line 11 of file Register.cpp.
References value(), and value_.
{
         value_ = value;
     }
zeroFlag()
bool bnssemulator::Register::zeroFlag () const noexcept
Gets the zero flag of the register.
Returns
Zero flag
Definition at line 19 of file Register.cpp.
References value_.
{
         return value_ == 0;
     }
Friends And Related Function Documentation
operator &
Register operator& (const Register & lhs, const Register & rhs) friend
Definition at line 131 of file Register.cpp.
{
         return Register(lhs.value_ & rhs.value_);
     }
operator%
Register operator% (const Register & lhs, const Register & rhs) friend
Definition at line 127 of file Register.cpp.
{
         return Register(lhs.value_ % rhs.value_);
     }
operator*
Register operator* (const Register & lhs, const Register & rhs) friend
Definition at line 112 of file Register.cpp.
{
         auto result_value = static_cast<int64_t>(lhs.value_) + static_cast<int64_t>(rhs.value_);
         auto left = static_cast<bool>(lhs.value_ & INT32_MIN);
         auto right = static_cast<bool>(rhs.value_ & INT32_MIN);
         auto result = static_cast<bool>(result_value & INT32_MIN);
         auto flags = ((result_value & TOP_32_BITS) != 0) || (!left && !right && result);
         return Register(static_cast<int32_t>(result_value), flags, flags);
     }
operator+
Register operator+ (const Register & lhs, const Register & rhs) friend
Definition at line 97 of file Register.cpp.
{
         auto result_value = static_cast<int64_t>(lhs.value_) + static_cast<int64_t>(rhs.value_);
         auto left = static_cast<bool>(lhs.value_ & INT32_MIN);
         auto right = static_cast<bool>(rhs.value_ & INT32_MIN);
         auto result = static_cast<bool>(result_value & INT32_MIN);
         auto flags = (left && right && !result) || (!left && !right && result);
         return Register(static_cast<int32_t>(result_value), flags, flags);
     }
operator-
Register operator- (const Register & lhs, const Register & rhs) friend
Definition at line 108 of file Register.cpp.
{
         return lhs + -rhs;
     }
operator/
Register operator/ (const Register & lhs, const Register & rhs) friend
Definition at line 123 of file Register.cpp.
{
         return Register(lhs.value_ / rhs.value_);
     }
operator<<
Register operator<< (const Register & lhs, const Register & rhs) friend
Definition at line 143 of file Register.cpp.
{
         auto shift = rhs.value_ % 32;
         auto result = lhs.value_ << shift;
         auto carry = (result & TOP_32_BITS) != 0;
         return Register(result, carry, false);
     }
operator>>
Register operator>> (const Register & lhs, const Register & rhs) friend
Definition at line 152 of file Register.cpp.
{
         auto shift = rhs.value_ % 32;
         auto result = lhs.value_ >> shift;
         auto back = result << shift;
         auto carry = lhs.value_ != back;
         return Register(result, carry, false);
     }
operator^
Register operator^ (const Register & lhs, const Register & rhs) friend
Definition at line 139 of file Register.cpp.
{
         return Register(lhs.value_ ^ rhs.value_);
     }
operator|
Register operator| (const Register & lhs, const Register & rhs) friend
Definition at line 135 of file Register.cpp.
{
         return Register(lhs.value_ | rhs.value_);
     }
Member Data Documentation
carry_flag_
bool bnssemulator::Register::carry_flag_ = false private
Definition at line 104 of file Register.h.
Referenced by carryFlag().
overflow_flag_
bool bnssemulator::Register::overflow_flag_ = false private
Definition at line 105 of file Register.h.
Referenced by overflowFlag().
value_
int32_t bnssemulator::Register::value_ = 0 private
Definition at line 102 of file Register.h.
Referenced by negativeFlag(), operator int32_t(), operator-(), bnssemulator::operator<<(), bnssemulator::operator>>(), operator~(), value(), and zeroFlag().
The documentation for this class was generated from the following files:
Code/Emulator/Include/Register.h
Code/Emulator/Source/Register.cpp