AssemblerEmulator - Nikola Bebic: bnssemulator::StoreExecuter Class Reference
bnssemulator::StoreExecuter Class Reference
Class representing the executer for the store instruction.
#include <StoreExecuter.h>
Public Member Functions
void execute (InstructionBitField instruction, Context &context) const override
Executes the instruction.
Public Member Functions inherited from bnssemulator::Executer
virtual ~Executer ()=default
Detailed Description
Class representing the executer for the store instruction.
Definition at line 10 of file StoreExecuter.h.
Member Function Documentation
execute()
void bnssemulator::StoreExecuter::execute (InstructionBitField instruction, Context & context) const override virtual
Executes the instruction.
Parameters
instruction Instruction
context Processor context
Implements bnssemulator::Executer.
Definition at line 9 of file StoreExecuter.cpp.
References bnssemulator::InstructionBitField::address_mode, bnssemulator::Context::addressSpace(), bnssemulator::Context::getOperandAddress(), bnssemulator::Context::getRegister(), bnssemulator::InstructionBitField::register0, bnssemulator::InstructionBitField::register1, bnssemulator::REGISTER_DIRECT, bnssemulator::REGULAR_BYTE, bnssemulator::REGULAR_DOUBLE_WORD, bnssemulator::REGULAR_WORD, bnssemulator::AddressSpace::set16bitData(), bnssemulator::AddressSpace::set32bitData(), bnssemulator::AddressSpace::set8bitData(), bnssemulator::StringHelper::toHexString(), and bnssemulator::InstructionBitField::type.
{
         auto &src = context.getRegister(instruction.register0);
         if (instruction.address_mode == REGISTER_DIRECT) {
             auto &dst = context.getRegister(instruction.register1);
             dst = src;
         }
         else {
             auto address = context.getOperandAddress(instruction, 1);
             switch (instruction.type) {
             case REGULAR_BYTE:
                 context.addressSpace().set8bitData(address, src);
                 break;
             case REGULAR_WORD:
                 context.addressSpace().set16bitData(address, src);
                 break;
             case REGULAR_DOUBLE_WORD:
                 context.addressSpace().set32bitData(address, src);
                 break;
             default:
                 throw MessageException("Invalid instruction type: " + StringHelper::toHexString(instruction.type));
             }
         }
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/StoreExecuter.h
Code/Emulator/Source/StoreExecuter.cpp