AssemblerEmulator - Nikola Bebic: bnssassembler::SectionTypeParser Class Reference
bnssassembler::SectionTypeParser Class Reference final
Utility class representing the parser for the section types.
#include <SectionTypeParser.h>
Classes
struct SectionTypeParserData
Static Public Member Functions
static SectionType parse (std::string type)
Parses the section type.
static std::string toString (SectionType type) noexcept
Converts a SectionType to string.
Static Private Member Functions
static SectionTypeParserData & staticData () noexcept
Detailed Description
Utility class representing the parser for the section types.
Definition at line 12 of file SectionTypeParser.h.
Member Function Documentation
parse()
SectionType bnssassembler::SectionTypeParser::parse (std::string type) static
Parses the section type.
Parameters
type String representing the section
Returns
SectionType enum
Exceptions
Throws if the section is invalid
Definition at line 6 of file SectionTypeParser.cpp.
References bnssassembler::SectionTypeParser::SectionTypeParserData::map, and staticData().
Referenced by bnssassembler::SectionStartLineParser::parse().
{
         transform(type.begin(), type.end(), type.begin(), tolower);
         if (staticData().map.count(type) == 0) {
             throw MessageException(type + " is not a valid section");
         }
         return staticData().map[type];
     }
staticData()
SectionTypeParser::SectionTypeParserData & bnssassembler::SectionTypeParser::staticData () static private noexcept
Definition at line 20 of file SectionTypeParser.cpp.
Referenced by parse(), and toString().
{
         static SectionTypeParserData static_data;
         return static_data;
     }
toString()
std::string bnssassembler::SectionTypeParser::toString (SectionType type) static noexcept
Converts a SectionType to string.
Parameters
type SectionType object
Returns
String representation of the type
Definition at line 16 of file SectionTypeParser.cpp.
References bnssassembler::SectionTypeParser::SectionTypeParserData::reverse, and staticData().
Referenced by bnssassembler::SectionTable::operator+=().
{
         return staticData().reverse[type];
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/SectionTypeParser.h
Code/Assembler/Source/SectionTypeParser.cpp