AssemblerEmulator - Nikola Bebic: bnssassembler::FirstPassData Class Reference
bnssassembler::FirstPassData Class Reference
Class representing the data that the two-pass assembler will modify in the first pass.
#include <FirstPassData.h>
Public Member Functions
void incLocationCounter (size_t offset)
Increases the location counter of the current section.
void insertSymbol (std::string symbol)
Inserts a symbol into the symbol table.
void insertSection (SectionType type)
Inserts a non-indexed section into the section table.
void insertSection (SectionType type, size_t index)
Inserts an indexed section into the section table.
void insertSymbolDefinition (SymbolDefinition symbol)
Inserts a symbol definition into the vector.
std::unordered_set< SymbolDefinition > symbolDefinitions () const noexcept
Get the symbol definitions.
Private Member Functions
void insertSection (SectionData section_data)
Inserts a section into the section table.
Private Attributes
SymbolTable symbol_table_
SectionTable section_table_
std::unordered_set< SymbolDefinition > symbol_definitions_
Friends
class SecondPassData
Detailed Description
Class representing the data that the two-pass assembler will modify in the first pass.
Definition at line 13 of file FirstPassData.h.
Member Function Documentation
incLocationCounter()
void bnssassembler::FirstPassData::incLocationCounter (size_t offset)
Increases the location counter of the current section.
Definition at line 6 of file FirstPassData.cpp.
References section_table_.
Referenced by bnssassembler::DataDefinitionToken::firstPass(), and bnssassembler::InstructionToken::firstPass().
{
         if (section_table_.empty()) {
             throw MessageException("All data must be in sections");
         }
         section_table_.back().incLocationCounter(offset);
     }
insertSection() [1/3]
void bnssassembler::FirstPassData::insertSection (SectionType type)
Inserts a non-indexed section into the section table.
Parameters
type Type of the section
Definition at line 27 of file FirstPassData.cpp.
Referenced by bnssassembler::SectionStartToken::firstPass(), and insertSection().
{
         insertSection(SectionData(type));
     }
insertSection() [2/3]
void bnssassembler::FirstPassData::insertSection (SectionType type, size_t index)
Inserts an indexed section into the section table.
Parameters
type Type of the section
index Index of the section
Definition at line 31 of file FirstPassData.cpp.
References insertSection().
{
         insertSection(SectionData(type, index));
     }
insertSection() [3/3]
void bnssassembler::FirstPassData::insertSection (SectionData section_data) private
Inserts a section into the section table.
Parameters
section_data Section data to be inserted
Definition at line 47 of file FirstPassData.cpp.
References section_table_.
{
         section_table_ += section_data;
     }
insertSymbol()
void bnssassembler::FirstPassData::insertSymbol (std::string symbol)
Inserts a symbol into the symbol table.
Definition at line 14 of file FirstPassData.cpp.
References bnssassembler::SymbolTable::contains(), section_table_, and symbol_table_.
Referenced by bnssassembler::LabelToken::firstPass().
{
         if (section_table_.empty()) {
             throw MessageException("All labels must be in sections");
         }
         if (symbol_table_.contains(symbol)) {
             throw MessageException("Symbol " + symbol + " is already defined");
         }
         SymbolData symbol_data(symbol, section_table_.size() - 1, section_table_.back().locationCounter(), true);
         symbol_table_ += symbol_data;
     }
insertSymbolDefinition()
void bnssassembler::FirstPassData::insertSymbolDefinition (SymbolDefinition symbol)
Inserts a symbol definition into the vector.
Parameters
symbol SymbolDefinition object to insert
Definition at line 35 of file FirstPassData.cpp.
References bnssassembler::SymbolDefinition::name(), and symbol_definitions_.
Referenced by bnssassembler::SymbolDefinitionToken::firstPass().
{
         if (symbol_definitions_.count(symbol) > 0) {
             throw MessageException("Symbol " + symbol.name() + " is already defined");
         }
         symbol_definitions_.insert(symbol);
     }
symbolDefinitions()
std::unordered_set< SymbolDefinition > bnssassembler::FirstPassData::symbolDefinitions () const noexcept
Get the symbol definitions.
Returns
Symbol definitions
Definition at line 43 of file FirstPassData.cpp.
References symbol_definitions_.
Referenced by bnssassembler::FirstPass::execute().
{
         return symbol_definitions_;
     }
Friends And Related Function Documentation
SecondPassData
friend class SecondPassData friend
Definition at line 50 of file FirstPassData.h.
Member Data Documentation
section_table_
SectionTable bnssassembler::FirstPassData::section_table_ private
Definition at line 53 of file FirstPassData.h.
Referenced by incLocationCounter(), insertSection(), and insertSymbol().
symbol_definitions_
std::unordered_set<SymbolDefinition> bnssassembler::FirstPassData::symbol_definitions_ private
Definition at line 54 of file FirstPassData.h.
Referenced by insertSymbolDefinition(), and symbolDefinitions().
symbol_table_
SymbolTable bnssassembler::FirstPassData::symbol_table_ private
Definition at line 52 of file FirstPassData.h.
Referenced by insertSymbol().
The documentation for this class was generated from the following files:
Code/Assembler/Include/FirstPassData.h
Code/Assembler/Source/FirstPassData.cpp