AssemblerEmulator - Nikola Bebic: bnssassembler::InstructionCodeParser Class Reference
bnssassembler::InstructionCodeParser Class Reference final
Utility class used for parsing instruction codes.
#include <InstructionCodeParser.h>
Classes
struct InstructionCodeParserStaticData
Static Public Member Functions
static InstructionCode parse (std::string str)
Parses the instruction code.
Private Member Functions
InstructionCodeParser ()=delete
InstructionCodeParser (InstructionCodeParser &)=delete
void operator= (InstructionCodeParser &)=delete
Static Private Member Functions
static InstructionCodeParserStaticData & staticData () noexcept
Detailed Description
Utility class used for parsing instruction codes.
Definition at line 11 of file InstructionCodeParser.h.
Constructor & Destructor Documentation
InstructionCodeParser() [1/2]
bnssassembler::InstructionCodeParser::InstructionCodeParser () private delete
InstructionCodeParser() [2/2]
bnssassembler::InstructionCodeParser::InstructionCodeParser (InstructionCodeParser &) private delete
Member Function Documentation
operator=()
void bnssassembler::InstructionCodeParser::operator= (InstructionCodeParser &) private delete
parse()
InstructionCode bnssassembler::InstructionCodeParser::parse (std::string str) static
Parses the instruction code.
Parameters
str String representing the instruction code
Returns
Instruction code
Exceptions
Throws if the instruction code is not valid
Definition at line 8 of file InstructionCodeParser.cpp.
References bnssassembler::InstructionCodeParser::InstructionCodeParserStaticData::map, and staticData().
Referenced by bnssassembler::InstructionLineParser::parse().
{
         transform(str.begin(), str.end(), str.begin(), tolower);
         if (staticData().map.count(str) == 0) {
             throw MessageException(str + " is not an instruction code");
         }
         return staticData().map[str];
     }
staticData()
InstructionCodeParser::InstructionCodeParserStaticData & bnssassembler::InstructionCodeParser::staticData () static private noexcept
Definition at line 18 of file InstructionCodeParser.cpp.
Referenced by parse().
{
         static InstructionCodeParserStaticData static_data;
         return static_data;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/InstructionCodeParser.h
Code/Assembler/Source/InstructionCodeParser.cpp