AssemblerEmulator - Nikola Bebic: bnssassembler::FirstPass Class Reference
bnssassembler::FirstPass Class Reference final
Class representing the executor of the first pass.
#include <FirstPass.h>
Static Public Member Functions
static FirstPassData execute (std::vector< std::shared_ptr< Token >> tokens)
Executes the first pass.
Private Member Functions
FirstPass ()=delete
FirstPass (FirstPass &)=delete
void operator= (FirstPass &)=delete
Detailed Description
Class representing the executor of the first pass.
Definition at line 11 of file FirstPass.h.
Constructor & Destructor Documentation
FirstPass() [1/2]
bnssassembler::FirstPass::FirstPass () private delete
FirstPass() [2/2]
bnssassembler::FirstPass::FirstPass (FirstPass &) private delete
Member Function Documentation
execute()
FirstPassData bnssassembler::FirstPass::execute (std::vector< std::shared_ptr< Token >> tokens) static
Executes the first pass.
Parameters
tokens Vector of parsed tokens
Returns
FirstPassData object
Definition at line 7 of file FirstPass.cpp.
References bnssassembler::MessageException::message(), and bnssassembler::FirstPassData::symbolDefinitions().
Referenced by main().
{
         FirstPassData ret;
         for (auto &token : tokens) {
             try {
                 token->resolveSymbolDefinitions(ret.symbolDefinitions());
                 token->firstPass(ret);
             }
             catch (MessageException &exception) {
                 throw FirstPassException(token->lineNumber(), token->line(), exception.message());
             }
         }
         return ret;
     }
operator=()
void bnssassembler::FirstPass::operator= (FirstPass &) private delete
The documentation for this class was generated from the following files:
Code/Assembler/Include/FirstPass.h
Code/Assembler/Source/FirstPass.cpp