AssemblerEmulator - Nikola Bebic: bnssemulator::Processor Class Reference
bnssemulator::Processor Class Reference final
Class representing the processor.
#include <Processor.h>
Classes
struct ProcessorStaticData
Static Public Member Functions
static void executeProgram (Context &context)
Executes the program using the given processor context.
Static Private Member Functions
static void executeInstruction (Context &context)
Executes one instruction of the program using the given processor context.
static ProcessorStaticData & staticData () noexcept
Detailed Description
Class representing the processor.
Definition at line 13 of file Processor.h.
Member Function Documentation
executeInstruction()
void bnssemulator::Processor::executeInstruction (Context & context) static private
Executes one instruction of the program using the given processor context.
Parameters
context Reference to the processor context
Definition at line 76 of file Processor.cpp.
References bnssemulator::Context::getInstruction(), bnssemulator::Processor::ProcessorStaticData::map, bnssemulator::opcode(), staticData(), and bnssemulator::StringHelper::toHexString().
Referenced by executeProgram().
{
         auto instruction = context.getInstruction();
         if (staticData().map.count(opcode(instruction)) == 0) {
             throw MessageException("Invalid operation code: " + StringHelper::toHexString(instruction.operation_code));
         }
         auto &executer = staticData().map.at(opcode(instruction));
         executer->execute(instruction, context);
     }
executeProgram()
void bnssemulator::Processor::executeProgram (Context & context) static
Executes the program using the given processor context.
Parameters
context Reference to the processor context
Definition at line 35 of file Processor.cpp.
References executeInstruction(), bnssemulator::Context::finishProgram(), bnssemulator::Context::hasCharacters(), bnssemulator::Context::insideInterrupt(), bnssemulator::Context::jumpToErrorInterrupt(), bnssemulator::Context::jumpToKeyboardInterrupt(), bnssemulator::Context::jumpToTimerInterrupt(), bnssemulator::TimerListener::listen(), bnssemulator::KeyboardListener::listen(), bnssemulator::Context::programFinished(), and bnssemulator::Context::timerTriggered().
Referenced by main().
{
         std::thread keyboard_listener(KeyboardListener::listen, &context);
         std::thread timer_thread(TimerListener::listen, &context);
         try {
             while (!context.programFinished()) {
                 try {
                     executeInstruction(context);
                 }
                 catch (...) {
                     if (context.insideInterrupt()) {
                         throw;
                     }
                     context.jumpToErrorInterrupt();
                 }
                 if (context.hasCharacters() && !context.insideInterrupt()) {
                     context.jumpToKeyboardInterrupt();
                 }
                 if (context.timerTriggered() && !context.insideInterrupt()) {
                     context.jumpToTimerInterrupt();
                 }
             }
         }
         catch (...) {
             context.finishProgram();
             keyboard_listener.join();
             timer_thread.join();
             throw;
         }
         keyboard_listener.join();
         timer_thread.join();
     }
staticData()
Processor::ProcessorStaticData & bnssemulator::Processor::staticData () static private noexcept
Definition at line 114 of file Processor.cpp.
Referenced by executeInstruction().
{
         static ProcessorStaticData static_data;
         return static_data;
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/Processor.h
Code/Emulator/Source/Processor.cpp