AssemblerEmulator - Nikola Bebic: bnssassembler::RegisterIndirectOffset Class Reference
bnssassembler::RegisterIndirectOffset Class Reference
Class representing the register indirect operand with offset.
#include <RegisterIndirectOffset.h>
Public Member Functions
RegisterIndirectOffset (Register reg, MicroRiscExpression offset_or_address, bool absolute)
Constructs a RegisterIndirectOffset object.
void packToInstruction (InstructionBitFieldUnion &instruction, uint32_t &second_word, std::list< RelocationRecord > &relocations) const override
Packs the operand into the instruction.
void resolveSymbols (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves the defined symbols in the expressions.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
AddressMode addressMode () const noexcept override
Gets the address mode of the operand.
Public Member Functions inherited from bnssassembler::Operand
virtual ~Operand ()=default
Private Attributes
Register reg_
MicroRiscExpression offset_or_address_
bool absolute_ = false
size_t pc_section_index_ = 0
size_t pc_offset_ = 0
Detailed Description
Class representing the register indirect operand with offset.
Definition at line 12 of file RegisterIndirectOffset.h.
Constructor & Destructor Documentation
RegisterIndirectOffset()
bnssassembler::RegisterIndirectOffset::RegisterIndirectOffset (Register reg, MicroRiscExpression offset_or_address, bool absolute)
Constructs a RegisterIndirectOffset object.
Parameters
reg Register
offset_or_address Offset or absolute address of the operand
absolute Whether the address is absolute
Definition at line 6 of file RegisterIndirectOffset.cpp.
References bnssassembler::PC.
                                                                                                                      : reg_(reg), offset_or_address_(offset_or_address), absolute_(absolute) {
         if (absolute && reg != PC) {
             throw MessageException("Only PC relative address can be absolute");
         }
     }
Member Function Documentation
addressMode()
AddressMode bnssassembler::RegisterIndirectOffset::addressMode () const override virtual noexcept
Gets the address mode of the operand.
Returns
Address mode of the operand
Implements bnssassembler::Operand.
Definition at line 78 of file RegisterIndirectOffset.cpp.
References bnssassembler::REGISTER_INDIRECT_OFFSET.
{
         return REGISTER_INDIRECT_OFFSET;
     }
packToInstruction()
void bnssassembler::RegisterIndirectOffset::packToInstruction (InstructionBitFieldUnion & instruction, uint32_t & second_word, std::list< RelocationRecord > & relocations) const override virtual
Packs the operand into the instruction.
Parameters
instruction Reference to the first word of the instruction containing the instruction info
second_word Reference to the second word of the instruction containing the address/value/displacement
relocations Reference to the list of relocation records
Implements bnssassembler::Operand.
Definition at line 12 of file RegisterIndirectOffset.cpp.
References absolute_, bnssassembler::InstructionBitField::address_mode, bnssassembler::InstructionBitFieldUnion::bit_field, bnssassembler::MicroRiscExpression::generateRelocations(), bnssassembler::NONE, offset_or_address_, pc_offset_, pc_section_index_, reg_, bnssassembler::InstructionBitField::register0, bnssassembler::InstructionBitField::register1, bnssassembler::InstructionBitField::register2, bnssassembler::REGISTER_INDIRECT_OFFSET, and bnssassembler::MicroRiscExpression::value().
{
         instruction.bit_field.address_mode = REGISTER_INDIRECT_OFFSET;
         second_word = offset_or_address_.value();
         if (absolute_) {
             second_word -= 4;
             auto rels = offset_or_address_.generateRelocations();
             if (rels.empty()) {
                 throw MessageException("PC Relative address must contain at least one label");
             }
             auto found_same_section = false;
             for (auto &rel : rels) {
                 if (rel.sectionIndex() == pc_section_index_) {
                     found_same_section = true;
                     second_word -= pc_offset_ + 4;
                     rels.remove(rel);
                     break;
                 }
             }
             if (!found_same_section) {
                 rels.front().absolute(false);
             }
             relocations.splice(relocations.end(), rels);
         }
         else {
             relocations.splice(relocations.end(), offset_or_address_.generateRelocations());
         }
         if (instruction.bit_field.register0 == NONE) {
             instruction.bit_field.register0 = reg_;
             return;
         }
         if (instruction.bit_field.register1 == NONE) {
             instruction.bit_field.register1 = reg_;
             return;
         }
         if (instruction.bit_field.register2 == NONE) {
             instruction.bit_field.register2 = reg_;
         }
     }
resolveCurrentPcSymbol()
void bnssassembler::RegisterIndirectOffset::resolveCurrentPcSymbol (size_t section_index, size_t offset) override virtual noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Reimplemented from bnssassembler::Operand.
Definition at line 72 of file RegisterIndirectOffset.cpp.
References offset_or_address_, pc_offset_, pc_section_index_, and bnssassembler::MicroRiscExpression::resolveCurrentPcSymbol().
{
         offset_or_address_.resolveCurrentPcSymbol(section_index, offset);
         pc_section_index_ = section_index;
         pc_offset_ = offset;
     }
resolveImports()
void bnssassembler::RegisterIndirectOffset::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates the relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Operand.
Definition at line 68 of file RegisterIndirectOffset.cpp.
References offset_or_address_, and bnssassembler::MicroRiscExpression::resolveImports().
{
         offset_or_address_.resolveImports(imported_symbols);
     }
resolveSymbols()
void bnssassembler::RegisterIndirectOffset::resolveSymbols (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves the defined symbols in the expressions.
Parameters
symbols Collection of symbol definitions
Reimplemented from bnssassembler::Operand.
Definition at line 58 of file RegisterIndirectOffset.cpp.
References offset_or_address_, and bnssassembler::MicroRiscExpression::setValue().
{
         for (auto &symbol : symbols) {
             offset_or_address_.setValue(symbol.name(), symbol.expression());
         }
     }
resolveSymbolTable()
void bnssassembler::RegisterIndirectOffset::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates the relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Operand.
Definition at line 64 of file RegisterIndirectOffset.cpp.
References offset_or_address_, and bnssassembler::MicroRiscExpression::resolveSymbolTable().
{
         offset_or_address_.resolveSymbolTable(symbol_table);
     }
Member Data Documentation
absolute_
bool bnssassembler::RegisterIndirectOffset::absolute_ = false private
Definition at line 31 of file RegisterIndirectOffset.h.
Referenced by packToInstruction().
offset_or_address_
MicroRiscExpression bnssassembler::RegisterIndirectOffset::offset_or_address_ private
Definition at line 30 of file RegisterIndirectOffset.h.
Referenced by packToInstruction(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbols(), and resolveSymbolTable().
pc_offset_
size_t bnssassembler::RegisterIndirectOffset::pc_offset_ = 0 private
Definition at line 33 of file RegisterIndirectOffset.h.
Referenced by packToInstruction(), and resolveCurrentPcSymbol().
pc_section_index_
size_t bnssassembler::RegisterIndirectOffset::pc_section_index_ = 0 private
Definition at line 32 of file RegisterIndirectOffset.h.
Referenced by packToInstruction(), and resolveCurrentPcSymbol().
reg_
Register bnssassembler::RegisterIndirectOffset::reg_ private
Definition at line 29 of file RegisterIndirectOffset.h.
Referenced by packToInstruction().
The documentation for this class was generated from the following files:
Code/Assembler/Include/RegisterIndirectOffset.h
Code/Assembler/Source/RegisterIndirectOffset.cpp