AssemblerEmulator - Nikola Bebic: bnssassembler::SecondPassData Class Reference
bnssassembler::SecondPassData Class Reference
Class representing the data that will be updated during the second pass.
#include <SecondPassData.h>
Public Member Functions
SecondPassData (FirstPassData &&first_pass_data) noexcept
Constructs the object.
void nextSection () noexcept
Increasses the current section counter.
bool orgValid () const noexcept
Check if the ORG address is valid.
bool contains (std::string symbol) const noexcept
Check whether the symbol exists in the symbol table.
void insertImported (std::string symbol)
Inserts an imported symbol into the set.
void exportSymbol (std::string symbol)
Exports a symbol.
SectionType currentSectionType () const noexcept
Gets the current section type.
void addData (uint8_t data, std::list< RelocationRecord > relocations)
Adds 8 bits of data to the current section.
void addData (uint16_t data, std::list< RelocationRecord > relocations)
Adds 16 bits of data to the current section.
void addData (uint32_t data, std::list< RelocationRecord > relocations)
Adds 32 bits of data to the current section.
void org (uint32_t address)
Sets the ORG address.
SymbolTable & symbolTable () noexcept
Gets the symbol table.
const SymbolTable & symbolTable () const noexcept
Gets the symbol table.
std::unordered_set< std::string > & importedSymbols ()
Gets the collection of imported symbols.
const std::unordered_set< std::string > & importedSymbols () const
Gets the collection of imported symbols.
size_t currentSectionIndex () const noexcept
Gets the index of the current section.
size_t currentSectionOffset () const noexcept
Gets the current offset inside the current section.
Private Attributes
std::unordered_set< std::string > imported_symbols_
SymbolTable symbol_table_
SectionTable section_table_
int32_t org_address_ = 0
bool org_valid_ = false
Friends
std::ostream & operator<< (std::ostream &os, const SecondPassData &data)
Writes the content of the object to a stream.
Detailed Description
Class representing the data that will be updated during the second pass.
Definition at line 11 of file SecondPassData.h.
Constructor & Destructor Documentation
SecondPassData()
bnssassembler::SecondPassData::SecondPassData (FirstPassData && first_pass_data) explicit noexcept
Constructs the object.
Parameters
first_pass_data Data generated by the first pass
Definition at line 8 of file SecondPassData.cpp.
 : symbol_table_(move(first_pass_data.symbol_table_)), section_table_(move(first_pass_data.section_table_)) {}
Member Function Documentation
addData() [1/3]
void bnssassembler::SecondPassData::addData (uint8_t data, std::list< RelocationRecord > relocations)
Adds 8 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 38 of file SecondPassData.cpp.
References bnssassembler::SectionTable::addData(), and section_table_.
Referenced by bnssassembler::DataDefinitionToken::secondPass(), and bnssassembler::InstructionToken::secondPass().
{
         section_table_.addData(data, relocations);
     }
addData() [2/3]
void bnssassembler::SecondPassData::addData (uint16_t data, std::list< RelocationRecord > relocations)
Adds 16 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 42 of file SecondPassData.cpp.
References bnssassembler::SectionTable::addData(), and section_table_.
{
         section_table_.addData(data, relocations);
     }
addData() [3/3]
void bnssassembler::SecondPassData::addData (uint32_t data, std::list< RelocationRecord > relocations)
Adds 32 bits of data to the current section.
Parameters
data Data to be addded
relocations List of relocation records for the data
Definition at line 46 of file SecondPassData.cpp.
References bnssassembler::SectionTable::addData(), and section_table_.
{
         section_table_.addData(data, relocations);
     }
contains()
bool bnssassembler::SecondPassData::contains (std::string symbol) const noexcept
Check whether the symbol exists in the symbol table.
Definition at line 22 of file SecondPassData.cpp.
References bnssassembler::SymbolTable::contains(), and symbol_table_.
Referenced by bnssassembler::GlobalSymbolsToken::secondPass().
{
         return symbol_table_.contains(symbol);
     }
currentSectionIndex()
size_t bnssassembler::SecondPassData::currentSectionIndex () const noexcept
Gets the index of the current section.
Definition at line 71 of file SecondPassData.cpp.
References bnssassembler::SectionTable::currentIndex(), and section_table_.
Referenced by currentSectionOffset(), and bnssassembler::SecondPass::execute().
{
         return section_table_.currentIndex();
     }
currentSectionOffset()
size_t bnssassembler::SecondPassData::currentSectionOffset () const noexcept
Gets the current offset inside the current section.
Definition at line 75 of file SecondPassData.cpp.
References bnssassembler::SectionTable::current(), currentSectionIndex(), section_table_, and bnssassembler::SectionData::size().
Referenced by bnssassembler::SecondPass::execute().
{
         if (currentSectionIndex() == static_cast<size_t>(-1)) {
             return 0;
         }
         return section_table_.current().size();
     }
currentSectionType()
SectionType bnssassembler::SecondPassData::currentSectionType () const noexcept
Gets the current section type.
Returns
Current section type
Definition at line 34 of file SecondPassData.cpp.
References bnssassembler::SectionTable::currentSectionType(), and section_table_.
Referenced by bnssassembler::DataDefinitionToken::secondPass(), and bnssassembler::InstructionToken::secondPass().
{
         return section_table_.currentSectionType();
     }
exportSymbol()
void bnssassembler::SecondPassData::exportSymbol (std::string symbol)
Exports a symbol.
Parameters
symbol Symbol to be exported
Definition at line 30 of file SecondPassData.cpp.
References bnssassembler::SymbolTable::exportSymbol(), and symbol_table_.
Referenced by bnssassembler::GlobalSymbolsToken::secondPass().
{
         symbol_table_.exportSymbol(symbol);
     }
importedSymbols() [1/2]
std::unordered_set< std::string > & bnssassembler::SecondPassData::importedSymbols ()
Gets the collection of imported symbols.
Returns
Collection of imported symbols
Definition at line 63 of file SecondPassData.cpp.
References imported_symbols_.
Referenced by bnssassembler::SecondPass::execute(), and importedSymbols().
{
         return imported_symbols_;
     }
importedSymbols() [2/2]
const std::unordered_set< std::string > & bnssassembler::SecondPassData::importedSymbols () const
Gets the collection of imported symbols.
Returns
Collection of imported symbols
Definition at line 67 of file SecondPassData.cpp.
References importedSymbols().
{
         return const_cast<SecondPassData &>(*this).importedSymbols();
     }
insertImported()
void bnssassembler::SecondPassData::insertImported (std::string symbol)
Inserts an imported symbol into the set.
Parameters
symbol Symbol to be imported
Definition at line 26 of file SecondPassData.cpp.
References imported_symbols_.
Referenced by bnssassembler::GlobalSymbolsToken::secondPass().
{
         imported_symbols_.insert(symbol);
     }
nextSection()
void bnssassembler::SecondPassData::nextSection () noexcept
Increasses the current section counter.
Definition at line 10 of file SecondPassData.cpp.
References bnssassembler::SectionTable::current(), bnssassembler::SectionTable::nextSection(), bnssassembler::SectionData::org(), org_address_, org_valid_, and section_table_.
Referenced by bnssassembler::SectionStartToken::secondPass().
{
         section_table_.nextSection();
         if (org_valid_) {
             org_valid_ = false;
             section_table_.current().org(org_address_);
         }
     }
org()
void bnssassembler::SecondPassData::org (uint32_t address)
Sets the ORG address.
Parameters
address ORG address
Definition at line 50 of file SecondPassData.cpp.
References org_address_, and org_valid_.
Referenced by bnssassembler::OrgDirectiveToken::secondPass().
{
         org_address_ = address;
         org_valid_ = true;
     }
orgValid()
bool bnssassembler::SecondPassData::orgValid () const noexcept
Check if the ORG address is valid.
Definition at line 18 of file SecondPassData.cpp.
References org_valid_.
Referenced by bnssassembler::SecondPass::execute().
{
         return org_valid_;
     }
symbolTable() [1/2]
SymbolTable & bnssassembler::SecondPassData::symbolTable () noexcept
Gets the symbol table.
Returns
Symbol table
Definition at line 55 of file SecondPassData.cpp.
References symbol_table_.
Referenced by bnssassembler::SecondPass::execute(), and symbolTable().
{
         return symbol_table_;
     }
symbolTable() [2/2]
const SymbolTable & bnssassembler::SecondPassData::symbolTable () const noexcept
Gets the symbol table.
Returns
Symbol table
Definition at line 59 of file SecondPassData.cpp.
References symbolTable().
{
         return const_cast<SecondPassData &>(*this).symbolTable();
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SecondPassData & data) friend
Writes the content of the object to a stream.
Parameters
os Stream where the content will be written
data Data that will be written
Definition at line 83 of file SecondPassData.cpp.
{
         os << data.imported_symbols_.size() << std::endl;
         std::cout << UPPER_LEFT << multiple(HORIZONTAL, 81) << UPPER_RIGHT << std::endl;
         std::cout << VERTICAL << UPPER_LEFT << multiple(HORIZONTAL, 79) << UPPER_RIGHT << VERTICAL << std::endl;
         std::cout << VERTICAL << VERTICAL << std::setw(79) << std::left << " Imported symbols:" << VERTICAL << VERTICAL << std::endl;
         std::cout << VERTICAL << LOWER_LEFT << multiple(HORIZONTAL, 79) << LOWER_RIGHT << VERTICAL << std::endl;
         std::cout << T_RIGHT << multiple(HORIZONTAL, 81) << T_LEFT << std::endl;
         for (auto &symbol : data.imported_symbols_) {
             os << symbol << std::endl;
             std::cout << VERTICAL << " " << std::setw(80) << std::left << symbol << VERTICAL << std::endl;
         }
         std::cout << LOWER_LEFT << multiple(HORIZONTAL, 81) << LOWER_RIGHT << std::endl << std::endl << std::endl;
         os << data.section_table_ << std::endl;
         os << data.symbol_table_ << std::endl;
         return os;
     }
Member Data Documentation
imported_symbols_
std::unordered_set<std::string> bnssassembler::SecondPassData::imported_symbols_ private
Definition at line 120 of file SecondPassData.h.
Referenced by importedSymbols(), insertImported(), and bnssassembler::operator<<().
org_address_
int32_t bnssassembler::SecondPassData::org_address_ = 0 private
Definition at line 124 of file SecondPassData.h.
Referenced by nextSection(), and org().
org_valid_
bool bnssassembler::SecondPassData::org_valid_ = false private
Definition at line 125 of file SecondPassData.h.
Referenced by nextSection(), org(), and orgValid().
section_table_
SectionTable bnssassembler::SecondPassData::section_table_ private
Definition at line 122 of file SecondPassData.h.
Referenced by addData(), currentSectionIndex(), currentSectionOffset(), currentSectionType(), nextSection(), and bnssassembler::operator<<().
symbol_table_
SymbolTable bnssassembler::SecondPassData::symbol_table_ private
Definition at line 121 of file SecondPassData.h.
Referenced by contains(), exportSymbol(), bnssassembler::operator<<(), and symbolTable().
The documentation for this class was generated from the following files:
Code/Assembler/Include/SecondPassData.h
Code/Assembler/Source/SecondPassData.cpp