AssemblerEmulator - Nikola Bebic: bnssemulator::TimerListener Class Reference
bnssemulator::TimerListener Class Reference
Class representing a listener for the timer events.
#include <TimerListener.h>
Static Public Member Functions
static void listen (Context *context)
Listens to timer interrupts and sets the context flag every time it should.
Detailed Description
Class representing a listener for the timer events.
Definition at line 10 of file TimerListener.h.
Member Function Documentation
listen()
void bnssemulator::TimerListener::listen (Context * context) static
Listens to timer interrupts and sets the context flag every time it should.
Definition at line 7 of file TimerListener.cpp.
References bnssemulator::Context::programFinished(), and bnssemulator::Context::timerTriggered().
Referenced by bnssemulator::Processor::executeProgram().
{
         using namespace std::literals::chrono_literals;
         while (!context->programFinished()) {
             std::this_thread::sleep_for(100ms);
             context->timerTriggered(true);
         }
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/TimerListener.h
Code/Emulator/Source/TimerListener.cpp