AssemblerEmulator - Nikola Bebic: bnssemulator::FileReader Class Reference
bnssemulator::FileReader Class Reference final
Utility class used for reading assembler output from the file.
#include <FileReader.h>
Static Public Member Functions
static AssemblerOutput parse (std::string filename)
Parses the input file.
Private Member Functions
FileReader ()=delete
FileReader (FileReader &)=delete
void operator= (FileReader &)=delete
Detailed Description
Utility class used for reading assembler output from the file.
Definition at line 11 of file FileReader.h.
Constructor & Destructor Documentation
FileReader() [1/2]
bnssemulator::FileReader::FileReader () private delete
FileReader() [2/2]
bnssemulator::FileReader::FileReader (FileReader &) private delete
Member Function Documentation
operator=()
void bnssemulator::FileReader::operator= (FileReader &) private delete
parse()
AssemblerOutput bnssemulator::FileReader::parse (std::string filename) static
Parses the input file.
Parameters
filename Name of the input file
Returns
Object containing the parsed input file
Definition at line 8 of file FileReader.cpp.
References z85::decode_with_padding(), and bnssemulator::StringHelper::fileToString().
Referenced by main().
{
         auto raw_file = StringHelper::fileToString(filename);
         auto decoded = z85::decode_with_padding(raw_file);
         std::stringstream stringstream(decoded);
         AssemblerOutput ret;
         stringstream >> ret;
         return ret;
     }
The documentation for this class was generated from the following files:
Code/Emulator/Include/FileReader.h
Code/Emulator/Source/FileReader.cpp