AssemblerEmulator - Nikola Bebic: bnssassembler::GlobalSymbolsToken Class Reference
bnssassembler::GlobalSymbolsToken Class Reference
Class representing the global symbols token.
#include <GlobalSymbolToken.h>
Public Member Functions
GlobalSymbolsToken (std::vector< std::string > symbols, size_t line_number, std::string line) noexcept
Constructs a GlobalSymbolsToken object.
void firstPass (FirstPassData &data) const override
Executes the first pass over the token.
void secondPass (SecondPassData &data) const override
Executes the second pass over the token.
Public Member Functions inherited from bnssassembler::Token
Token (size_t line_number, std::string line) noexcept
Constructs a token.
virtual void resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) noexcept
Resolves symbol definitions in a token.
virtual bool usesAddress () const noexcept
Check whether the token can use the ORG address.
virtual void resolveSymbolTable (const SymbolTable &symbol_table) noexcept
Resolves the symbols from the symbol table and updates relocation info.
virtual void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept
Resolves the imported symbols and updates relocation info.
virtual void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept
Resolves the current PC symbol and sets the relocation info.
size_t lineNumber () const noexcept
Get the line number of the token.
std::string line () const noexcept
Get the line of the token.
virtual ~Token ()=default
Private Attributes
std::vector< std::string > symbols_
Detailed Description
Class representing the global symbols token.
Definition at line 11 of file GlobalSymbolToken.h.
Constructor & Destructor Documentation
GlobalSymbolsToken()
bnssassembler::GlobalSymbolsToken::GlobalSymbolsToken (std::vector< std::string > symbols, size_t line_number, std::string line) noexcept
Constructs a GlobalSymbolsToken object.
Parameters
symbols Vector of global symbols
line_number Number of the line where the symbols are defined
line Line where symbols are defined
Definition at line 6 of file GlobalSymbolToken.cpp.
 : Token(line_number, line), symbols_(symbols) {}
Member Function Documentation
firstPass()
void bnssassembler::GlobalSymbolsToken::firstPass (FirstPassData & data) const override virtual
Executes the first pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 8 of file GlobalSymbolToken.cpp.
{
         // Do nothing
     }
secondPass()
void bnssassembler::GlobalSymbolsToken::secondPass (SecondPassData & data) const override virtual
Executes the second pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 12 of file GlobalSymbolToken.cpp.
References bnssassembler::SecondPassData::contains(), bnssassembler::SecondPassData::exportSymbol(), bnssassembler::SecondPassData::insertImported(), and symbols_.
{
         for (const auto &symbol : symbols_) {
             if (data.contains(symbol)) {
                 data.exportSymbol(symbol);
             }
             else {
                 data.insertImported(symbol);
             }
         }
     }
Member Data Documentation
symbols_
std::vector<std::string> bnssassembler::GlobalSymbolsToken::symbols_ private
Definition at line 24 of file GlobalSymbolToken.h.
Referenced by secondPass().
The documentation for this class was generated from the following files:
Code/Assembler/Include/GlobalSymbolToken.h
Code/Assembler/Source/GlobalSymbolToken.cpp