AssemblerEmulator - Nikola Bebic: bnssassembler::AddOperation Class Reference
bnssassembler::AddOperation Class Reference
Class implementing the behaviour of the + operator in expressions.
#include <AddOperation.h>
Public Member Functions
std::list< RelocationRecord > generateRelocations () const override
Generates the relocation records for the subtree.
Public Member Functions inherited from bnssassembler::Operation
int32_t value () const override
Evaluates the expression.
bool setValue (std::string symbol, std::shared_ptr< Expression > value) noexcept override
Traverses the subtree and sets the value for the symbol.
bool containsSymbol () const noexcept override
Tests whether the expression contains a Symbol.
int symbolCount () const noexcept override
Counts the symbols in the expression.
void pushChildren (std::stack< std::reference_wrapper< std::shared_ptr< Expression >>> &stack) const noexcept override
Pushes the children to the stack.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and sets the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and sets the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
std::list< RelocationRecord > generateRelocations () const override
Generates the relocation records for the subtree.
void left (std::shared_ptr< Expression > left) noexcept
Sets the left side of the operator.
void right (std::shared_ptr< Expression > right) noexcept
Sets the right side of the operator.
Public Member Functions inherited from bnssassembler::Expression
virtual bool validate () const noexcept
Validates the expression.
virtual ~Expression ()=default
Protected Member Functions
int32_t calculate (int32_t lhs, int32_t rhs) const noexcept override
Calculates the value of the subexpression.
Protected Member Functions inherited from bnssassembler::Operation
std::shared_ptr< Expression > left () const noexcept
Gets the left side of the operator.
std::shared_ptr< Expression > right () const noexcept
Gets the right side of the operator.
Detailed Description
Class implementing the behaviour of the + operator in expressions.
Definition at line 10 of file AddOperation.h.
Member Function Documentation
calculate()
int32_t bnssassembler::AddOperation::calculate (int32_t lhs, int32_t rhs) const override protected virtual noexcept
Calculates the value of the subexpression.
Parameters
lhs Left side of the operator
rhs Right side of the operator
Returns
Result of the operation
Exceptions
Throws if the expression can not be evaluated (example: division by zero)
Implements bnssassembler::Operation.
Definition at line 7 of file AddOperation.cpp.
{
         return lhs + rhs;
     }
generateRelocations()
std::list< RelocationRecord > bnssassembler::AddOperation::generateRelocations () const override virtual
Generates the relocation records for the subtree.
Returns
Collection of relocation records
Reimplemented from bnssassembler::Expression.
Definition at line 23 of file AddOperation.cpp.
References bnssassembler::SubtractOperation::generateRelocations(), bnssassembler::Operation::generateRelocations(), bnssassembler::Operation::left(), bnssassembler::Operation::right(), and bnssassembler::split().
{
         auto original = Operation::generateRelocations();
         std::list<RelocationRecord> left;
         std::list<RelocationRecord> right;
         split(original, left, right);
         return SubtractOperation::generateRelocations(left, right);
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/AddOperation.h
Code/Assembler/Source/AddOperation.cpp