AssemblerEmulator - Nikola Bebic: bnssassembler::AssemblerException Class Reference
bnssassembler::AssemblerException Class Reference abstract
Class representing the custom exception for the assembler.
#include <AssemblerException.h>
Public Member Functions
AssemblerException (size_t line_number, std::string line) noexcept
Constructs an AssemblerException object.
std::string message () const noexcept
Gets the message. Note that this should be used instead of what()
const char * what () const noexcept override
Protected Member Functions
virtual std::string messageBody () const noexcept=0
Returns the actual message body of the exception.
Private Attributes
size_t line_number_
std::string line_
Detailed Description
Class representing the custom exception for the assembler.
Definition at line 11 of file AssemblerException.h.
Constructor & Destructor Documentation
AssemblerException()
bnssassembler::AssemblerException::AssemblerException (size_t line_number, std::string line) explicit noexcept
Constructs an AssemblerException object.
Parameters
line_number Number of the line in the source file which triggered the exception
line Line of the source file which triggered the exception
Definition at line 6 of file AssemblerException.cpp.
 : line_number_(line_number), line_(line) {}
Member Function Documentation
message()
std::string bnssassembler::AssemblerException::message () const noexcept
Gets the message. Note that this should be used instead of what()
Returns
The message of the exception
Definition at line 8 of file AssemblerException.cpp.
References line_, line_number_, messageBody(), and bnssassembler::StringHelper::numberFormat().
Referenced by main(), and what().
{
         return
             "Error in line " + StringHelper::numberFormat(line_number_) + "\n" +
             line_ + "\n" +
             messageBody();
     }
messageBody()
virtual std::string bnssassembler::AssemblerException::messageBody () const protected pure virtual noexcept
Returns the actual message body of the exception.
Implemented in bnssassembler::FirstPassException, bnssassembler::ParserException, and bnssassembler::SecondPassException.
Referenced by message().
what()
const char * bnssassembler::AssemblerException::what () const override noexcept
Definition at line 15 of file AssemblerException.cpp.
References message().
{
         return message().c_str();
     }
Member Data Documentation
line_
std::string bnssassembler::AssemblerException::line_ private
Definition at line 33 of file AssemblerException.h.
Referenced by message().
line_number_
size_t bnssassembler::AssemblerException::line_number_ private
Definition at line 32 of file AssemblerException.h.
Referenced by message().
The documentation for this class was generated from the following files:
Code/Assembler/Include/AssemblerException.h
Code/Assembler/Source/AssemblerException.cpp