AssemblerEmulator - Nikola Bebic: bnssassembler::Parser Class Reference
bnssassembler::Parser Class Reference abstract
Abstract class representing a text parser.
#include <Parser.h>
Public Member Functions
std::vector< std::shared_ptr< Token > > parse (std::vector< std::string > body) const
Parses the File into tokens.
virtual ~Parser ()=default
Virtual destructor needed for polymorphic class.
Protected Member Functions
virtual std::vector< std::string > oneLineCommentDelimiters () const noexcept=0
Returns all strings that start the comment to the end of the line.
virtual std::vector< std::string > labelDelimiters () const noexcept=0
Returns all strings that end the label at the start of the line.
virtual bool isEnd (std::string line) const noexcept=0
Checks if the parser should stop parsing the file.
virtual std::shared_ptr< LineParser > chain () const noexcept=0
Returns the first LineParser in chain.
Detailed Description
Abstract class representing a text parser.
Definition at line 14 of file Parser.h.
Constructor & Destructor Documentation
~Parser()
virtual bnssassembler::Parser::~Parser () virtual default
Virtual destructor needed for polymorphic class.
Member Function Documentation
chain()
virtual std::shared_ptr<LineParser> bnssassembler::Parser::chain () const protected pure virtual noexcept
Returns the first LineParser in chain.
Returns
Pointer to the first parser
Implemented in bnssassembler::MicroRiscParser.
Referenced by parse().
isEnd()
virtual bool bnssassembler::Parser::isEnd (std::string line) const protected pure virtual noexcept
Checks if the parser should stop parsing the file.
Parameters
line Line to check
Implemented in bnssassembler::MicroRiscParser.
Referenced by parse().
labelDelimiters()
virtual std::vector<std::string> bnssassembler::Parser::labelDelimiters () const protected pure virtual noexcept
Returns all strings that end the label at the start of the line.
Returns
Vector of such strings
Implemented in bnssassembler::MicroRiscParser.
Referenced by parse().
oneLineCommentDelimiters()
virtual std::vector<std::string> bnssassembler::Parser::oneLineCommentDelimiters () const protected pure virtual noexcept
Returns all strings that start the comment to the end of the line.
Returns
Vector of such strings
Implemented in bnssassembler::MicroRiscParser.
Referenced by parse().
parse()
std::vector< std::shared_ptr< Token > > bnssassembler::Parser::parse (std::vector< std::string > body) const
Parses the File into tokens.
Parameters
body Collection of all lines in the file
Returns
Collection of tokens
Exceptions
Throws if the file can not be parsed
Definition at line 53 of file Parser.cpp.
References chain(), bnssassembler::extractLabel(), bnssassembler::StringHelper::isAllWhiteSpace(), isEnd(), labelDelimiters(), bnssassembler::MessageException::message(), oneLineCommentDelimiters(), and bnssassembler::stripComment().
Referenced by main().
{
         std::vector<std::shared_ptr<Token>> ret;
         for (size_t i = 0; i < body.size(); i++) {
             auto &line = body[i];
             auto initial_line = line;
             try {
                 // Strip the comments
                 stripComment(line, oneLineCommentDelimiters());
                 // Extract the label (if it exists) and insert it into the Token vector
                 auto label = extractLabel(line, labelDelimiters());
                 if (label != "") {
                     ret.push_back(std::make_shared<LabelToken>(label, i + 1, initial_line));
                 }
                 // Skip if the line contains no data
                 if (StringHelper::isAllWhiteSpace(line)) {
                     continue;
                 }
                 // Check if the file should still be parsed
                 if (isEnd(line)) {
                     break;
                 }
                 // Parse the line
                 auto token = chain()->tryParse(line, i + 1, initial_line);
                 if (token == nullptr) {
                     throw MessageException("The line can not be parsed");
                 }
                 ret.push_back(token);
             }
             catch (MessageException &e) {
                 throw ParserException(i + 1, initial_line, e.message());
             }
         }
         return ret;
     }
The documentation for this class was generated from the following files:
Code/Assembler/Include/Parser.h
Code/Assembler/Source/Parser.cpp