AssemblerEmulator - Nikola Bebic: bnssassembler::MicroRiscExpression Class Reference
bnssassembler::MicroRiscExpression Class Reference
Adapter class for Expression.
#include <MicroRiscExpression.h>
Public Member Functions
MicroRiscExpression (std::shared_ptr< Expression > expression) noexcept
Constructs a MicroRiscExpression object.
int32_t value () const
Get the value of the expression.
bool setValue (std::string name, MicroRiscExpression expression) const noexcept
Sets the value for the symbol.
void resolveSymbolTable (const SymbolTable &symbol_table) const noexcept
Resolves the symbols from the symbol table and sets the relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) const noexcept
Resolves the imported symbols and sets the relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) const noexcept
Resolves the current PC symbol and sets the relocation info.
std::list< RelocationRecord > generateRelocations () const
Validates the tree and generates the relocation records for the expression.
Private Attributes
std::shared_ptr< Expression > expression_
Detailed Description
Adapter class for Expression.
Definition at line 11 of file MicroRiscExpression.h.
Constructor & Destructor Documentation
MicroRiscExpression()
bnssassembler::MicroRiscExpression::MicroRiscExpression (std::shared_ptr< Expression > expression) explicit noexcept
Constructs a MicroRiscExpression object.
Parameters
expression Pointer to Expression object that this object will adapt
Definition at line 6 of file MicroRiscExpression.cpp.
 : expression_(expression) {}
Member Function Documentation
generateRelocations()
std::list< RelocationRecord > bnssassembler::MicroRiscExpression::generateRelocations () const
Validates the tree and generates the relocation records for the expression.
Returns
Collection of relocation records
Definition at line 28 of file MicroRiscExpression.cpp.
References expression_.
Referenced by bnssassembler::Immediate::packToInstruction(), bnssassembler::MemoryDirect::packToInstruction(), bnssassembler::RegisterIndirectOffset::packToInstruction(), and bnssassembler::OrgDirectiveToken::secondPass().
{
         expression_->validate();
         auto ret = expression_->generateRelocations();
         for (auto &element : ret) {
             if (element.opposite()) {
                 throw MessageException((element.section() ? "Symbols from " + std::to_string(element.sectionIndex()) + "th section are " : "Symbol " + element.symbolName() + " is ") + "subtracted more times than added");
             }
         }
         return ret;
     }
resolveCurrentPcSymbol()
void bnssassembler::MicroRiscExpression::resolveCurrentPcSymbol (size_t section_index, size_t offset) const noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Definition at line 24 of file MicroRiscExpression.cpp.
References expression_.
Referenced by bnssassembler::Immediate::resolveCurrentPcSymbol(), bnssassembler::MemoryDirect::resolveCurrentPcSymbol(), and bnssassembler::RegisterIndirectOffset::resolveCurrentPcSymbol().
{
         expression_->resolveCurrentPcSymbol(section_index, offset);
     }
resolveImports()
void bnssassembler::MicroRiscExpression::resolveImports (std::unordered_set< std::string > imported_symbols) const noexcept
Resolves the imported symbols and sets the relocation info.
Parameters
imported_symbols Collection of imported symbols
Definition at line 20 of file MicroRiscExpression.cpp.
References expression_.
Referenced by bnssassembler::Immediate::resolveImports(), bnssassembler::MemoryDirect::resolveImports(), bnssassembler::OrgDirectiveToken::resolveImports(), and bnssassembler::RegisterIndirectOffset::resolveImports().
{
         expression_->resolveImports(imported_symbols);
     }
resolveSymbolTable()
void bnssassembler::MicroRiscExpression::resolveSymbolTable (const SymbolTable & symbol_table) const noexcept
Resolves the symbols from the symbol table and sets the relocation info.
Parameters
symbol_table Symbol table
Definition at line 16 of file MicroRiscExpression.cpp.
References expression_.
Referenced by bnssassembler::Immediate::resolveSymbolTable(), bnssassembler::MemoryDirect::resolveSymbolTable(), bnssassembler::OrgDirectiveToken::resolveSymbolTable(), and bnssassembler::RegisterIndirectOffset::resolveSymbolTable().
{
         expression_->resolveSymbolTable(symbol_table);
     }
setValue()
bool bnssassembler::MicroRiscExpression::setValue (std::string name, MicroRiscExpression expression) const noexcept
Sets the value for the symbol.
Parameters
name Name of the symbol
expression Expression of the symbol
Definition at line 12 of file MicroRiscExpression.cpp.
References expression_, and bnssassembler::name().
Referenced by bnssassembler::Immediate::resolveSymbols(), bnssassembler::MemoryDirect::resolveSymbols(), and bnssassembler::RegisterIndirectOffset::resolveSymbols().
{
         return expression_->setValue(name, expression.expression_);
     }
value()
int32_t bnssassembler::MicroRiscExpression::value () const
Get the value of the expression.
Returns
Value of the expression
Exceptions
Throws if the value can not be calculated
Definition at line 8 of file MicroRiscExpression.cpp.
References expression_.
Referenced by bnssassembler::Immediate::packToInstruction(), bnssassembler::MemoryDirect::packToInstruction(), bnssassembler::RegisterIndirectOffset::packToInstruction(), and bnssassembler::OrgDirectiveToken::secondPass().
{
         return expression_->value();
     }
Member Data Documentation
expression_
std::shared_ptr<Expression> bnssassembler::MicroRiscExpression::expression_ private
Definition at line 58 of file MicroRiscExpression.h.
Referenced by generateRelocations(), resolveCurrentPcSymbol(), resolveImports(), resolveSymbolTable(), setValue(), and value().
The documentation for this class was generated from the following files:
Code/Assembler/Include/MicroRiscExpression.h
Code/Assembler/Source/MicroRiscExpression.cpp