AssemblerEmulator - Nikola Bebic: bnssassembler::SecondPass Class Reference
bnssassembler::SecondPass Class Reference final
Utility class executing the second pass.
#include <SecondPass.h>
Static Public Member Functions
static SecondPassData execute (std::vector< std::shared_ptr< Token >> tokens, FirstPassData &&first_pass_data)
Executes the second pass using the first pass.
Private Member Functions
SecondPass ()=delete
SecondPass (SecondPass &)=delete
void operator= (SecondPass &)=delete
Detailed Description
Utility class executing the second pass.
Definition at line 11 of file SecondPass.h.
Constructor & Destructor Documentation
SecondPass() [1/2]
bnssassembler::SecondPass::SecondPass () private delete
SecondPass() [2/2]
bnssassembler::SecondPass::SecondPass (SecondPass &) private delete
Member Function Documentation
execute()
SecondPassData bnssassembler::SecondPass::execute (std::vector< std::shared_ptr< Token >> tokens, FirstPassData && first_pass_data) static
Executes the second pass using the first pass.
Parameters
tokens Vector of parsed tokens
first_pass_data Data generated from the first pass
Definition at line 7 of file SecondPass.cpp.
References bnssassembler::SecondPassData::currentSectionIndex(), bnssassembler::SecondPassData::currentSectionOffset(), bnssassembler::SecondPassData::importedSymbols(), bnssassembler::MessageException::message(), bnssassembler::SecondPassData::orgValid(), and bnssassembler::SecondPassData::symbolTable().
Referenced by main().
{
         SecondPassData ret(std::move(first_pass_data));
         for (auto &token : tokens) {
             try {
                 if (ret.orgValid() && !token->usesAddress()) {
                     throw MessageException("ORG directive must be followed by a section start");
                 }
                 token->resolveCurrentPcSymbol(ret.currentSectionIndex(), ret.currentSectionOffset());
                 token->resolveSymbolTable(ret.symbolTable());
                 token->resolveImports(ret.importedSymbols());
                 token->secondPass(ret);
             } catch (MessageException &exception) {
                 throw SecondPassException(token->lineNumber(), token->line(), exception.message());
             }
         }
         return ret;
     }
operator=()
void bnssassembler::SecondPass::operator= (SecondPass &) private delete
The documentation for this class was generated from the following files:
Code/Assembler/Include/SecondPass.h
Code/Assembler/Source/SecondPass.cpp