AssemblerEmulator - Nikola Bebic: bnssassembler::InstructionToken Class Reference
bnssassembler::InstructionToken Class Reference
Class representing the instruction in an assembler source file.
#include <InstructionToken.h>
Public Member Functions
InstructionToken (size_t line_number, std::string line, InstructionCode code, std::vector< std::shared_ptr< Operand >> operands, OperandType type=DEFAULT) noexcept
Constructs an InstructionToken object.
void resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) noexcept override
Resolves symbol definitions in a token.
void firstPass (FirstPassData &data) const override
Executes the first pass over the token.
void secondPass (SecondPassData &data) const override
Executes the second pass over the token.
void resolveSymbolTable (const SymbolTable &symbol_table) noexcept override
Resolves the symbols from the symbol table and updates relocation info.
void resolveImports (std::unordered_set< std::string > imported_symbols) noexcept override
Resolves the imported symbols and updates relocation info.
void resolveCurrentPcSymbol (size_t section_index, size_t offset) noexcept override
Resolves the current PC symbol and sets the relocation info.
Public Member Functions inherited from bnssassembler::Token
Token (size_t line_number, std::string line) noexcept
Constructs a token.
virtual bool usesAddress () const noexcept
Check whether the token can use the ORG address.
size_t lineNumber () const noexcept
Get the line number of the token.
std::string line () const noexcept
Get the line of the token.
virtual ~Token ()=default
Private Member Functions
size_t length () const
Gets the length of the instruction in bytes.
std::pair< uint32_t, std::pair< uint32_t, std::list< RelocationRecord > > > packInstruction () const
Private Attributes
InstructionCode code_
OperandType type_
std::vector< std::shared_ptr< Operand > > operands_
Detailed Description
Class representing the instruction in an assembler source file.
Definition at line 16 of file InstructionToken.h.
Constructor & Destructor Documentation
InstructionToken()
bnssassembler::InstructionToken::InstructionToken (size_t line_number, std::string line, InstructionCode code, std::vector< std::shared_ptr< Operand >> operands, OperandType type = DEFAULT) noexcept
Constructs an InstructionToken object.
Parameters
line_number Number of the line where the instruction is
line Line where the instruction is
code Instruction code
operands Vector of operands of the instruction
type Type of the operand
Definition at line 9 of file InstructionToken.cpp.
 : Token(line_number, line), code_(code), type_(type), operands_(operands) {}
Member Function Documentation
firstPass()
void bnssassembler::InstructionToken::firstPass (FirstPassData & data) const override virtual
Executes the first pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 17 of file InstructionToken.cpp.
References bnssassembler::FirstPassData::incLocationCounter(), and length().
{
         data.incLocationCounter(length());
     }
length()
size_t bnssassembler::InstructionToken::length () const private
Gets the length of the instruction in bytes.
Returns
Length of the instruction in bytes
Definition at line 52 of file InstructionToken.cpp.
References bnssassembler::IMMEDIATE, bnssassembler::MEMORY_DIRECT, operands_, and bnssassembler::REGISTER_INDIRECT_OFFSET.
Referenced by firstPass(), and secondPass().
{
         for (auto &operand : operands_) {
             if (
                 operand->addressMode() == IMMEDIATE ||
                 operand->addressMode() == MEMORY_DIRECT ||
                 operand->addressMode() == REGISTER_INDIRECT_OFFSET)
                 return 8;
         }
         return 4;
     }
packInstruction()
std::pair< uint32_t, std::pair< uint32_t, std::list< RelocationRecord > > > bnssassembler::InstructionToken::packInstruction () const private
Definition at line 64 of file InstructionToken.cpp.
References bnssassembler::InstructionBitField::address_mode, bnssassembler::InstructionBitFieldUnion::bit_field, code_, bnssassembler::InstructionBitFieldUnion::data, bnssassembler::NONE, operands_, bnssassembler::InstructionBitField::operation_code, bnssassembler::InstructionBitField::register0, bnssassembler::InstructionBitField::register1, bnssassembler::InstructionBitField::register2, bnssassembler::REGISTER_DIRECT, bnssassembler::InstructionBitField::type, and type_.
Referenced by secondPass().
{
         std::pair<uint32_t, std::pair<uint32_t, std::list<RelocationRecord>>> ret;
         InstructionBitFieldUnion instruction;
         instruction.bit_field.operation_code = code_;
         instruction.bit_field.address_mode = REGISTER_DIRECT; // Default address mode
         instruction.bit_field.register0 = NONE;
         instruction.bit_field.register1 = NONE;
         instruction.bit_field.register2 = NONE;
         instruction.bit_field.type = type_;
         for (auto &operand : operands_) {
             operand->packToInstruction(instruction, ret.second.first, ret.second.second);
         }
         // ReSharper disable once CppSomeObjectMembersMightNotBeInitialized
         ret.first = instruction.data;
         return ret;
     }
resolveCurrentPcSymbol()
void bnssassembler::InstructionToken::resolveCurrentPcSymbol (size_t section_index, size_t offset) override virtual noexcept
Resolves the current PC symbol and sets the relocation info.
Parameters
section_index Current PC section
offset PC address in relation to the current section beginning
Reimplemented from bnssassembler::Token.
Definition at line 46 of file InstructionToken.cpp.
References operands_.
{
         for (auto &operand: operands_) {
             operand->resolveCurrentPcSymbol(section_index, offset);
         }
     }
resolveImports()
void bnssassembler::InstructionToken::resolveImports (std::unordered_set< std::string > imported_symbols) override virtual noexcept
Resolves the imported symbols and updates relocation info.
Parameters
imported_symbols Collection of imported symbols
Reimplemented from bnssassembler::Token.
Definition at line 40 of file InstructionToken.cpp.
References operands_.
{
         for (auto &operand : operands_) {
             operand->resolveImports(imported_symbols);
         }
     }
resolveSymbolDefinitions()
void bnssassembler::InstructionToken::resolveSymbolDefinitions (std::unordered_set< SymbolDefinition > symbols) override virtual noexcept
Resolves symbol definitions in a token.
Parameters
symbols Vector od symbol definitions that should be resolved
Reimplemented from bnssassembler::Token.
Definition at line 11 of file InstructionToken.cpp.
{
         for (auto &operand : operands_) {
             operand->resolveSymbols(symbols);
         }
     }
resolveSymbolTable()
void bnssassembler::InstructionToken::resolveSymbolTable (const SymbolTable & symbol_table) override virtual noexcept
Resolves the symbols from the symbol table and updates relocation info.
Parameters
symbol_table Symbol table
Reimplemented from bnssassembler::Token.
Definition at line 34 of file InstructionToken.cpp.
References operands_.
{
         for (auto &operand : operands_) {
             operand->resolveSymbolTable(symbol_table);
         }
     }
secondPass()
void bnssassembler::InstructionToken::secondPass (SecondPassData & data) const override virtual
Executes the second pass over the token.
Parameters
data Data that the token will modify
Implements bnssassembler::Token.
Definition at line 21 of file InstructionToken.cpp.
References bnssassembler::SecondPassData::addData(), bnssassembler::SecondPassData::currentSectionType(), length(), packInstruction(), and bnssassembler::TEXT.
{
         if (data.currentSectionType() != TEXT) {
             throw MessageException("Instructions can only exist in text sections");
         }
         auto pair = packInstruction();
         data.addData(pair.first, std::list<RelocationRecord>());
         if (length() == 8) {
             data.addData(pair.second.first, pair.second.second);
         }
     }
Member Data Documentation
code_
InstructionCode bnssassembler::InstructionToken::code_ private
Definition at line 35 of file InstructionToken.h.
Referenced by packInstruction().
operands_
std::vector<std::shared_ptr<Operand> > bnssassembler::InstructionToken::operands_ private
Definition at line 37 of file InstructionToken.h.
Referenced by length(), packInstruction(), resolveCurrentPcSymbol(), resolveImports(), and resolveSymbolTable().
type_
OperandType bnssassembler::InstructionToken::type_ private
Definition at line 36 of file InstructionToken.h.
Referenced by packInstruction().
The documentation for this class was generated from the following files:
Code/Assembler/Include/InstructionToken.h
Code/Assembler/Source/InstructionToken.cpp