AssemblerEmulator - Nikola Bebic: bnssemulator Namespace Reference
bnssemulator Namespace Reference
Classes
class AddExecuter
Class representing the executer for the add instruction.
class AddressSpace
Class representing the address space of the emulator.
class AluExecuter
Base class used for executing ALU instructions.
class AndExecuter
Class representing the executer for the and instruction.
class AslExecuter
Class representing the executer for the asl instruction.
class AsrExecuter
Class representing the executer for the asr instruction.
class AssemblerOutput
Class representing the output from the assembler.
class CallExecuter
Class representing the executer for the call instruction.
class CommandLineHelper
Utility class used for parsing the command line.
struct compare_pair_difference
struct compare_pair_first
struct compare_pair_second
class ConditionalJumpExecuter
Base executer for conditional jump instructions.
class Context
Class representing the context of the processor.
class DivideExecuter
Class representing the executer of the divide instruction.
class Executer
Base class used for executing instructions.
class FileReader
Utility class used for reading assembler output from the file.
struct InstructionBitField
Bit field that enables easier manipulation of instructions.
union InstructionBitFieldUnion
Union that enables easier manipulation of the instruction bit field.
class IntExecuter
Class representing the executer for the int instruction.
class JgezExecuter
Class representing the executer for the jgez instruction.
class JgzExecuter
Class representing the executer for the jgz instruction.
class JlezExecuter
Class representing the executer for the jlez instruction.
class JlzExecuter
Class representing the executer for the jlz instruction.
class JmpExecuter
Class representing the executer for the jmp instruction.
class JnzExecuter
Class representing the executer for the jnz instruction.
class JzExecuter
Class representing the executer for the jz instruction.
class KeyboardListener
Class representing the keyboard listener thread.
class LoadExecuter
Class representing the executer for the load instruction.
class MessageException
Represents an exception with a string message.
class ModuloExecuter
Class representing the executer for the modulo instruction.
class MultiplyExecuter
Class representing the executer for the multiply instruction.
class NotExecuter
Class representing the executer for the not instruction.
class OrExecuter
Class representing the executer for the or instruction.
class PopExecuter
Class representing the executer for the pop instruction.
class Processor
Class representing the processor.
class PushExecuter
Class representing the executer for the push instruction.
class Register
Class representing the register.
class RelocationRecord
Class representing one relocation record.
class RetExecuter
Class representing the executer for ret instruction.
class SectionData
Class representing the data about one section.
class Segment
Class representing one segment of memory.
class StoreExecuter
Class representing the executer for the store instruction.
class StringHelper
Utility class providing helper methods for std::string class.
class SubtractExecuter
Class representing the executer for the subtract instruction.
class SymbolData
Class representing data about one symbol.
class TimerListener
Class representing a listener for the timer events.
class XorExecuter
Class representing the executer for the xor instruction.
Enumerations
enum AddressMode : uint32_t {
IMMEDIATE = 0b100, REGISTER_DIRECT = 0b000, MEMORY_DIRECT = 0b110, REGISTER_INDIRECT = 0b010,
REGISTER_INDIRECT_OFFSET = 0b111
}
Enum representing the address mode.
enum DataType : int8_t { DOUBLE_WORD = 0, WORD, BYTE }
Enum representing a data type.
enum InstructionCode : int8_t {
INT = 0x00, JMP = 0x02, CALL = 0x03, RET = 0x01,
JZ = 0x04, JNZ = 0x05, JGZ = 0x06, JGEZ = 0x07,
JLZ = 0x08, JLEZ = 0x09, LOAD = 0x10, STORE = 0x11,
PUSH = 0x20, POP = 0x21, ADD = 0x30, SUB = 0x31,
MUL = 0x32, DIV = 0x33, MOD = 0x34, AND = 0x35,
OR = 0x36, XOR = 0x37, NOT = 0x38, ASL = 0x39,
ASR = 0x3A
}
Enum representing the instruction code.
enum OperandType : int8_t {
DEFAULT = 0b000, UNSIGNED_BYTE = 0b011, SIGNED_BYTE = 0b111, REGULAR_BYTE = 0b111,
UNSIGNED_WORD = 0b001, SIGNED_WORD = 0b101, REGULAR_WORD = 0b101, REGULAR_DOUBLE_WORD = 0b000
}
Enum representing the operand type.
enum SectionType : int8_t { TEXT = 0, DATA, RODATA, BSS }
Enum representing the type of the section.
Functions
static void removeEmpty (std::vector< SectionData > &section_table)
static bool checkOverlaps (const std::vector< SectionData > &section_table)
static std::list< std::pair< uint32_t, uint32_t > > getAvailable (const std::vector< SectionData > &section_table)
static void generateAddresses (std::vector< SectionData > &section_table, std::list< std::pair< uint32_t, uint32_t >> &available)
std::istream & operator>> (std::istream &is, AssemblerOutput &data)
static size_t getRegisterIndex (InstructionBitField instruction, size_t register_index)
Gets the index of the register in the array of registers.
static uint32_t fill (OperandType type, int32_t operand)
static InstructionCode opcode (InstructionBitField instruction)
Register operator+ (const Register &lhs, const Register &rhs) noexcept
Register operator- (const Register &lhs, const Register &rhs) noexcept
Register operator* (const Register &lhs, const Register &rhs) noexcept
Register operator/ (const Register &lhs, const Register &rhs) noexcept
Register operator% (const Register &lhs, const Register &rhs) noexcept
Register operator & (const Register &lhs, const Register &rhs) noexcept
Register operator| (const Register &lhs, const Register &rhs) noexcept
Register operator^ (const Register &lhs, const Register &rhs) noexcept
Register operator<< (const Register &lhs, const Register &rhs) noexcept
Register operator>> (const Register &lhs, const Register &rhs) noexcept
std::istream & operator>> (std::istream &is, RelocationRecord &data)
std::istream & operator>> (std::istream &is, SectionData &data)
std::istream & operator>> (std::istream &is, SymbolData &data)
Variables
const size_t BLOCK_BITS = 16
const uint32_t PAGE_MASK = ~0 << BLOCK_BITS
const uint32_t OFFSET_MASK = ~PAGE_MASK
const size_t BLOCK_SIZE = OFFSET_MASK + 1
const std::string ZERO = "0"
const std::string DECIMAL = "[1-9][0-9]*"
const std::string HEX = "0x[0-9a-fA-F][0-9a-fA-F]*"
const std::string BINARY = "0b[01][01]*"
const std::string OCT = "0[0-7][0-7]*"
const std::string CHARACTER = "'[[:print:]]'"
const std::string LITERAL = "(" + ZERO + "|" + DECIMAL + "|" + HEX + "|" + BINARY + "|" + OCT + "|" + CHARACTER + ")"
const std::string OPERATOR = "[-+*/()]"
const std::string SYMBOL = "(([a-zA-Z_][a-zA-Z_0-9]*)|\\$)"
const std::string LABEL = SYMBOL
const std::string CONSTANT_TERM = "([[:space:]]*(" + LITERAL + "|" + OPERATOR + "|" + SYMBOL + ")[[:space:]]*)*"
const std::string ORG_DIRECTIVE = "[Oo][Rr][Gg]"
const std::string SYMBOL_DEFINITION = "[Dd][Ee][Ff]"
const std::string DUPLICATE_DIRECTIVE = "[Dd][Uu][Pp]"
const std::string GLOBAL_DIRECTIVE = "[.][Gg][Ll][Oo][Bb][Aa][Ll]"
const std::string COMMA_TOKENIZER = "[[:space:]]*(.*?)[[:space:]]*,(.*)"
const std::string LAST_COMMA_TOKEN = "[[:space:]]*(.*)[[:space:]]*"
const std::regex ZERO_REGEX = std::regex(ZERO)
const std::regex DECIMAL_REGEX = std::regex(DECIMAL)
const std::regex HEX_REGEX = std::regex(HEX)
const std::regex BINARY_REGEX = std::regex(BINARY)
const std::regex OCT_REGEX = std::regex(OCT)
const std::regex CHARACTER_REGEX = std::regex(CHARACTER)
const std::regex LITERAL_REGEX = std::regex(LITERAL)
const std::regex OPERATOR_REGEX = std::regex(OPERATOR)
const std::regex SYMBOL_REGEX = std::regex(SYMBOL)
const std::regex LABEL_REGEX = std::regex(LABEL)
const std::regex CONSTANT_TERM_REGEX = std::regex(CONSTANT_TERM)
const std::regex ORG_DIRECTIVE_REGEX = std::regex(ORG_DIRECTIVE)
const std::regex SYMBOL_DEFINITION_REGEX = std::regex(SYMBOL_DEFINITION)
const std::regex DUPLICATE_DIRECTIVE_REGEX = std::regex(DUPLICATE_DIRECTIVE)
const std::regex GLOBAL_DIRECTIVE_REGEX = std::regex(GLOBAL_DIRECTIVE)
const std::regex COMMA_TOKENIZER_REGEX = std::regex(COMMA_TOKENIZER)
const std::regex LAST_COMMA_TOKEN_REGEX = std::regex(LAST_COMMA_TOKEN)
static const int32_t UNSIGNED_BYTE_MASK = 0x000000ff
static const int32_t UNSIGNED_WORD_MASK = 0x0000ffff
static const int32_t SIGNED_BYTE_TEST = 0x00000080
static const int32_t SIGNED_WORD_TEST = 0x00008000
static const int32_t SIGNED_BYTE_FILL = 0xffffff00
static const int32_t SIGNED_WORD_FILL = 0xffff0000
static const uint64_t TOP_32_BITS = ~static_cast<uint64_t>(0) << 32
Enumeration Type Documentation
AddressMode
enum bnssemulator::AddressMode : uint32_t
Enum representing the address mode.
Enumerator
IMMEDIATE
REGISTER_DIRECT
MEMORY_DIRECT
REGISTER_INDIRECT
REGISTER_INDIRECT_OFFSET
Definition at line 10 of file AddressMode.h.
                      : uint32_t {
         IMMEDIATE = 0b100,
         REGISTER_DIRECT = 0b000,
         MEMORY_DIRECT = 0b110,
         REGISTER_INDIRECT = 0b010,
         REGISTER_INDIRECT_OFFSET = 0b111
     };
DataType
enum bnssemulator::DataType : int8_t
Enum representing a data type.
Enumerator
DOUBLE_WORD
32bit value
WORD
16bit value
BYTE
8bit value
Definition at line 9 of file DataType.h.
                   : int8_t {
         DOUBLE_WORD = 0,
         WORD,
         BYTE
     };
InstructionCode
enum bnssemulator::InstructionCode : int8_t
Enum representing the instruction code.
Enumerator
INT
JMP
CALL
RET
JZ
JNZ
JGZ
JGEZ
JLZ
JLEZ
LOAD
STORE
PUSH
POP
ADD
SUB
MUL
DIV
MOD
AND
OR
XOR
NOT
ASL
ASR
Definition at line 12 of file InstructionCode.h.
                          : int8_t {
         INT   = 0x00,
         JMP   = 0x02,
         CALL  = 0x03,
         RET   = 0x01,
         JZ    = 0x04,
         JNZ   = 0x05,
         JGZ   = 0x06,
         JGEZ  = 0x07,
         JLZ   = 0x08,
         JLEZ  = 0x09,
         LOAD  = 0x10,
         STORE = 0x11,
         PUSH  = 0x20,
         POP   = 0x21,
         ADD   = 0x30,
         SUB   = 0x31,
         MUL   = 0x32,
         DIV   = 0x33,
         MOD   = 0x34,
         AND   = 0x35,
         OR    = 0x36,
         XOR   = 0x37,
         NOT   = 0x38,
         ASL   = 0x39,
         ASR   = 0x3A
     };
OperandType
enum bnssemulator::OperandType : int8_t
Enum representing the operand type.
Enumerator
DEFAULT
UNSIGNED_BYTE
SIGNED_BYTE
REGULAR_BYTE
UNSIGNED_WORD
SIGNED_WORD
REGULAR_WORD
REGULAR_DOUBLE_WORD
Definition at line 10 of file OperandType.h.
                      : int8_t {
         DEFAULT = 0b000,
         UNSIGNED_BYTE = 0b011,
         SIGNED_BYTE = 0b111,
         REGULAR_BYTE = 0b111,
         UNSIGNED_WORD = 0b001,
         SIGNED_WORD = 0b101,
         REGULAR_WORD = 0b101,
         REGULAR_DOUBLE_WORD = 0b000
     };
SectionType
enum bnssemulator::SectionType : int8_t
Enum representing the type of the section.
Enumerator
TEXT
Text section
DATA
Data section
RODATA
Read-only data section
BSS
Block started by symbol section
Definition at line 11 of file SectionType.h.
                      : int8_t {
         TEXT = 0,
         DATA,
         RODATA,
         BSS
     };
Function Documentation
checkOverlaps()
static bool bnssemulator::checkOverlaps (const std::vector< SectionData > & section_table) static
Definition at line 23 of file AddressSpace.cpp.
Referenced by bnssemulator::AddressSpace::AddressSpace().
{
         std::vector<std::pair<uint32_t, uint32_t>> check;
         for (auto &section : section_table) {
             if (section.hasAddress()) {
                 check.push_back(std::make_pair(section.address(), section.address() + section.size() - 1));
             }
         }
         sort(check.begin(), check.end(), compare_pair_first<uint32_t, uint32_t>());
         for (size_t i = 1; i < check.size(); i++) {
             if (check[i - 1].second >= check[i].first) {
                 return true;
             }
         }
         return false;
     }
fill()
static uint32_t bnssemulator::fill (OperandType type, int32_t operand) static
Definition at line 17 of file LoadExecuter.cpp.
References REGULAR_DOUBLE_WORD, SIGNED_BYTE, SIGNED_BYTE_FILL, SIGNED_WORD, SIGNED_WORD_FILL, bnssemulator::StringHelper::toHexString(), UNSIGNED_BYTE, UNSIGNED_BYTE_MASK, UNSIGNED_WORD, and UNSIGNED_WORD_MASK.
Referenced by bnssemulator::LoadExecuter::execute().
{
         switch (type) {
         case UNSIGNED_BYTE:
             return operand & UNSIGNED_BYTE_MASK;
         case SIGNED_BYTE:
             if ((operand & SIGNED_BYTE_TEST) != 0) {
                 return operand | SIGNED_BYTE_FILL;
             }
             return operand;
         case UNSIGNED_WORD:
             return operand & UNSIGNED_WORD_MASK;
         case SIGNED_WORD:
             if ((operand & SIGNED_WORD_TEST) != 0) {
                 return operand | SIGNED_WORD_FILL;
             }
             return operand;
         case REGULAR_DOUBLE_WORD:
             return operand;
         default:
             throw MessageException("Invalid operand type: " + StringHelper::toHexString(static_cast<int8_t>(type)));
         }
     }
generateAddresses()
static void bnssemulator::generateAddresses (std::vector< SectionData > & section_table, std::list< std::pair< uint32_t, uint32_t >> & available) static
Definition at line 77 of file AddressSpace.cpp.
Referenced by bnssemulator::AddressSpace::AddressSpace().
{
         for (auto &section : section_table) {
             if (!section.hasAddress()) {
                 auto found = false;
                 for (auto iterator = available.begin(); iterator != available.end(); ++iterator) {
                     if (iterator->second - iterator->first >= section.size()) {
                         found = true;
                         section.address(iterator->first);
                         iterator->first += section.size();
                         if (iterator->first == iterator->second) {
                             available.erase(iterator);
                         }
                         break;
                     }
                 }
                 if (!found) {
                     throw MessageException("There is not enough space for all the sections");
                 }
             }
         }
     }
getAvailable()
static std::list<std::pair<uint32_t, uint32_t> > bnssemulator::getAvailable (const std::vector< SectionData > & section_table) static
Definition at line 42 of file AddressSpace.cpp.
Referenced by bnssemulator::AddressSpace::AddressSpace().
{
         std::set<std::pair<uint32_t, uint32_t>, compare_pair_first<uint32_t, uint32_t>> set{{0, 0xffffffff}};
         for (auto &section : section_table) {
             if (section.hasAddress()) {
                 auto section_pair = std::make_pair(section.address(), section.address() + section.size() - 1);
                 auto upper = set.upper_bound(section_pair);
                 --upper;
                 auto left = std::make_pair(upper->first, section_pair.first - 1);
                 auto right = std::make_pair(section_pair.second + 1, upper->second);
                 set.erase(upper);
                 if (left.first != left.second + 1) {
                     set.insert(left);
                 }
                 if (right.first != right.second + 1) {
                     set.insert(right);
                 }
             }
         }
         std::list<std::pair<uint32_t, uint32_t>> ret;
         for (auto &entry : set) {
             ret.push_back(entry);
         }
         return ret;
     }
getRegisterIndex()
static size_t bnssemulator::getRegisterIndex (InstructionBitField instruction, size_t register_index) static
Gets the index of the register in the array of registers.
Parameters
instruction Instruction
register_index Index of the register in the instruction
Returns
Index of the register in the array
Definition at line 81 of file Context.cpp.
References bnssemulator::StringHelper::numberFormat(), bnssemulator::InstructionBitField::register0, bnssemulator::InstructionBitField::register1, and bnssemulator::InstructionBitField::register2.
Referenced by bnssemulator::Context::getOperand(), and bnssemulator::Context::getOperandAddress().
{
         switch (register_index) {
         case 0:
             return instruction.register0;
         case 1:
             return instruction.register1;
         case 2:
             return instruction.register2;
         default:
             throw MessageException("Invalid register index: " + StringHelper::numberFormat(register_index));
         }
     }
opcode()
static InstructionCode bnssemulator::opcode (InstructionBitField instruction) static
Definition at line 72 of file Processor.cpp.
References bnssemulator::InstructionBitField::operation_code.
Referenced by bnssemulator::Processor::executeInstruction().
{
         return static_cast<InstructionCode>(instruction.operation_code);
     }
operator &()
Register bnssemulator::operator& (const Register & lhs, const Register & rhs) noexcept
Definition at line 131 of file Register.cpp.
References bnssemulator::Register::Register().
{
         return Register(lhs.value_ & rhs.value_);
     }
operator%()
Register bnssemulator::operator% (const Register & lhs, const Register & rhs) noexcept
Definition at line 127 of file Register.cpp.
References bnssemulator::Register::Register().
{
         return Register(lhs.value_ % rhs.value_);
     }
operator*()
Register bnssemulator::operator* (const Register & lhs, const Register & rhs) noexcept
Definition at line 112 of file Register.cpp.
References bnssemulator::Register::Register(), and TOP_32_BITS.
{
         auto result_value = static_cast<int64_t>(lhs.value_) + static_cast<int64_t>(rhs.value_);
         auto left = static_cast<bool>(lhs.value_ & INT32_MIN);
         auto right = static_cast<bool>(rhs.value_ & INT32_MIN);
         auto result = static_cast<bool>(result_value & INT32_MIN);
         auto flags = ((result_value & TOP_32_BITS) != 0) || (!left && !right && result);
         return Register(static_cast<int32_t>(result_value), flags, flags);
     }
operator+()
Register bnssemulator::operator+ (const Register & lhs, const Register & rhs) noexcept
Definition at line 97 of file Register.cpp.
References bnssemulator::Register::Register().
{
         auto result_value = static_cast<int64_t>(lhs.value_) + static_cast<int64_t>(rhs.value_);
         auto left = static_cast<bool>(lhs.value_ & INT32_MIN);
         auto right = static_cast<bool>(rhs.value_ & INT32_MIN);
         auto result = static_cast<bool>(result_value & INT32_MIN);
         auto flags = (left && right && !result) || (!left && !right && result);
         return Register(static_cast<int32_t>(result_value), flags, flags);
     }
operator-()
Register bnssemulator::operator- (const Register & lhs, const Register & rhs) noexcept
Definition at line 108 of file Register.cpp.
{
         return lhs + -rhs;
     }
operator/()
Register bnssemulator::operator/ (const Register & lhs, const Register & rhs) noexcept
Definition at line 123 of file Register.cpp.
References bnssemulator::Register::Register().
{
         return Register(lhs.value_ / rhs.value_);
     }
operator<<()
Register bnssemulator::operator<< (const Register & lhs, const Register & rhs) noexcept
Definition at line 143 of file Register.cpp.
References bnssemulator::Register::Register(), TOP_32_BITS, and bnssemulator::Register::value_.
{
         auto shift = rhs.value_ % 32;
         auto result = lhs.value_ << shift;
         auto carry = (result & TOP_32_BITS) != 0;
         return Register(result, carry, false);
     }
operator>>() [1/5]
std::istream& bnssemulator::operator>> (std::istream & is, RelocationRecord & data)
Parameters
is Input stream
data Reference to the object that should be loaded
Returns
Input stream
Definition at line 5 of file RelocationRecord.cpp.
References bnssemulator::RelocationRecord::absolute_, bnssemulator::RelocationRecord::offset_, bnssemulator::RelocationRecord::section_, bnssemulator::RelocationRecord::section_index_, and bnssemulator::RelocationRecord::symbol_name_.
{
         is >> data.offset_;
         is >> data.absolute_;
         is >> data.section_;
         if (data.section_) {
             is >> data.section_index_;
         }
         else {
             is >> data.symbol_name_;
         }
         return is;
     }
operator>>() [2/5]
std::istream& bnssemulator::operator>> (std::istream & is, SectionData & data)
Parameters
is Input stream
data Reference to the object that should be loaded
Returns
Input stream
Definition at line 6 of file SectionData.cpp.
References bnssemulator::SectionData::data_, bnssemulator::SectionData::index_, bnssemulator::SectionData::indexed_, bnssemulator::SectionData::location_counter_, bnssemulator::SectionData::org_address_, bnssemulator::SectionData::org_valid_, bnssemulator::SectionData::relocation_records_, and bnssemulator::SectionData::type_.
{
         int type;
         is >> type;
         data.type_ = static_cast<SectionType>(type);
         is >> data.indexed_;
         if (data.indexed_) {
             is >> data.index_;
         }
         is >> data.org_valid_;
         if (data.org_valid_) {
             is >> data.org_address_;
         }
         is >> data.location_counter_;
         size_t data_size;
         is >> data_size;
         for (size_t i = 0; i < data_size; i++) {
             int data_byte;
             is >> data_byte;
             data.data_.push_back(static_cast<int8_t>(data_byte));
         }
         size_t relocation_records_size;
         is >> relocation_records_size;
         for (size_t i = 0; i < relocation_records_size; i++) {
             RelocationRecord relocation_record;
             is >> relocation_record;
             data.relocation_records_.push_back(relocation_record);
         }
         return is;
     }
operator>>() [3/5]
std::istream& bnssemulator::operator>> (std::istream & is, AssemblerOutput & data)
Parameters
is Input stream
data Reference to the object that should be loaded
Returns
Input stream
Definition at line 7 of file AssemblerOutput.cpp.
References bnssemulator::AssemblerOutput::imported_symbols_, bnssemulator::AssemblerOutput::section_table_, and bnssemulator::AssemblerOutput::symbol_table_.
{
         size_t num_of_imported_symbols;
         is >> num_of_imported_symbols;
         for (size_t i = 0; i < num_of_imported_symbols; i++) {
             std::string symbol;
             is >> symbol;
             data.imported_symbols_.insert(symbol);
         }
         size_t section_table_size;
         is >> section_table_size;
         for (size_t i = 0; i < section_table_size; i++) {
             SectionData section;
             is >> section;
             data.section_table_.push_back(section);
         }
         size_t symbol_table_size;
         is >> symbol_table_size;
         for (size_t i = 0; i < symbol_table_size; i++) {
             SymbolData symbol;
             is >> symbol;
             data.symbol_table_[symbol.name()] = symbol;
         }
         return is;
     }
operator>>() [4/5]
std::istream& bnssemulator::operator>> (std::istream & is, SymbolData & data)
Parameters
is Input stream
data Reference to the object that should be loaded
Returns
Input stream
Definition at line 17 of file SymbolData.cpp.
References bnssemulator::SymbolData::local_, bnssemulator::SymbolData::name_, bnssemulator::SymbolData::offset_, and bnssemulator::SymbolData::section_index_.
{
         is >> data.name_;
         is >> data.section_index_;
         is >> data.offset_;
         is >> data.local_;
         return is;
     }
operator>>() [5/5]
Register bnssemulator::operator>> (const Register & lhs, const Register & rhs) noexcept
Definition at line 152 of file Register.cpp.
References bnssemulator::Register::Register(), and bnssemulator::Register::value_.
{
         auto shift = rhs.value_ % 32;
         auto result = lhs.value_ >> shift;
         auto back = result << shift;
         auto carry = lhs.value_ != back;
         return Register(result, carry, false);
     }
operator^()
Register bnssemulator::operator^ (const Register & lhs, const Register & rhs) noexcept
Definition at line 139 of file Register.cpp.
References bnssemulator::Register::Register().
{
         return Register(lhs.value_ ^ rhs.value_);
     }
operator|()
Register bnssemulator::operator| (const Register & lhs, const Register & rhs) noexcept
Definition at line 135 of file Register.cpp.
References bnssemulator::Register::Register().
{
         return Register(lhs.value_ | rhs.value_);
     }
removeEmpty()
static void bnssemulator::removeEmpty (std::vector< SectionData > & section_table) static
Definition at line 12 of file AddressSpace.cpp.
Referenced by bnssemulator::AddressSpace::AddressSpace().
{
         size_t j = 0;
         for (size_t i = 0; i < section_table.size(); i++) {
             if (section_table[i].size() != 0) {
                 section_table[j++] = section_table[i];
             }
         }
         section_table.resize(j);
     }
Variable Documentation
BINARY
const std::string bnssemulator::BINARY = "0b[01][01]*"
Definition at line 10 of file CommonRegexes.h.
BINARY_REGEX
const std::regex bnssemulator::BINARY_REGEX = std::regex(BINARY)
Definition at line 36 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().
BLOCK_BITS
const size_t bnssemulator::BLOCK_BITS = 16
Definition at line 9 of file Address.h.
BLOCK_SIZE
const size_t bnssemulator::BLOCK_SIZE = OFFSET_MASK + 1
Definition at line 12 of file Address.h.
CHARACTER
const std::string bnssemulator::CHARACTER = "'[[:print:]]'"
Definition at line 12 of file CommonRegexes.h.
CHARACTER_REGEX
const std::regex bnssemulator::CHARACTER_REGEX = std::regex(CHARACTER)
Definition at line 38 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().
COMMA_TOKENIZER
const std::string bnssemulator::COMMA_TOKENIZER = "[[:space:]]*(.*?)[[:space:]]*,(.*)"
Definition at line 30 of file CommonRegexes.h.
COMMA_TOKENIZER_REGEX
const std::regex bnssemulator::COMMA_TOKENIZER_REGEX = std::regex(COMMA_TOKENIZER)
Definition at line 51 of file CommonRegexes.h.
CONSTANT_TERM
const std::string bnssemulator::CONSTANT_TERM = "([[:space:]]*(" + LITERAL + "|" + OPERATOR + "|" + SYMBOL + ")[[:space:]]*)*"
Definition at line 23 of file CommonRegexes.h.
CONSTANT_TERM_REGEX
const std::regex bnssemulator::CONSTANT_TERM_REGEX = std::regex(CONSTANT_TERM)
Definition at line 44 of file CommonRegexes.h.
DECIMAL
const std::string bnssemulator::DECIMAL = "[1-9][0-9]*"
Definition at line 8 of file CommonRegexes.h.
DECIMAL_REGEX
const std::regex bnssemulator::DECIMAL_REGEX = std::regex(DECIMAL)
Definition at line 34 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().
DUPLICATE_DIRECTIVE
const std::string bnssemulator::DUPLICATE_DIRECTIVE = "[Dd][Uu][Pp]"
Definition at line 27 of file CommonRegexes.h.
DUPLICATE_DIRECTIVE_REGEX
const std::regex bnssemulator::DUPLICATE_DIRECTIVE_REGEX = std::regex(DUPLICATE_DIRECTIVE)
Definition at line 48 of file CommonRegexes.h.
GLOBAL_DIRECTIVE
const std::string bnssemulator::GLOBAL_DIRECTIVE = "[.][Gg][Ll][Oo][Bb][Aa][Ll]"
Definition at line 28 of file CommonRegexes.h.
GLOBAL_DIRECTIVE_REGEX
const std::regex bnssemulator::GLOBAL_DIRECTIVE_REGEX = std::regex(GLOBAL_DIRECTIVE)
Definition at line 49 of file CommonRegexes.h.
HEX
const std::string bnssemulator::HEX = "0x[0-9a-fA-F][0-9a-fA-F]*"
Definition at line 9 of file CommonRegexes.h.
HEX_REGEX
const std::regex bnssemulator::HEX_REGEX = std::regex(HEX)
Definition at line 35 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().
LABEL
const std::string bnssemulator::LABEL = SYMBOL
Definition at line 22 of file CommonRegexes.h.
LABEL_REGEX
const std::regex bnssemulator::LABEL_REGEX = std::regex(LABEL)
Definition at line 43 of file CommonRegexes.h.
LAST_COMMA_TOKEN
const std::string bnssemulator::LAST_COMMA_TOKEN = "[[:space:]]*(.*)[[:space:]]*"
Definition at line 31 of file CommonRegexes.h.
LAST_COMMA_TOKEN_REGEX
const std::regex bnssemulator::LAST_COMMA_TOKEN_REGEX = std::regex(LAST_COMMA_TOKEN)
Definition at line 52 of file CommonRegexes.h.
LITERAL
const std::string bnssemulator::LITERAL = "(" + ZERO + "|" + DECIMAL + "|" + HEX + "|" + BINARY + "|" + OCT + "|" + CHARACTER + ")"
Definition at line 17 of file CommonRegexes.h.
LITERAL_REGEX
const std::regex bnssemulator::LITERAL_REGEX = std::regex(LITERAL)
Definition at line 40 of file CommonRegexes.h.
OCT
const std::string bnssemulator::OCT = "0[0-7][0-7]*"
Definition at line 11 of file CommonRegexes.h.
OCT_REGEX
const std::regex bnssemulator::OCT_REGEX = std::regex(OCT)
Definition at line 37 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().
OFFSET_MASK
const uint32_t bnssemulator::OFFSET_MASK = ~PAGE_MASK
Definition at line 11 of file Address.h.
OPERATOR
const std::string bnssemulator::OPERATOR = "[-+*/()]"
Definition at line 20 of file CommonRegexes.h.
OPERATOR_REGEX
const std::regex bnssemulator::OPERATOR_REGEX = std::regex(OPERATOR)
Definition at line 41 of file CommonRegexes.h.
ORG_DIRECTIVE
const std::string bnssemulator::ORG_DIRECTIVE = "[Oo][Rr][Gg]"
Definition at line 25 of file CommonRegexes.h.
ORG_DIRECTIVE_REGEX
const std::regex bnssemulator::ORG_DIRECTIVE_REGEX = std::regex(ORG_DIRECTIVE)
Definition at line 46 of file CommonRegexes.h.
PAGE_MASK
const uint32_t bnssemulator::PAGE_MASK = ~0 << BLOCK_BITS
Definition at line 10 of file Address.h.
SIGNED_BYTE_FILL
const int32_t bnssemulator::SIGNED_BYTE_FILL = 0xffffff00 static
Definition at line 14 of file LoadExecuter.cpp.
Referenced by fill().
SIGNED_BYTE_TEST
const int32_t bnssemulator::SIGNED_BYTE_TEST = 0x00000080 static
Definition at line 11 of file LoadExecuter.cpp.
SIGNED_WORD_FILL
const int32_t bnssemulator::SIGNED_WORD_FILL = 0xffff0000 static
Definition at line 15 of file LoadExecuter.cpp.
Referenced by fill().
SIGNED_WORD_TEST
const int32_t bnssemulator::SIGNED_WORD_TEST = 0x00008000 static
Definition at line 12 of file LoadExecuter.cpp.
SYMBOL
const std::string bnssemulator::SYMBOL = "(([a-zA-Z_][a-zA-Z_0-9]*)|\\$)"
Definition at line 21 of file CommonRegexes.h.
SYMBOL_DEFINITION
const std::string bnssemulator::SYMBOL_DEFINITION = "[Dd][Ee][Ff]"
Definition at line 26 of file CommonRegexes.h.
SYMBOL_DEFINITION_REGEX
const std::regex bnssemulator::SYMBOL_DEFINITION_REGEX = std::regex(SYMBOL_DEFINITION)
Definition at line 47 of file CommonRegexes.h.
SYMBOL_REGEX
const std::regex bnssemulator::SYMBOL_REGEX = std::regex(SYMBOL)
Definition at line 42 of file CommonRegexes.h.
TOP_32_BITS
const uint64_t bnssemulator::TOP_32_BITS = ~static_cast<uint64_t>(0) << 32 static
Definition at line 5 of file Register.cpp.
Referenced by operator*(), and operator<<().
UNSIGNED_BYTE_MASK
const int32_t bnssemulator::UNSIGNED_BYTE_MASK = 0x000000ff static
Definition at line 8 of file LoadExecuter.cpp.
Referenced by fill().
UNSIGNED_WORD_MASK
const int32_t bnssemulator::UNSIGNED_WORD_MASK = 0x0000ffff static
Definition at line 9 of file LoadExecuter.cpp.
Referenced by fill().
ZERO
const std::string bnssemulator::ZERO = "0"
Definition at line 7 of file CommonRegexes.h.
ZERO_REGEX
const std::regex bnssemulator::ZERO_REGEX = std::regex(ZERO)
Definition at line 33 of file CommonRegexes.h.
Referenced by bnssemulator::StringHelper::parseNumber().