AssemblerEmulator - Nikola Bebic: cxxopts Namespace Reference
cxxopts Namespace Reference
Namespaces
anonymous_namespace{cxxopts.h}
values
Classes
class argument_incorrect_type
struct HelpGroupDetails
struct HelpOptionDetails
class invalid_option_format_error
class missing_argument_exception
class option_exists_error
class option_not_exists_exception
class option_not_has_argument_exception
class option_not_present_exception
class option_required_exception
class option_requires_argument_exception
class OptionAdder
class OptionDetails
class OptionException
class OptionParseException
class Options
class OptionSpecException
class Value
Typedefs
typedef std::string String
Functions
template<typename T >
T toLocalString (T &&t)
size_t stringLength (const String &s)
String & stringAppend (String &s, String a)
String & stringAppend (String &s, size_t n, char c)
template<typename Iterator >
String & stringAppend (String &s, Iterator begin, Iterator end)
template<typename T >
std::string toUTF8String (T &&t)
bool empty (const std::string &s)
template<typename T >
std::shared_ptr< Value > value ()
template<typename T >
std::shared_ptr< Value > value (T &t)
void check_required (const Options &options, const std::vector< std::string > &required)
Typedef Documentation
String
typedef std::string cxxopts::String
Definition at line 184 of file cxxopts.h.
Function Documentation
check_required()
void cxxopts::check_required (const Options & options, const std::vector< std::string > & required) inline
Definition at line 849 of file cxxopts.h.
References cxxopts::Options::count().
Referenced by cxxopts::OptionAdder::OptionAdder().
     {
         for (auto& r : required)
         {
             if (options.count(r) == 0)
             {
                 throw option_required_exception(r);
             }
         }
     }
empty()
bool cxxopts::empty (const std::string & s) inline
Definition at line 230 of file cxxopts.h.
Referenced by cxxopts::Options::generate_group_help(), and cxxopts::OptionAdder::OptionAdder().
     {
         return s.empty();
     }
stringAppend() [1/3]
String & cxxopts::stringAppend (String & s, String a) inline
Definition at line 202 of file cxxopts.h.
Referenced by cxxopts::anonymous_namespace{cxxopts.h}::format_description(), and cxxopts::OptionAdder::OptionAdder().
     {
         return s.append(std::move(a));
     }
stringAppend() [2/3]
String & cxxopts::stringAppend (String & s, size_t n, char c) inline
Definition at line 209 of file cxxopts.h.
     {
         return s.append(n, c);
     }
stringAppend() [3/3]
template<typename Iterator > String & cxxopts::stringAppend (String & s, Iterator begin, Iterator end)
Definition at line 216 of file cxxopts.h.
     {
         return s.append(begin, end);
     }
stringLength()
size_t cxxopts::stringLength (const String & s) inline
Definition at line 195 of file cxxopts.h.
Referenced by cxxopts::Options::help_one_group(), and cxxopts::OptionAdder::OptionAdder().
     {
         return s.length();
     }
toLocalString()
template<typename T > T cxxopts::toLocalString (T && t)
Definition at line 188 of file cxxopts.h.
Referenced by cxxopts::Options::add_option(), cxxopts::anonymous_namespace{cxxopts.h}::format_description(), cxxopts::anonymous_namespace{cxxopts.h}::format_option(), cxxopts::Options::help(), cxxopts::Options::help_one_group(), and cxxopts::OptionAdder::OptionAdder().
     {
         return t;
     }
toUTF8String()
template<typename T > std::string cxxopts::toUTF8String (T && t)
Definition at line 223 of file cxxopts.h.
Referenced by cxxopts::Options::help(), and cxxopts::OptionAdder::OptionAdder().
     {
         return std::forward<T>(t);
     }
value() [1/2]
template<typename T > std::shared_ptr< Value > cxxopts::value ()
Definition at line 567 of file cxxopts.h.
Referenced by cxxopts::Options::add_option(), cxxopts::values::standard_value< T >::default_value(), cxxopts::values::standard_value< T >::get(), cxxopts::values::standard_value< T >::implicit_value(), bnssassembler::LiteralToken::LiteralToken(), cxxopts::option_required_exception::option_required_exception(), cxxopts::OptionAdder::OptionAdder(), cxxopts::Options::positional_help(), bnssemulator::Context::timerTriggered(), Z85_decode_unsafe(), and Z85_encode_unsafe().
     {
         return std::make_shared<values::standard_value<T>>();
     }
value() [2/2]
template<typename T > std::shared_ptr< Value > cxxopts::value (T & t)
Definition at line 574 of file cxxopts.h.
     {
         return std::make_shared<values::standard_value<T>>(&t);
     }