AssemblerEmulator - Nikola Bebic: cxxopts::anonymous_namespace{cxxopts.h} Namespace Reference
cxxopts::anonymous_namespace{cxxopts.h} Namespace Reference
Functions
std::basic_regex< char > option_matcher ("--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)")
std::basic_regex< char > option_specifier ("(([[:alnum:]]),)?([[:alnum:]][-_[:alnum:]]*)?")
String format_option (const HelpOptionDetails &o)
String format_description (const HelpOptionDetails &o, size_t start, size_t width)
Variables
constexpr int OPTION_LONGEST = 30
constexpr int OPTION_DESC_GAP = 2
Function Documentation
format_description()
String cxxopts::anonymous_namespace{cxxopts.h}::format_description (const HelpOptionDetails & o, size_t start, size_t width)
Definition at line 918 of file cxxopts.h.
References cxxopts::HelpOptionDetails::default_value, cxxopts::HelpOptionDetails::desc, cxxopts::HelpOptionDetails::has_default, cxxopts::stringAppend(), and cxxopts::toLocalString().
Referenced by format_option(), cxxopts::Options::help_one_group(), and cxxopts::OptionAdder::OptionAdder().
         {
             auto desc = o.desc;
             if (o.has_default)
             {
                 desc += toLocalString(" (default: " + o.default_value + ")");
             }
             String result;
             auto current = std::begin(desc);
             auto startLine = current;
             auto lastSpace = current;
             auto size = size_t{};
             while (current != std::end(desc))
             {
                 if (*current == ' ')
                 {
                     lastSpace = current;
                 }
                 if (size > width)
                 {
                     if (lastSpace == startLine)
                     {
                         stringAppend(result, startLine, current + 1);
                         stringAppend(result, "\n");
                         stringAppend(result, start, ' ');
                         startLine = current + 1;
                         lastSpace = startLine;
                     }
                     else
                     {
                         stringAppend(result, startLine, lastSpace);
                         stringAppend(result, "\n");
                         stringAppend(result, start, ' ');
                         startLine = lastSpace + 1;
                     }
                     size = 0;
                 }
                 else
                 {
                     ++size;
                 }
                 ++current;
             }
             //append whatever is left
             stringAppend(result, startLine, current);
             return result;
         }
format_option()
String cxxopts::anonymous_namespace{cxxopts.h}::format_option (const HelpOptionDetails & o)
Definition at line 876 of file cxxopts.h.
References cxxopts::HelpOptionDetails::arg_help, format_description(), cxxopts::HelpOptionDetails::has_arg, cxxopts::HelpOptionDetails::has_implicit, cxxopts::HelpOptionDetails::implicit_value, cxxopts::HelpOptionDetails::l, cxxopts::HelpOptionDetails::s, and cxxopts::toLocalString().
Referenced by cxxopts::Options::help_one_group(), and cxxopts::OptionAdder::OptionAdder().
         {
             auto& s = o.s;
             auto& l = o.l;
             String result = "  ";
             if (s.size() > 0)
             {
                 result += "-" + toLocalString(s) + ",";
             }
             else
             {
                 result += "   ";
             }
             if (l.size() > 0)
             {
                 result += " --" + toLocalString(l);
             }
             if (o.has_arg)
             {
                 auto arg = o.arg_help.size() > 0 ? toLocalString(o.arg_help) : "arg";
                 if (o.has_implicit)
                 {
                     result += " [=" + arg + "(=" + toLocalString(o.implicit_value) + ")]";
                 }
                 else
                 {
                     result += " " + arg;
                 }
             }
             return result;
         }
option_matcher()
std::basic_regex< char > cxxopts::anonymous_namespace{cxxopts.h}::option_matcher ("--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)")
Referenced by cxxopts::OptionAdder::OptionAdder(), and cxxopts::Options::parse().
option_specifier()
std::basic_regex< char > cxxopts::anonymous_namespace{cxxopts.h}::option_specifier ("(([[:alnum:]]),)?([[:alnum:]][-_[:alnum:]]*)?")
Referenced by cxxopts::OptionAdder::operator()(), and cxxopts::OptionAdder::OptionAdder().
Variable Documentation
OPTION_DESC_GAP
constexpr int cxxopts::anonymous_namespace{cxxopts.h}::OPTION_DESC_GAP = 2
Definition at line 866 of file cxxopts.h.
Referenced by cxxopts::Options::help_one_group(), and cxxopts::OptionAdder::OptionAdder().
OPTION_LONGEST
constexpr int cxxopts::anonymous_namespace{cxxopts.h}::OPTION_LONGEST = 30
Definition at line 865 of file cxxopts.h.
Referenced by cxxopts::OptionAdder::OptionAdder().