AssemblerEmulator - Nikola Bebic: z85 Namespace Reference
z85 Namespace Reference
Functions
std::string encode_with_padding (const char *source, size_t inputSize)
Encodes 'inputSize' bytes from 'source'. If 'inputSize' is not divisible by 4 with no remainder, 'source' is padded.
std::string encode_with_padding (const std::string &source)
std::string encode_with_padding (const char *) Z85_DELETE_FUNCTION_DEFINITION
std::string decode_with_padding (const char *source, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source', encoded with encode_with_padding().
std::string decode_with_padding (const std::string &source)
std::string decode_with_padding (const char *) Z85_DELETE_FUNCTION_DEFINITION
std::string encode (const char *source, size_t inputSize)
Encodes 'inputSize' bytes from 'source'. If 'inputSize' is not divisible by 4 with no remainder, empty string is retured.
std::string encode (const std::string &source)
std::string encode (const char *) Z85_DELETE_FUNCTION_DEFINITION
std::string decode (const char *source, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source'. If 'inputSize' is not divisible by 5 with no remainder, empty string is returned.
std::string decode (const std::string &source)
std::string decode (const char *) Z85_DELETE_FUNCTION_DEFINITION
Function Documentation
decode() [1/3]
std::string z85::decode (const char * source, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source'. If 'inputSize' is not divisible by 5 with no remainder, empty string is returned.
Parameters
source in, input buffer (printable string to be decoded)
inputSize in, number of symbols to be decoded
Returns
decoded string
Definition at line 115 of file z85_impl.cpp.
References Z85_decode(), and Z85_decode_bound().
Referenced by decode().
     {
         if (!source || inputSize == 0)
         {
             return std::string();
         }
         std::string buf;
         buf.resize(Z85_decode_bound(inputSize));
         const size_t decodedBytes = Z85_decode(source, &buf[0], inputSize);
         if (decodedBytes == 0)
         {
             assert(!"wrong input size");
             return std::string();
         }
         return buf;
     }
decode() [2/3]
std::string z85::decode (const std::string & source)
Definition at line 135 of file z85_impl.cpp.
References decode().
     {
         return decode(source.c_str(), source.size());
     }
decode() [3/3]
std::string z85::decode (const char *)
decode_with_padding() [1/3]
std::string z85::decode_with_padding (const char * source, size_t inputSize)
Decodes 'inputSize' printable symbols from 'source', encoded with encode_with_padding().
Parameters
source in, input buffer (printable string to be decoded)
inputSize in, number of symbols to be decoded
Returns
decoded string
Definition at line 62 of file z85_impl.cpp.
References Z85_decode_with_padding(), and Z85_decode_with_padding_bound().
Referenced by decode_with_padding(), and bnssemulator::FileReader::parse().
     {
         if (!source || inputSize == 0)
         {
             return std::string();
         }
         const size_t bufSize = Z85_decode_with_padding_bound(source, inputSize);
         if (bufSize == 0)
         {
             assert(!"wrong padding");
             return std::string();
         }
         std::string buf;
         buf.resize(bufSize);
         const size_t decodedBytes = Z85_decode_with_padding(source, &buf[0], inputSize);
         assert(decodedBytes == buf.size()); (void)decodedBytes;
         return buf;
     }
decode_with_padding() [2/3]
std::string z85::decode_with_padding (const std::string & source)
Definition at line 85 of file z85_impl.cpp.
References decode_with_padding().
     {
         return decode_with_padding(source.c_str(), source.size());
     }
decode_with_padding() [3/3]
std::string z85::decode_with_padding (const char *)
encode() [1/3]
std::string z85::encode (const char * source, size_t inputSize)
Encodes 'inputSize' bytes from 'source'. If 'inputSize' is not divisible by 4 with no remainder, empty string is retured.
Parameters
source in, input buffer (binary string to be encoded)
inputSize in, number of bytes to be encoded
Returns
printable string
Definition at line 90 of file z85_impl.cpp.
References Z85_encode(), and Z85_encode_bound().
Referenced by encode().
     {
         if (!source || inputSize == 0)
         {
             return std::string();
         }
         std::string buf;
         buf.resize(Z85_encode_bound(inputSize));
         const size_t encodedBytes = Z85_encode(source, &buf[0], inputSize);
         if (encodedBytes == 0)
         {
             assert(!"wrong input size");
             return std::string();
         }
         return buf;
     }
encode() [2/3]
std::string z85::encode (const std::string & source)
Definition at line 110 of file z85_impl.cpp.
References encode().
     {
         return encode(source.c_str(), source.size());
     }
encode() [3/3]
std::string z85::encode (const char *)
encode_with_padding() [1/3]
std::string z85::encode_with_padding (const char * source, size_t inputSize)
Encodes 'inputSize' bytes from 'source'. If 'inputSize' is not divisible by 4 with no remainder, 'source' is padded.
Parameters
source in, input buffer (binary string to be encoded)
inputSize in, number of bytes to be encoded
Returns
printable string
Definition at line 41 of file z85_impl.cpp.
References Z85_encode_with_padding(), and Z85_encode_with_padding_bound().
Referenced by encode_with_padding(), and bnssassembler::FileWriter::write().
     {
         if (!source || inputSize == 0)
         {
             return std::string();
         }
         std::string buf;
         buf.resize(Z85_encode_with_padding_bound(inputSize));
         const size_t encodedBytes = Z85_encode_with_padding(source, &buf[0], inputSize);
         assert(encodedBytes == buf.size()); (void)encodedBytes;
         return buf;
     }
encode_with_padding() [2/3]
std::string z85::encode_with_padding (const std::string & source)
Definition at line 57 of file z85_impl.cpp.
References encode_with_padding().
     {
         return encode_with_padding(source.c_str(), source.size());
     }
encode_with_padding() [3/3]
std::string z85::encode_with_padding (const char *)